//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"

// Blocks are Tecton consumers: the libraries Tecton is built on are internal to
// @tecton/react and never imported directly (same list in apps/www).
const LIBRARY_IMPORT_MESSAGE =
  "Import from @tecton/react instead: the libraries Tecton is built on are internal (TectonProvider replaces their providers)."
const restrictedLibraryImports = {
  paths: [
    "react-aria-components",
    "react-aria",
    "react-stately",
    "@base-ui/react",
  ].map((name) => ({ name, message: LIBRARY_IMPORT_MESSAGE })),
  patterns: [
    {
      group: [
        "react-aria-components/*",
        "react-aria/*",
        "react-stately/*",
        "@react-aria/*",
        "@react-stately/*",
        "@react-types/*",
        "@internationalized/*",
        "@base-ui/react/*",
      ],
      message: LIBRARY_IMPORT_MESSAGE,
    },
  ],
}

export default [
  ...tanstackConfig,
  {
    rules: {
      "no-restricted-imports": ["error", restrictedLibraryImports],
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
      // shadcn conventions used by the generated components and followed by
      // the Tecton components and the blocks: inline `type` import specifiers
      // and `composeRenderProps(className, (className) => …)`.
      "import/consistent-type-specifier-style": "off",
      "no-shadow": "off",
    },
  },
  {
    // The registry build output is regenerated by `registry:build` and never
    // edited by hand, so it is not linted or formatted either (see also
    // .prettierignore at the repository root).
    ignores: ["eslint.config.js", ".prettierrc", "registry/**"],
  },
]
