//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"

export default [
  ...tanstackConfig,
  {
    rules: {
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
      // shadcn conventions used by the generated components and followed by
      // the Tecton components and the blocks: inline `type` import specifiers
      // and `composeRenderProps(className, (className) => …)`.
      "import/consistent-type-specifier-style": "off",
      "no-shadow": "off",
    },
  },
  {
    // The registry build output is regenerated by `registry:build` and never
    // edited by hand, so it is not linted or formatted either (see also
    // .prettierignore at the repository root).
    ignores: ["eslint.config.js", ".prettierrc", "registry/**"],
  },
]
