/// <reference types="node" />
/**
 * Renders packages/tecton-react/guidelines/*.md into the component pages.
 *
 *   bun run scripts/sync-guidelines.mts           (pnpm --filter www docs:guidelines)
 *   bun run scripts/sync-guidelines.mts --check   (CI: fails when a page is stale)
 *
 * One guideline file per module becomes one "## Usage guidelines" section:
 *
 *   @tecton/react/components/badge -> content/docs/components/badge.mdx
 *   @tecton/react/tecton/chip      -> content/docs/tecton/chip.mdx
 *
 * The section is written between `{/* guidelines:start *\/}` and
 * `{/* guidelines:end *\/}`, before "## API Reference" when the page has one and
 * at the end when it does not. Everything outside the markers is left alone, so
 * a hand-written page and a page generated by docs:sync are treated the same —
 * and docs:sync calls `withGuidelines` itself, right after it inserts the
 * docs-extras block, so a synced page keeps its section.
 *
 * Plain markdown only: the section has to render in a page that knows nothing
 * about it, so it uses headings, bullets, bold and fenced code and no MDX
 * components.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import {
  MODULE_DIRS,
  loadGuidelines,
  renderNotFor,
} from "../../../packages/tecton-react/scripts/guidelines-lib.mts"
import type { Catalog, Guideline } from "../../../packages/tecton-react/scripts/guidelines-lib.mts"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const WWW = path.resolve(HERE, "..")
const DOCS = path.join(WWW, "content/docs")

export const START = "{/* guidelines:start */}"
export const END = "{/* guidelines:end */}"
const API_REFERENCE = "\n## API Reference"

type Loaded = { catalog: Catalog; valid: Map<string, Guideline>; invalid: Map<string, string[]> }

let loaded: Loaded | null = null

/** Parsed once per process: docs:sync calls `withGuidelines` for every page. */
function guidelines(): Loaded {
  if (!loaded) {
    // --guidelines <dir> reads a fixture folder instead of the package's own.
    const at = process.argv.indexOf("--guidelines")
    const dir = at === -1 ? undefined : path.resolve(process.argv[at + 1] ?? "")
    const { catalog, valid, invalid } = dir ? loadGuidelines(dir) : loadGuidelines()
    loaded = { catalog, valid, invalid }
  }
  return loaded
}

// ---------------------------------------------------------------------------
// rendering
// ---------------------------------------------------------------------------

export function renderSection(guideline: Guideline, catalog: Catalog): string {
  const dont = guideline.sections.dontEntries.map((entry) =>
    [`**${entry.severity}**`, "", `#### ${entry.title}`, "", entry.body].join("\n")
  )
  return [
    START,
    "",
    "## Usage guidelines",
    "",
    "### Use it when",
    "",
    guideline.sections.useWhen,
    "",
    "### Not for",
    "",
    renderNotFor(guideline.meta, catalog, "docs").join("\n"),
    "",
    "### Do",
    "",
    guideline.sections.do,
    "",
    "### Don't",
    "",
    dont.join("\n\n"),
    "",
    END,
  ].join("\n")
}

/** Replaces the marked section, or inserts it before "## API Reference". */
export function insertSection(mdx: string, section: string): string {
  const start = mdx.indexOf(START)
  const end = mdx.indexOf(END)
  if (start !== -1 && end !== -1 && end > start) {
    return mdx.slice(0, start) + section + mdx.slice(end + END.length)
  }
  const at = mdx.indexOf(API_REFERENCE)
  if (at === -1) return `${mdx.trimEnd()}\n\n${section}\n`
  return `${mdx.slice(0, at).trimEnd()}\n\n${section}\n${mdx.slice(at)}`
}

export function removeSection(mdx: string): string {
  const start = mdx.indexOf(START)
  const end = mdx.indexOf(END)
  if (start === -1 || end === -1 || end < start) return mdx
  return `${mdx.slice(0, start).trimEnd()}\n\n${mdx.slice(end + END.length).trimStart()}`
}

/**
 * The page content with its guidelines section up to date. Exported for
 * sync-upstream-docs.mts, which calls it on the page it just generated.
 * `moduleKey` is `components/<name>` or `tecton/<name>`.
 */
export function withGuidelines(mdx: string, moduleKey: string): string {
  const { catalog, valid } = guidelines()
  const guideline = valid.get(moduleKey)
  if (!guideline) return removeSection(mdx)
  return insertSection(mdx, renderSection(guideline, catalog))
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

/** Every `<dir>/<name>.mdx` under content/docs that a module could own. */
function docsPages(): Map<string, string> {
  const pages = new Map<string, string>()
  for (const dir of MODULE_DIRS) {
    const full = path.join(DOCS, dir)
    if (!existsSync(full)) continue
    for (const entry of readdirSync(full)) {
      if (!entry.endsWith(".mdx") || entry === "index.mdx") continue
      pages.set(`${dir}/${entry.slice(0, -".mdx".length)}`, path.join(full, entry))
    }
  }
  return pages
}

function main() {
  const check = process.argv.includes("--check")
  const { catalog, valid, invalid } = guidelines()
  const pages = docsPages()
  const changed: string[] = []
  const missing: string[] = []

  for (const [file, errors] of invalid) {
    console.error(`✗ ${path.basename(file)}: ${errors.length} problem(s) — run guidelines:check`)
  }

  const targets = new Set([...valid.keys(), ...pages.keys()])
  for (const moduleKey of [...targets].sort()) {
    const page = pages.get(moduleKey)
    const guideline = valid.get(moduleKey)
    if (!page) {
      if (guideline) missing.push(moduleKey)
      continue
    }
    const current = readFileSync(page, "utf8")
    const eol = current.includes("\r\n") ? "\r\n" : "\n"
    const lf = current.replace(/\r\n/g, "\n")
    if (!guideline && !lf.includes(START)) continue
    const next = guideline
      ? insertSection(lf, renderSection(guideline, catalog))
      : removeSection(lf)
    if (next === lf) continue
    changed.push(`content/docs/${moduleKey}.mdx${guideline ? "" : " (section removed)"}`)
    if (!check) writeFileSync(page, next.split("\n").join(eol))
  }

  for (const moduleKey of missing) {
    console.error(`✗ ${moduleKey}: no page at content/docs/${moduleKey}.mdx to render into`)
  }

  const summary = `${valid.size} guideline file(s), ${pages.size} page(s)`
  if (invalid.size || missing.length) {
    console.error(`docs:guidelines failed — ${invalid.size} invalid file(s), ${missing.length} page(s) missing.`)
    process.exit(1)
  }
  if (check) {
    if (changed.length) {
      console.error(`docs:guidelines --check failed — ${changed.length} page(s) stale:`)
      for (const item of changed) console.error(`  ${item}`)
      console.error("  run: pnpm --filter www docs:guidelines")
      process.exit(1)
    }
    console.log(`docs:guidelines: up to date (${summary})`)
    return
  }
  console.log(
    changed.length
      ? `docs:guidelines: updated ${changed.length} page(s) (${summary})`
      : `docs:guidelines: up to date (${summary})`
  )
}

const entry = process.argv[1] ? path.resolve(process.argv[1]) : ""
if (entry === fileURLToPath(import.meta.url)) main()
