/// <reference types="node" />
/**
 * Renders packages/tecton-react/guidelines/*.md into the component pages.
 *
 *   bun run scripts/sync-guidelines.mts           (pnpm --filter www docs:guidelines)
 *   bun run scripts/sync-guidelines.mts --check   (CI: fails when a page is stale)
 *
 * One guideline file per module becomes one "## Usage guidelines" section:
 *
 *   @tecton/react/components/badge -> content/docs/components/badge.mdx
 *   @tecton/react/tecton/chip      -> content/docs/tecton/chip.mdx
 *
 * The section is written between `{/* guidelines:start *\/}` and
 * `{/* guidelines:end *\/}`, before "## API Reference" when the page has one and
 * at the end when it does not. Everything outside the markers is left alone, so
 * a hand-written page and a page generated by docs:sync are treated the same —
 * and docs:sync calls `withGuidelines` itself, right after it inserts the
 * docs-extras block, so a synced page keeps its section.
 *
 * "Use it when" and "Not for" are plain markdown. "Do" and "Don't" are rendered
 * with the MDX components in src/components/guideline.tsx (registered in
 * src/components/mdx.tsx) so a Do reads as a check mark and a Don't as a red
 * entry with its severity and a Wrong/Correct pair. The tags sit on their own
 * lines with blank lines around the content: that is the only shape in which
 * MDX parses markdown — bullets, inline code, fenced code — inside JSX.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import {
  MODULE_DIRS,
  loadGuidelines,
  renderNotFor,
} from "../../../packages/tecton-react/scripts/guidelines-lib.mts"
import type { Catalog, Guideline } from "../../../packages/tecton-react/scripts/guidelines-lib.mts"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const WWW = path.resolve(HERE, "..")
const DOCS = path.join(WWW, "content/docs")

export const START = "{/* guidelines:start */}"
export const END = "{/* guidelines:end */}"
const API_REFERENCE = "\n## API Reference"

type Loaded = { catalog: Catalog; valid: Map<string, Guideline>; invalid: Map<string, string[]> }

let loaded: Loaded | null = null

/** Parsed once per process: docs:sync calls `withGuidelines` for every page. */
function guidelines(): Loaded {
  if (!loaded) {
    // --guidelines <dir> reads a fixture folder instead of the package's own.
    const at = process.argv.indexOf("--guidelines")
    const dir = at === -1 ? undefined : path.resolve(process.argv[at + 1] ?? "")
    const { catalog, valid, invalid } = dir ? loadGuidelines(dir) : loadGuidelines()
    loaded = { catalog, valid, invalid }
  }
  return loaded
}

// ---------------------------------------------------------------------------
// rendering
// ---------------------------------------------------------------------------

/**
 * Plain text as the value of a double-quoted JSX attribute.
 *
 * Titles are plain prose today, so this never fires; it is here so a title that
 * one day carries a quote, an angle bracket or a brace cannot break 49 pages.
 * JSX attribute values take HTML entities and no backslash escapes, so every
 * character that JSX would read goes through one.
 */
function jsxAttributeValue(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\{/g, "&#123;")
    .replace(/\}/g, "&#125;")
    .replace(/\\/g, "&#92;")
}

/** `<Tag …>` with `body` as markdown children — blank lines and all. */
function jsxBlock(open: string, close: string, body: string[]): string[] {
  return [open, "", ...body, "", close]
}

export function renderSection(guideline: Guideline, catalog: Catalog): string {
  const doList = jsxBlock(
    "<DoList>",
    "</DoList>",
    // Adopted checklist items (guidelines/adopted/*.json) read as Do bullets here;
    // adopted Do items are already in doBullets.
    [...guideline.sections.doBullets, ...guideline.adopted.checklist].flatMap((bullet, index) => [
      ...(index ? [""] : []),
      ...jsxBlock("<Do>", "</Do>", [bullet]),
    ])
  )

  const dont = guideline.sections.dontEntries.map((entry) =>
    jsxBlock(
      `<Dont severity="${jsxAttributeValue(entry.severity)}" title="${jsxAttributeValue(entry.title)}">`,
      "</Dont>",
      [
        ...jsxBlock("<Wrong>", "</Wrong>", entry.wrong.split("\n")),
        "",
        ...jsxBlock("<Correct>", "</Correct>", entry.correct.split("\n")),
        "",
        entry.closing,
      ]
    ).join("\n")
  )

  return [
    START,
    "",
    "## Usage guidelines",
    "",
    "### Use it when",
    "",
    guideline.sections.useWhen,
    "",
    "### Not for",
    "",
    renderNotFor(guideline.meta, catalog).join("\n"),
    "",
    "### Do",
    "",
    doList.join("\n"),
    "",
    "### Don't",
    "",
    dont.join("\n\n"),
    "",
    END,
  ].join("\n")
}

/**
 * Where the marked section is: both markers once and in order, or neither.
 * Anything else — a START without its END, a second START, END first — is a
 * hand edit gone wrong, and inserting a fresh section would duplicate it, so
 * it throws instead.
 */
function markers(mdx: string): { start: number; end: number } | null {
  const start = mdx.indexOf(START)
  const end = mdx.indexOf(END)
  if (start === -1 && end === -1) return null
  const problem =
    start === -1
      ? `${END} without ${START}`
      : end === -1
        ? `${START} without ${END}`
        : end < start
          ? `${END} before ${START}`
          : mdx.indexOf(START, start + 1) !== -1 || mdx.indexOf(END, end + 1) !== -1
            ? "more than one guidelines section"
            : null
  if (problem) throw new Error(`sync-guidelines: ${problem} — fix the markers by hand`)
  return { start, end }
}

/** Replaces the marked section, or inserts it before "## API Reference". */
export function insertSection(mdx: string, section: string): string {
  const found = markers(mdx)
  if (found) {
    return mdx.slice(0, found.start) + section + mdx.slice(found.end + END.length)
  }
  const at = mdx.indexOf(API_REFERENCE)
  if (at === -1) return `${mdx.trimEnd()}\n\n${section}\n`
  return `${mdx.slice(0, at).trimEnd()}\n\n${section}\n${mdx.slice(at)}`
}

export function removeSection(mdx: string): string {
  const found = markers(mdx)
  if (!found) return mdx
  return `${mdx.slice(0, found.start).trimEnd()}\n\n${mdx.slice(found.end + END.length).trimStart()}`
}

/**
 * The page content with its guidelines section up to date. Exported for
 * sync-upstream-docs.mts, which calls it on the page it just generated.
 * `moduleKey` is `components/<name>` or `tecton/<name>`.
 *
 * Throws while any guideline file (or adopted rules file) fails
 * guidelines:check: dropping the section of an invalid file would publish the
 * page without its guidelines and nothing would say so.
 */
export function withGuidelines(mdx: string, moduleKey: string): string {
  const { catalog, valid, invalid } = guidelines()
  if (invalid.size) {
    const files = [...invalid.keys()].map((file) => path.basename(file)).join(", ")
    throw new Error(`sync-guidelines: ${files} fail guidelines:check — fix them before syncing ${moduleKey}`)
  }
  const guideline = valid.get(moduleKey)
  if (!guideline) return removeSection(mdx)
  return insertSection(mdx, renderSection(guideline, catalog))
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

/** Every `<dir>/<name>.mdx` under content/docs that a module could own. */
function docsPages(): Map<string, string> {
  const pages = new Map<string, string>()
  for (const dir of MODULE_DIRS) {
    const full = path.join(DOCS, dir)
    if (!existsSync(full)) continue
    for (const entry of readdirSync(full)) {
      if (!entry.endsWith(".mdx") || entry === "index.mdx") continue
      pages.set(`${dir}/${entry.slice(0, -".mdx".length)}`, path.join(full, entry))
    }
  }
  return pages
}

function main() {
  const check = process.argv.includes("--check")
  const { catalog, valid, invalid } = guidelines()
  const pages = docsPages()
  const changed: string[] = []
  const missing: string[] = []

  // An invalid file is not "no guideline": rendering now would strip its
  // section from the page, so nothing is written until every file passes.
  if (invalid.size) {
    for (const [file, errors] of invalid) {
      console.error(`✗ ${path.basename(file)}: ${errors.length} problem(s) — run guidelines:check`)
    }
    console.error(`docs:guidelines failed — ${invalid.size} invalid file(s); no page was written.`)
    process.exit(1)
  }

  const broken: string[] = []
  const targets = new Set([...valid.keys(), ...pages.keys()])
  for (const moduleKey of [...targets].sort()) {
    const page = pages.get(moduleKey)
    const guideline = valid.get(moduleKey)
    if (!page) {
      if (guideline) missing.push(moduleKey)
      continue
    }
    const current = readFileSync(page, "utf8")
    const eol = current.includes("\r\n") ? "\r\n" : "\n"
    const lf = current.replace(/\r\n/g, "\n")
    if (!guideline && !lf.includes(START) && !lf.includes(END)) continue
    let next: string
    try {
      next = guideline ? insertSection(lf, renderSection(guideline, catalog)) : removeSection(lf)
    } catch (error) {
      broken.push(`content/docs/${moduleKey}.mdx: ${(error as Error).message}`)
      continue
    }
    if (next === lf) continue
    changed.push(`content/docs/${moduleKey}.mdx${guideline ? "" : " (section removed)"}`)
    if (!check) writeFileSync(page, next.split("\n").join(eol))
  }

  for (const moduleKey of missing) {
    console.error(`✗ ${moduleKey}: no page at content/docs/${moduleKey}.mdx to render into`)
  }
  for (const problem of broken) console.error(`✗ ${problem}`)

  const summary = `${valid.size} guideline file(s), ${pages.size} page(s)`
  if (missing.length || broken.length) {
    console.error(`docs:guidelines failed — ${missing.length} page(s) missing, ${broken.length} page(s) with broken markers.`)
    process.exit(1)
  }
  if (check) {
    if (changed.length) {
      console.error(`docs:guidelines --check failed — ${changed.length} page(s) stale:`)
      for (const item of changed) console.error(`  ${item}`)
      console.error("  run: pnpm --filter www docs:guidelines")
      process.exit(1)
    }
    console.log(`docs:guidelines: up to date (${summary})`)
    return
  }
  console.log(
    changed.length
      ? `docs:guidelines: updated ${changed.length} page(s) (${summary})`
      : `docs:guidelines: up to date (${summary})`
  )
}

const entry = process.argv[1] ? path.resolve(process.argv[1]) : ""
if (entry === fileURLToPath(import.meta.url)) main()
