// GENERATED by scripts/barrel-build.mts — do not edit
/**
 * The whole `@tecton/react` surface behind one import.
 *
 * Every component, hook, utility and icon is also reachable at its own
 * subpath (`@tecton/react/components/button`, `@tecton/react/icons`), which
 * is what the docs site and the shadcn CLI use. This barrel exists for
 * consumers that need a single module — a Module Federation host, where one
 * share entry per component is unmanageable:
 *
 *     import { Button, Panel, WellIcon, useIsMobile, cn } from "@tecton/react"
 *
 * Blocks stay at `@tecton/react/blocks/*`; see scripts/barrel-build.mts.
 */

// --------------------------------------------------------------------------
// shadcn components — generated by the CLI from the `aria-tecton` style
// --------------------------------------------------------------------------

export {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "./components/accordion"
export {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogOverlay,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "./components/alert-dialog"
export {
  Alert,
  AlertTitle,
  AlertDescription,
  AlertAction,
  alertVariants,
} from "./components/alert"
export { AspectRatio } from "./components/aspect-ratio"
export {
  Attachment,
  AttachmentGroup,
  AttachmentMedia,
  AttachmentContent,
  AttachmentTitle,
  AttachmentDescription,
  AttachmentActions,
  AttachmentAction,
  AttachmentTrigger,
} from "./components/attachment"
export {
  Avatar,
  AvatarImage,
  AvatarFallback,
  AvatarGroup,
  AvatarGroupCount,
  AvatarBadge,
} from "./components/avatar"
export { Badge, badgeVariants } from "./components/badge"
export {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbPage,
  BreadcrumbEllipsis,
} from "./components/breadcrumb"
export {
  BubbleGroup,
  Bubble,
  BubbleContent,
  BubbleReactions,
} from "./components/bubble"
export {
  ButtonGroup,
  ButtonGroupSeparator,
  ButtonGroupText,
  buttonGroupVariants,
} from "./components/button-group"
export { Button, LinkButton, buttonVariants } from "./components/button"
export { Calendar, RangeCalendar } from "./components/calendar"
export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardAction,
  CardDescription,
  CardContent,
} from "./components/card"
export {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
  useCarousel,
} from "./components/carousel"
export type { CarouselApi } from "./components/carousel"
export {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
  ChartLegendContent,
  ChartStyle,
} from "./components/chart"
export type { ChartConfig } from "./components/chart"
export { Checkbox } from "./components/checkbox"
export {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
} from "./components/collapsible"
export {
  Combobox,
  ComboboxInput,
  ComboboxContent,
  ComboboxList,
  ComboboxItem,
  ComboboxGroup,
  ComboboxLabel,
  ComboboxCollection,
  ComboboxEmpty,
  ComboboxSeparator,
  ComboboxChips,
  ComboboxChip,
  ComboboxChipList,
  ComboboxChipsInput,
  ComboboxTrigger,
  ComboboxValue,
  useComboboxAnchor,
} from "./components/combobox"
export {
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandShortcut,
  CommandSeparator,
} from "./components/command"
export {
  ContextMenu,
  ContextMenuTrigger,
  ContextMenuItem,
  ContextMenuLabel,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuGroup,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
} from "./components/context-menu"
export {
  Dialog,
  DialogClose,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogTitle,
  DialogTrigger,
} from "./components/dialog"
export type {
  DialogPrimitiveProps,
  DialogTriggerPrimitiveProps,
} from "./components/dialog"
export {
  DirectionProvider,
  I18nProvider,
  useDirection,
  useLocale,
} from "./components/direction"
export {
  Drawer,
  DrawerPortal,
  DrawerOverlay,
  DrawerSwipeHandle,
  DrawerTrigger,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription,
} from "./components/drawer"
export {
  DropdownMenuTrigger,
  DropdownMenu,
  DropdownMenuGroup,
  DropdownMenuLabel,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent,
} from "./components/dropdown-menu"
export {
  Empty,
  EmptyHeader,
  EmptyTitle,
  EmptyDescription,
  EmptyContent,
  EmptyMedia,
} from "./components/empty"
export {
  Field,
  FieldLabel,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldContent,
  FieldTitle,
} from "./components/field"
export { HoverCard, HoverCardTrigger } from "./components/hover-card"
export {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupText,
  InputGroupInput,
  InputGroupTextarea,
} from "./components/input-group"
export {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
  InputOTPSeparator,
} from "./components/input-otp"
export { Input, inputVariants } from "./components/input"
export {
  Item,
  ItemMedia,
  ItemContent,
  ItemActions,
  ItemGroup,
  ItemSeparator,
  ItemTitle,
  ItemDescription,
  ItemHeader,
  ItemFooter,
} from "./components/item"
export { Kbd, KbdGroup } from "./components/kbd"
export { Label } from "./components/label"
export {
  Marker,
  MarkerIcon,
  MarkerContent,
  markerVariants,
} from "./components/marker"
export {
  MessageScrollerProvider,
  MessageScroller,
  MessageScrollerViewport,
  MessageScrollerContent,
  MessageScrollerItem,
  MessageScrollerButton,
  useMessageScroller,
  useMessageScrollerScrollable,
  useMessageScrollerVisibility,
} from "./components/message-scroller"
export {
  MessageGroup,
  Message,
  MessageAvatar,
  MessageContent,
  MessageFooter,
  MessageHeader,
} from "./components/message"
export {
  NativeSelect,
  NativeSelectOptGroup,
  NativeSelectOption,
} from "./components/native-select"
export {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "./components/pagination"
export {
  Popover,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
} from "./components/popover"
export {
  Progress,
  ProgressTrack,
  ProgressIndicator,
  ProgressLabel,
  ProgressValue,
} from "./components/progress"
export {
  Questionnaire,
  QuestionnaireActions,
  QuestionnaireChoice,
  QuestionnaireChoiceDescription,
  QuestionnaireChoices,
  QuestionnaireDescription,
  QuestionnaireError,
  QuestionnaireInput,
  QuestionnaireItem,
  QuestionnaireNext,
  QuestionnairePrevious,
  QuestionnaireProgress,
  QuestionnaireSkip,
  QuestionnaireSubmit,
  QuestionnaireTitle,
} from "./components/questionnaire"
export { RadioGroup, RadioGroupItem } from "./components/radio-group"
export {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "./components/resizable"
export { ScrollArea } from "./components/scroll-area"
export {
  Select,
  SelectContent,
  SelectGroup,
  SelectInput,
  SelectItem,
  SelectLabel,
  SelectList,
  SelectPopover,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  SelectEmpty,
} from "./components/select"
export { Separator, separatorVariants } from "./components/separator"
export {
  Sheet,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
} from "./components/sheet"
export type {
  SheetPrimitiveProps,
  SheetTriggerPrimitiveProps,
} from "./components/sheet"
export {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupAction,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInput,
  SidebarInset,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSkeleton,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  SidebarProvider,
  SidebarRail,
  SidebarSeparator,
  SidebarTrigger,
  useSidebar,
} from "./components/sidebar"
export { Skeleton } from "./components/skeleton"
export { Slider } from "./components/slider"
export { Toaster } from "./components/sonner"
export { Spinner } from "./components/spinner"
export { Switch } from "./components/switch"
export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
} from "./components/table"
export {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  tabsListVariants,
} from "./components/tabs"
export { Textarea, textareaVariants } from "./components/textarea"
export { ToggleGroup, ToggleGroupItem } from "./components/toggle-group"
export { Toggle, toggleVariants } from "./components/toggle"
export { Tooltip, TooltipTrigger } from "./components/tooltip"

// --------------------------------------------------------------------------
// hooks
// --------------------------------------------------------------------------

export { useIsMobile } from "./hooks/use-mobile"

// --------------------------------------------------------------------------
// utilities
// --------------------------------------------------------------------------

export { cn } from "./lib/utils"

// --------------------------------------------------------------------------
// Tecton components
// --------------------------------------------------------------------------

export {
  ActionBar,
  ActionBarSelection,
  ActionBarMessage,
  ActionBarActions,
  actionBarVariants,
} from "./tecton/action-bar"
export type {
  ActionBarProps,
  ActionBarSelectionProps,
} from "./tecton/action-bar"
export {
  AppFinder,
  AppFinderTrigger,
  AppFinderMenu,
  AppFinderInput,
  AppFinderList,
  AppFinderGroup,
  AppFinderItem,
  AppFinderIcon,
  appFinderIconVariants,
} from "./tecton/app-finder"
export type {
  AppFinderGroupProps,
  AppFinderItemProps,
  AppFinderListProps,
  AppFinderMenuProps,
  AppFinderTone,
  AppFinderTriggerProps,
} from "./tecton/app-finder"
export {
  AppShell,
  AppShellHeader,
  AppShellBrand,
  AppShellNav,
  AppShellHeaderActions,
  AppShellBody,
  AppShellSidebar,
  AppShellMain,
  AppShellAside,
  AppShellSplit,
  AppShellSplitPanel,
  AppShellSplitHandle,
  useMinWidth,
} from "./tecton/app-shell"
export {
  Background,
  BackgroundEffect,
  SeismicBackground,
  ContourBackground,
  StrataBackground,
  GridBackground,
  FlowBackground,
  WellLogBackground,
  DrillBackground,
  HexagonsBackground,
  PressureBackground,
  HorizonBackground,
  TerrainGridBackground,
  backgroundEffects,
  backgroundVariants,
  backgroundTones,
  backgroundIntensities,
  backgroundSpeeds,
} from "./tecton/background"
export type { BackgroundProps, BackgroundEffectName } from "./tecton/background"
export {
  Canvas,
  CanvasSurface,
  CanvasOverlay,
  CanvasToolbar,
  CanvasLegend,
  CanvasLegendItem,
  canvasOverlayVariants,
  canvasToolbarVariants,
} from "./tecton/canvas"
export { Chip, ChipGroup, ChipList, ChipRemove } from "./tecton/chip"
export type { ChipVariantProps } from "./tecton/chip"
export {
  CircularProgress,
  circularProgressVariants,
} from "./tecton/circular-progress"
export type { CircularProgressProps } from "./tecton/circular-progress"
export {
  ColorSwatch,
  colorSwatchPresets,
  colorSwatchVariants,
} from "./tecton/color-swatch"
export type { ColorSwatchProps } from "./tecton/color-swatch"
export { CopyButton } from "./tecton/copy-button"
export type { CopyButtonProps } from "./tecton/copy-button"
export { CountBadge, countBadgeVariants } from "./tecton/count-badge"
export type { CountBadgeProps } from "./tecton/count-badge"
export { Link, linkVariants } from "./tecton/link"
export type { LinkProps } from "./tecton/link"
export { Meter, meterVariants } from "./tecton/meter"
export type { MeterProps, MeterColor } from "./tecton/meter"
export {
  Overflow,
  Toolbar,
  OverflowItem,
  OverflowLabel,
  OverflowGroup,
  OverflowDivider,
  OverflowSpacer,
  OverflowMenu,
  useIsOverflowItemVisible,
} from "./tecton/overflow"
export type {
  OverflowProps,
  ToolbarProps,
  OverflowItemProps,
  OverflowGroupProps,
  OverflowMenuProps,
} from "./tecton/overflow"
export {
  PageHeader,
  PageHeaderContent,
  PageHeaderEyebrow,
  PageHeaderTitle,
  PageHeaderDescription,
  PageHeaderNav,
  PageHeaderActions,
} from "./tecton/page-header"
export {
  Panel,
  PanelHeader,
  PanelTitle,
  PanelDescription,
  PanelActions,
  PanelContent,
  PanelFooter,
  panelVariants,
} from "./tecton/panel"
export {
  PortalProvider,
  usePortalContainer,
  usePortalTarget,
} from "./tecton/portal"
export type { PortalProviderProps } from "./tecton/portal"
export {
  ShellActions,
  ShellAction,
  ShellCommandTrigger,
  ShellDivider,
  ShellOverflow,
  ShellUserMenu,
} from "./tecton/shell-actions"
export type {
  ShellActionProps,
  ShellCommandTriggerProps,
  ShellOverflowProps,
  ShellUserMenuProps,
} from "./tecton/shell-actions"
export {
  createShortcutRegistry,
  ShortcutsProvider,
  useShortcutRegistry,
  useShortcuts,
  useShortcut,
  formatShortcut,
  ShortcutKeys,
} from "./tecton/shortcuts"
export type {
  Shortcut,
  ShortcutRegistry,
  ShortcutsProviderProps,
} from "./tecton/shortcuts"
export {
  Stat,
  StatLabel,
  StatValue,
  StatDelta,
  StatHelp,
  StatGroup,
  statVariants,
} from "./tecton/stat"
export {
  TreeView,
  TreeViewItem,
  TreeViewItemContent,
  TreeViewAction,
  TreeViewVisibilityToggle,
  TreeViewCollection,
} from "./tecton/tree-view"
export type {
  TreeViewItemProps,
  TreeViewItemContentProps,
} from "./tecton/tree-view"

// --------------------------------------------------------------------------
// icons — generated by icons:build from icons-src/tecton/
// --------------------------------------------------------------------------

export {
  AddCircleIcon,
  AddIcon,
  AddPinIcon,
  AnnotateIcon,
  AppsIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CancelCircleIcon,
  CaretCollapseIcon,
  CaretUpDownIcon,
  CheckCircleIcon,
  CheckCircleOpenIcon,
  CheckIcon,
  CheckboxIcon,
  CheckboxOutlineBlankIcon,
  ChevronDownIcon,
  ChevronDownSmallIcon,
  ChevronLeftIcon,
  ChevronLeftSmallIcon,
  ChevronRightIcon,
  ChevronRightSmallIcon,
  ChevronUpIcon,
  ChevronUpSmallIcon,
  ChristmasTreeIcon,
  CloseIcon,
  CloseSmallIcon,
  Co2LeafIcon,
  CodeIcon,
  CollapseContentIcon,
  ControlsIcon,
  CopyIcon,
  CrownIcon,
  CubeIcon,
  DatabaseIcon,
  DeleteIcon,
  DesignIcon,
  DiamondMarkIcon,
  DiscoveryIcon,
  DragIndicatorIcon,
  DrillBitIcon,
  EditSquareIcon,
  ElectricityIcon,
  EngineeringIcon,
  ErrorIcon,
  ExpandContentIcon,
  ExportUploadIcon,
  FacilityIcon,
  FaultIcon,
  FilterIcon,
  FolderIcon,
  FolderNewIcon,
  FolderOpenIcon,
  FrameworksIcon,
  GeobodiesIcon,
  GeostructureIcon,
  GridViewIcon,
  HistoryIcon,
  HomeIcon,
  HorizonIcon,
  ImageIcon,
  IndeterminateCheckboxIcon,
  InfoIcon,
  InspectIcon,
  KanbanIcon,
  LayersIcon,
  LineWeightIcon,
  LinkIcon,
  LinkOffIcon,
  ListIcon,
  LockIcon,
  LockOpenIcon,
  LogCurveIcon,
  MapIcon,
  MenuIcon,
  MicrophoneIcon,
  MoneyIcon,
  MoreVertIcon,
  NodeIcon,
  NotificationsIcon,
  NumericIcon,
  OilRigOffshoreIcon,
  OpenInNewIcon,
  PanToolIcon,
  PanelIcon,
  PersonIcon,
  PlayIcon,
  PreviewIcon,
  ProjectIcon,
  PulseIcon,
  RadioButtonIcon,
  RedoIcon,
  RemoveCircleIcon,
  RemoveIcon,
  ReportsAnalyticsIcon,
  RiskSkullIcon,
  Robot2Icon,
  RockFormationsIcon,
  RotateIcon,
  RulerIcon,
  SearchIcon,
  SeismicIcon,
  SelectCursorIcon,
  SelectIcon,
  SettingsIcon,
  SliceIcon,
  SortEnabledIcon,
  SplitscreenIcon,
  StrataIcon,
  SurfaceIcon,
  SwapIcon,
  TargetIcon,
  ThreeDIcon,
  TrajectoryIcon,
  TrendIcon,
  UndoIcon,
  ValveIcon,
  VelocityModelIcon,
  ViewColumnIcon,
  ViewModuleIcon,
  VisibilityIcon,
  VisibilityOffIcon,
  WarningIcon,
  WaterIcon,
  WellIcon,
  WellPickIcon,
  WellPlanIcon,
  WindowIcon,
  ZoomInIcon,
  ZoomOutIcon,
  tectonIcons,
  tectonIconsBySlug,
} from "./icons"
export type {
  TectonIconComponent,
  TectonIconEntry,
  TectonIconProps,
  TectonIconSource,
  TectonIconVariant,
} from "./icons"
