"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `account_tree` (U+E97A), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** AccountTreeIcon — hierarchy of nodes joined by connectors */
export const AccountTreeIcon = tectonIcon("account-tree")
