// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/add-pin.ts (outline)
//   filled: icons-src/tecton/add-pin.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** AddPinIcon — map pin with small plus at top right */
export function AddPinIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="add-pin"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M8.82501 7.49017C9.05278 7.26139 9.16667 6.98639 9.16667 6.66517C9.16667 6.34394 9.05228 6.06944 8.8235 5.84167C8.59473 5.61389 8.31973 5.5 7.99851 5.5C7.67728 5.5 7.40278 5.61439 7.17501 5.84317C6.94723 6.07195 6.83334 6.34695 6.83334 6.66817C6.83334 6.98939 6.94773 7.26389 7.17651 7.49167C7.40528 7.71944 7.68028 7.83333 8.00151 7.83333C8.32273 7.83333 8.59723 7.71895 8.82501 7.49017ZM8.00001 14.6667C6.21112 13.1444 4.87501 11.7306 3.99167 10.425C3.10834 9.11944 2.66667 7.91111 2.66667 6.8C2.66667 5.13333 3.20278 3.80556 4.27501 2.81667C5.34723 1.82778 6.58889 1.33333 8.00001 1.33333C8.24445 1.33333 8.48334 1.35 8.71667 1.38333C8.95001 1.41667 9.17778 1.45878 9.40001 1.50967V3.8H11.5333V5.93333H13.2703C13.2901 6.07778 13.3056 6.21944 13.3167 6.35833C13.3278 6.49722 13.3333 6.64444 13.3333 6.8C13.3333 7.91111 12.8917 9.11944 12.0083 10.425C11.125 11.7306 9.78889 13.1444 8.00001 14.6667ZM12.2 5.26667V3.13333H10.0667V2.13333H12.2V0H13.2V2.13333H15.3333V3.13333H13.2V5.26667H12.2Z">
          </path>
        </>
      ) : (
        <>
          <path d="M8.00001 14.6667C6.21112 13.1444 4.87501 11.7306 3.99167 10.425C3.10834 9.11944 2.66667 7.91111 2.66667 6.8C2.66667 5.13333 3.20278 3.80556 4.27501 2.81667C5.34723 1.82778 6.58889 1.33333 8.00001 1.33333C8.18889 1.33333 8.36945 1.34167 8.54167 1.35833C8.71389 1.375 8.88889 1.4 9.06667 1.43333V2.46667C8.90001 2.42222 8.72778 2.38889 8.55001 2.36667C8.37223 2.34444 8.18889 2.33333 8.00001 2.33333C6.78423 2.33333 5.75806 2.75056 4.92151 3.585C4.08495 4.41956 3.66667 5.49122 3.66667 6.8C3.66667 7.63333 4.02778 8.59722 4.75001 9.69167C5.47223 10.7861 6.55556 12.0056 8.00001 13.35C9.47778 12.0056 10.5694 10.7861 11.275 9.69167C11.9806 8.59722 12.3333 7.63333 12.3333 6.8C12.3333 6.71111 12.3306 6.62222 12.325 6.53333C12.3195 6.44444 12.3111 6.35556 12.3 6.26667H13.3167C13.3278 6.35556 13.3333 6.44444 13.3333 6.53333V6.8C13.3333 7.91111 12.8917 9.11944 12.0083 10.425C11.125 11.7306 9.78889 13.1444 8.00001 14.6667ZM8.82501 7.49017C9.05278 7.26139 9.16667 6.98639 9.16667 6.66517C9.16667 6.34394 9.05228 6.06944 8.8235 5.84167C8.59473 5.61389 8.31973 5.5 7.99851 5.5C7.67728 5.5 7.40278 5.61439 7.17501 5.84317C6.94723 6.07195 6.83334 6.34695 6.83334 6.66817C6.83334 6.98939 6.94773 7.26389 7.17651 7.49167C7.40528 7.71944 7.68028 7.83333 8.00151 7.83333C8.32273 7.83333 8.59723 7.71895 8.82501 7.49017ZM12.2 5.26667H13.2V3.13333H15.3333V2.13333H13.2V0H12.2V2.13333H10.0667V3.13333H12.2V5.26667Z">
          </path>
        </>
      )}
    </svg>
  )
}
AddPinIcon.displayName = "AddPinIcon"
