"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `add_circle` (U+E990), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** AddCircleIcon — circle with plus */
export const AddCircleIcon = tectonIcon("add-circle")
