"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `airwave` (U+F154), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** AirwaveIcon — three stacked wavy lines */
export const AirwaveIcon = tectonIcon("airwave")
