"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100004 outlined, U+100804 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** AnnotateIcon — diagonal marker pen */
export const AnnotateIcon = tectonIcon("annotate")
