"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `archive` (U+E149), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ArchiveIcon — box with a lid and a slot */
export const ArchiveIcon = tectonIcon("archive")
