// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ArrowLeft` (manifest: lucide: "arrow-left").
// Drop icons-src/outlined/arrow-left.svg in place and re-run `pnpm icons:build`.
import { ArrowLeft as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ArrowLeftIcon — arrow pointing left */
export function ArrowLeftIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="arrow-left"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ArrowLeftIcon.displayName = "ArrowLeftIcon"
