"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `arrow_outward` (U+F8CE), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ArrowOutwardIcon — arrow pointing up and to the right */
export const ArrowOutwardIcon = tectonIcon("arrow-outward")
