"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `arrow_back` (U+E5C4), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ArrowLeftIcon — arrow pointing left */
export const ArrowLeftIcon = tectonIcon("arrow-left")
