// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ArrowRight` (manifest: lucide: "arrow-right").
// Drop icons-src/outlined/arrow-right.svg in place and re-run `pnpm icons:build`.
import { ArrowRight as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ArrowRightIcon — arrow pointing right */
export function ArrowRightIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="arrow-right"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ArrowRightIcon.displayName = "ArrowRightIcon"
