// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ArrowUp` (manifest: lucide: "arrow-up").
// Drop icons-src/outlined/arrow-up.svg in place and re-run `pnpm icons:build`.
import { ArrowUp as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ArrowUpIcon — arrow pointing up */
export function ArrowUpIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="arrow-up"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ArrowUpIcon.displayName = "ArrowUpIcon"
