"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `arrow_downward` (U+E5DB), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ArrowDownIcon — arrow pointing down */
export const ArrowDownIcon = tectonIcon("arrow-down")
