"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `auto_awesome` (U+E65F), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** AutoAwesomeIcon — large four-point star with two small ones */
export const AutoAwesomeIcon = tectonIcon("auto-awesome")
