"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `bluetooth` (U+E1A7), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** BluetoothIcon — bluetooth rune */
export const BluetoothIcon = tectonIcon("bluetooth")
