"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `bookmark` (U+E8E7), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** BookmarkIcon — ribbon bookmark */
export const BookmarkIcon = tectonIcon("bookmark")
