"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `calculate` (U+EA5F), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CalculateIcon — calculator keypad with operators */
export const CalculateIcon = tectonIcon("calculate")
