"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `unfold_more` (U+E5D7), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CaretUpDownIcon — two chevrons pointing away from each other vertically (up over down) */
export const CaretUpDownIcon = tectonIcon("caret-up-down")
