// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ChevronsUpDown` (manifest: lucide: "chevrons-up-down").
// Drop icons-src/outlined/caret-up-down.svg in place and re-run `pnpm icons:build`.
import { ChevronsUpDown as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** CaretUpDownIcon — two chevrons pointing away from each other vertically (up over down) */
export function CaretUpDownIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="caret-up-down"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
CaretUpDownIcon.displayName = "CaretUpDownIcon"
