"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `chat` (U+E0C9), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ChatIcon — rounded speech bubble with lines */
export const ChatIcon = tectonIcon("chat")
