"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `check_circle` (U+F0BE), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CheckCircleIcon — circle with check mark */
export const CheckCircleIcon = tectonIcon("check-circle")
