"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `check_box` (U+E9DE), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CheckboxIcon — square with check mark */
export const CheckboxIcon = tectonIcon("checkbox")
