// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `CircleCheck` (manifest: lucide: "circle-check").
// Drop icons-src/outlined/check-circle.svg in place and re-run `pnpm icons:build`.
import { CircleCheck as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** CheckCircleIcon — circle with check mark */
export function CheckCircleIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="check-circle"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
CheckCircleIcon.displayName = "CheckCircleIcon"
