// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/check-circle.ts (outline)
//   filled: icons-src/tecton/check-circle.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** CheckCircleIcon — circle with check mark */
export function CheckCircleIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="check-circle"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M7.01669 11.0333L11.7334 6.31659L10.9667 5.56659L7.01669 9.51658L5.01669 7.51658L4.26669 8.26658L7.01669 11.0333ZM8.00002 14.6666C7.08891 14.6666 6.2278 14.4916 5.41669 14.1416C4.60558 13.7916 3.89725 13.3138 3.29169 12.7083C2.68614 12.1027 2.20836 11.3944 1.85836 10.5833C1.50836 9.77214 1.33336 8.91103 1.33336 7.99992C1.33336 7.0777 1.50836 6.21103 1.85836 5.39992C2.20836 4.58881 2.68614 3.88325 3.29169 3.28325C3.89725 2.68325 4.60558 2.20825 5.41669 1.85825C6.2278 1.50825 7.08891 1.33325 8.00002 1.33325C8.92225 1.33325 9.78891 1.50825 10.6 1.85825C11.4111 2.20825 12.1167 2.68325 12.7167 3.28325C13.3167 3.88325 13.7917 4.58881 14.1417 5.39992C14.4917 6.21103 14.6667 7.0777 14.6667 7.99992C14.6667 8.91103 14.4917 9.77214 14.1417 10.5833C13.7917 11.3944 13.3167 12.1027 12.7167 12.7083C12.1167 13.3138 11.4111 13.7916 10.6 14.1416C9.78891 14.4916 8.92225 14.6666 8.00002 14.6666Z">
          </path>
        </>
      ) : (
        <>
          <path d="M7.01665 11.0333L11.7333 6.31659L10.9666 5.56659L7.01665 9.51658L5.01665 7.51658L4.26665 8.26658L7.01665 11.0333ZM7.99998 14.6666C7.08887 14.6666 6.22776 14.4916 5.41665 14.1416C4.60554 13.7916 3.8972 13.3138 3.29165 12.7083C2.68609 12.1027 2.20831 11.3944 1.85831 10.5833C1.50831 9.77214 1.33331 8.91103 1.33331 7.99992C1.33331 7.0777 1.50831 6.21103 1.85831 5.39992C2.20831 4.58881 2.68609 3.88325 3.29165 3.28325C3.8972 2.68325 4.60554 2.20825 5.41665 1.85825C6.22776 1.50825 7.08887 1.33325 7.99998 1.33325C8.9222 1.33325 9.78887 1.50825 10.6 1.85825C11.4111 2.20825 12.1166 2.68325 12.7166 3.28325C13.3166 3.88325 13.7916 4.58881 14.1416 5.39992C14.4916 6.21103 14.6666 7.0777 14.6666 7.99992C14.6666 8.91103 14.4916 9.77214 14.1416 10.5833C13.7916 11.3944 13.3166 12.1027 12.7166 12.7083C12.1166 13.3138 11.4111 13.7916 10.6 14.1416C9.78887 14.4916 8.9222 14.6666 7.99998 14.6666ZM7.99998 13.6666C9.57776 13.6666 10.9166 13.1138 12.0166 12.0083C13.1166 10.9027 13.6666 9.56658 13.6666 7.99992C13.6666 6.42214 13.1166 5.08325 12.0166 3.98325C10.9166 2.88325 9.57776 2.33325 7.99998 2.33325C6.43331 2.33325 5.0972 2.88325 3.99165 3.98325C2.88609 5.08325 2.33331 6.42214 2.33331 7.99992C2.33331 9.56658 2.88609 10.9027 3.99165 12.0083C5.0972 13.1138 6.43331 13.6666 7.99998 13.6666Z">
          </path>
        </>
      )}
    </svg>
  )
}
CheckCircleIcon.displayName = "CheckCircleIcon"
