"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+10000E outlined, U+10080E filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CheckCircleOpenIcon — dashed circle with check mark */
export const CheckCircleOpenIcon = tectonIcon("check-circle-open")
