// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `CircleDashed` (manifest: lucide: "circle-dashed").
// Drop icons-src/outlined/check-circle-open.svg in place and re-run `pnpm icons:build`.
import { CircleDashed as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** CheckCircleOpenIcon — dashed circle with check mark */
export function CheckCircleOpenIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="check-circle-open"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
CheckCircleOpenIcon.displayName = "CheckCircleOpenIcon"
