// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Check` (manifest: lucide: "check").
// Drop icons-src/outlined/check.svg in place and re-run `pnpm icons:build`.
import { Check as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** CheckIcon — check mark */
export function CheckIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="check"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
CheckIcon.displayName = "CheckIcon"
