// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/check-circle-open.ts (outline)
//   filled: icons-src/tecton/check-circle-open.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** CheckCircleOpenIcon — dashed circle with check mark */
export function CheckCircleOpenIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="check-circle-open"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M9.20638 14.0625L9.30305 14.5527C8.88132 14.6361 8.44566 14.6797 8.00032 14.6797C7.55498 14.6797 7.11932 14.6361 6.69759 14.5527L6.79427 14.0625L6.89095 13.5713C7.24922 13.6422 7.62036 13.6797 8.00032 13.6797C8.38028 13.6797 8.75142 13.6422 9.1097 13.5713L9.20638 14.0625ZM3.27669 11.1553C3.69149 11.7749 4.22545 12.3088 4.84505 12.7236L4.56673 13.1387L4.28841 13.5547C3.56019 13.0672 2.93316 12.4401 2.44563 11.7119L2.86165 11.4336L3.27669 11.1553ZM13.139 11.4336L13.555 11.7119C13.0675 12.4401 12.4404 13.0672 11.7122 13.5547L11.4339 13.1387L11.1556 12.7236C11.7752 12.3088 12.3091 11.7749 12.724 11.1553L13.139 11.4336ZM11.7337 6.31641L7.01692 11.0332L4.26692 8.2666L5.01692 7.5166L7.01692 9.5166L10.9671 5.56641L11.7337 6.31641ZM1.93782 6.79395L2.42903 6.89062C2.35815 7.2489 2.32063 7.62004 2.32063 8C2.32063 8.37996 2.35815 8.7511 2.42903 9.10938L1.93782 9.20605L1.44759 9.30273C1.36418 8.881 1.32063 8.44534 1.32063 8C1.32063 7.55466 1.36418 7.119 1.44759 6.69727L1.93782 6.79395ZM14.5531 6.69727C14.6365 7.119 14.68 7.55466 14.68 8C14.68 8.44534 14.6365 8.881 14.5531 9.30273L14.0628 9.20605L13.5716 9.10938C13.6425 8.7511 13.68 8.37996 13.68 8C13.68 7.62004 13.6425 7.2489 13.5716 6.89062L14.0628 6.79395L14.5531 6.69727ZM4.56673 2.86133L4.84505 3.27637C4.22545 3.69117 3.69149 4.22513 3.27669 4.84473L2.86165 4.56641L2.44563 4.28809C2.93316 3.55987 3.56019 2.93284 4.28841 2.44531L4.56673 2.86133ZM11.7122 2.44531C12.4404 2.93284 13.0675 3.55987 13.555 4.28809L13.139 4.56641L12.724 4.84473C12.3091 4.22513 11.7752 3.69117 11.1556 3.27637L11.4339 2.86133L11.7122 2.44531ZM8.00032 1.32031C8.44566 1.32031 8.88132 1.36386 9.30305 1.44727L9.20638 1.9375L9.1097 2.42871C8.75142 2.35783 8.38028 2.32031 8.00032 2.32031C7.62036 2.32031 7.24922 2.35783 6.89095 2.42871L6.79427 1.9375L6.69759 1.44727C7.11932 1.36386 7.55498 1.32031 8.00032 1.32031Z">
      </path>
    </svg>
  )
}
CheckCircleOpenIcon.displayName = "CheckCircleOpenIcon"
