"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `chevron_left` (U+E5CB), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ChevronLeftIcon — chevron pointing left */
export const ChevronLeftIcon = tectonIcon("chevron-left")
