// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ChevronDown` (manifest: lucide: "chevron-down").
// Drop icons-src/outlined/chevron-down.svg in place and re-run `pnpm icons:build`.
import { ChevronDown as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ChevronDownIcon — chevron pointing down */
export function ChevronDownIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="chevron-down"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ChevronDownIcon.displayName = "ChevronDownIcon"
