// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ChevronLeft` (manifest: lucide: "chevron-left").
// Drop icons-src/outlined/chevron-left.svg in place and re-run `pnpm icons:build`.
import { ChevronLeft as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ChevronLeftIcon — chevron pointing left */
export function ChevronLeftIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="chevron-left"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ChevronLeftIcon.displayName = "ChevronLeftIcon"
