// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ChevronRight` (manifest: lucide: "chevron-right").
// Drop icons-src/outlined/chevron-right-small.svg in place and re-run `pnpm icons:build`.
import { ChevronRight as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ChevronRightSmallIcon — small chevron pointing right */
export function ChevronRightSmallIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="chevron-right-small"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ChevronRightSmallIcon.displayName = "ChevronRightSmallIcon"
