// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ChevronDown` (manifest: lucide: "chevron-down").
// Drop icons-src/outlined/chevron-down-small.svg in place and re-run `pnpm icons:build`.
import { ChevronDown as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ChevronDownSmallIcon — small chevron pointing down */
export function ChevronDownSmallIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="chevron-down-small"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ChevronDownSmallIcon.displayName = "ChevronDownSmallIcon"
