"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `keyboard_arrow_down` (U+E313), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ChevronDownIcon — chevron pointing down */
export const ChevronDownIcon = tectonIcon("chevron-down")
