"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100013 outlined, U+100813 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ChevronDownSmallIcon — small chevron pointing down */
export const ChevronDownSmallIcon = tectonIcon("chevron-down-small")
