// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `X` (manifest: lucide: "x").
// Drop icons-src/outlined/close-small.svg in place and re-run `pnpm icons:build`.
import { X as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** CloseSmallIcon — small x cross */
export function CloseSmallIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="close-small"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
CloseSmallIcon.displayName = "CloseSmallIcon"
