"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `cloud_off` (U+E2C1), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CloudOffIcon — cloud with a diagonal strike */
export const CloudOffIcon = tectonIcon("cloud-off")
