"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `cloud` (U+F15C), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CloudIcon — cloud outline */
export const CloudIcon = tectonIcon("cloud")
