// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Sprout` (manifest: lucide: "sprout").
// Drop icons-src/outlined/co2-leaf.svg in place and re-run `pnpm icons:build`.
import { Sprout as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** Co2LeafIcon — sprout with two leaves */
export function Co2LeafIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="co2-leaf"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
Co2LeafIcon.displayName = "Co2LeafIcon"
