"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `code_blocks` (U+F84D), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CodeBlocksIcon — rounded frame containing angle brackets */
export const CodeBlocksIcon = tectonIcon("code-blocks")
