"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `collapse_content` (U+F507), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CollapseContentIcon — two corner brackets with short arrows pointing inward */
export const CollapseContentIcon = tectonIcon("collapse-content")
