// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/collapse-content.ts (outline)
//   filled: icons-src/tecton/collapse-content.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** CollapseContentIcon — two corner brackets with short arrows pointing inward */
export function CollapseContentIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="collapse-content"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M7.33333 8.66683V12.6668H6.33333V9.66683H3.33333V8.66683H7.33333ZM9.66666 3.3335V6.3335H12.6667V7.3335H8.66666V3.3335H9.66666Z">
      </path>
    </svg>
  )
}
CollapseContentIcon.displayName = "CollapseContentIcon"
