"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `content_paste` (U+E14F), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ContentPasteIcon — clipboard with a page */
export const ContentPasteIcon = tectonIcon("content-paste")
