// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/copy.ts (outline)
//   filled: icons-src/tecton/copy.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** CopyIcon — two overlapping rounded squares */
export function CopyIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="copy"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M5 3.33333C5 2.59695 5.59695 2 6.33333 2H12.3333C13.0697 2 13.6667 2.59695 13.6667 3.33333V9.33333C13.6667 10.0697 13.0697 10.6667 12.3333 10.6667H10.6667V9.66667H12.3333C12.5174 9.66667 12.6667 9.51743 12.6667 9.33333V3.33333C12.6667 3.14924 12.5174 3 12.3333 3H6.33333C6.14924 3 6 3.14924 6 3.33333V5H5V3.33333Z">
      </path>
      <path d="M3.66667 5.33333C2.93029 5.33333 2.33333 5.93029 2.33333 6.66667V12.6667C2.33333 13.403 2.93029 14 3.66667 14H9.66667C10.403 14 11 13.403 11 12.6667V6.66667C11 5.93029 10.403 5.33333 9.66667 5.33333H3.66667ZM3.33333 6.66667C3.33333 6.48257 3.48257 6.33333 3.66667 6.33333H9.66667C9.85076 6.33333 10 6.48257 10 6.66667V12.6667C10 12.8508 9.85076 13 9.66667 13H3.66667C3.48257 13 3.33333 12.8508 3.33333 12.6667V6.66667Z">
      </path>
    </svg>
  )
}
CopyIcon.displayName = "CopyIcon"
