"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100021 outlined, U+100821 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CopyIcon — two overlapping rounded squares */
export const CopyIcon = tectonIcon("copy")
