// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Copy` (manifest: lucide: "copy").
// Drop icons-src/outlined/copy.svg in place and re-run `pnpm icons:build`.
import { Copy as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** CopyIcon — two overlapping rounded squares */
export function CopyIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="copy"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
CopyIcon.displayName = "CopyIcon"
