"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `corporate_fare` (U+F1D0), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CorporateFareIcon — two buildings side by side */
export const CorporateFareIcon = tectonIcon("corporate-fare")
