"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `crop_free` (U+E3C2), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CropFreeIcon — four corner brackets */
export const CropFreeIcon = tectonIcon("crop-free")
