// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/cube.ts (outline)
//   filled: icons-src/tecton/cube.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** CubeIcon — isometric cube outline */
export function CubeIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="cube"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M8 14.775L2.075 11.3697V4.62501L8 1.21667L13.925 4.62501V11.3747L8 14.775ZM7.525 8.27501V13.4L8 13.675L8.48333 13.4V8.27484L12.9667 5.66668V5.19184L12.425 4.88334L8 7.46668L3.56666 4.88334L3.03333 5.18184V5.68334L7.525 8.27501Z">
          </path>
        </>
      ) : (
        <>
          <path d="M7.525 13.4V8.27501L3.03333 5.68334V10.8083L7.525 13.4ZM8.48333 13.4L12.9667 10.8083V5.66668L8.48333 8.27501V13.4ZM8 7.46668L12.425 4.88334L8 2.32501L3.56666 4.88334L8 7.46668ZM2.075 11.3667V4.62501L8 1.21667L13.925 4.62501V11.375L8 14.775L2.075 11.3667Z">
          </path>
        </>
      )}
    </svg>
  )
}
CubeIcon.displayName = "CubeIcon"
