"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `deployed_code` (U+F720), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** CubeIcon — isometric cube outline */
export const CubeIcon = tectonIcon("cube")
