"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `data_object` (U+EAD3), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** DataObjectIcon — pair of curly braces */
export const DataObjectIcon = tectonIcon("data-object")
