// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/delete.ts (outline)
//   filled: icons-src/tecton/delete.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** DeleteIcon — trash can */
export function DeleteIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="delete"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M4.37084 13.9168C4.11561 13.9168 3.89211 13.8209 3.70034 13.629C3.50845 13.4372 3.4125 13.2137 3.4125 12.9585V3.52516H2.7375V2.56966H5.8125V2.0835H10.1875V2.56683H13.2625V3.52516H12.5875V12.9585C12.5875 13.2137 12.4916 13.4372 12.2997 13.629C12.1079 13.8209 11.8844 13.9168 11.6292 13.9168H4.37084ZM6.15417 11.5335H7.1125V4.92516H6.15417V11.5335ZM8.8875 11.5335H9.84584V4.92516H8.8875V11.5335Z">
          </path>
        </>
      ) : (
        <>
          <path d="M4.37081 13.9168C4.10725 13.9168 3.88164 13.823 3.69397 13.6353C3.50631 13.4477 3.41247 13.2221 3.41247 12.9585V3.52516H2.73747V2.56966H5.81247V2.0835H10.1875V2.56683H13.2625V3.52516H12.5875V12.9585C12.5875 13.2137 12.4915 13.4372 12.2996 13.629C12.1079 13.8209 11.8844 13.9168 11.6291 13.9168H4.37081ZM11.6291 3.52516H4.37081V12.9585H11.6291V3.52516ZM6.15414 11.5335H7.11247V4.92516H6.15414V11.5335ZM8.88747 11.5335H9.84581V4.92516H8.88747V11.5335Z">
          </path>
        </>
      )}
    </svg>
  )
}
DeleteIcon.displayName = "DeleteIcon"
