// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/diamond-mark.ts (outline)
//   filled: icons-src/tecton/diamond-mark.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** DiamondMarkIcon — diamond (rotated square) outline */
export function DiamondMarkIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="diamond-mark"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M8.00002 15.0668L0.93335 8.00014L8.00002 0.933472L15.0667 8.00014L8.00002 15.0668Z">
          </path>
        </>
      ) : (
        <>
          <path d="M8.00002 15.0668L0.93335 8.00014L8.00002 0.933472L15.0667 8.00014L8.00002 15.0668ZM8.00002 13.6918L13.6917 8.00014L8.00002 2.30847L2.30835 8.00014L8.00002 13.6918Z">
          </path>
        </>
      )}
    </svg>
  )
}
DiamondMarkIcon.displayName = "DiamondMarkIcon"
