// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Compass` (manifest: lucide: "compass").
// Drop icons-src/outlined/discovery.svg in place and re-run `pnpm icons:build`.
import { Compass as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** DiscoveryIcon — compass with needle */
export function DiscoveryIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="discovery"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
DiscoveryIcon.displayName = "DiscoveryIcon"
