"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `download` (U+F090), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** DownloadIcon — arrow down onto a line */
export const DownloadIcon = tectonIcon("download")
