// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `GripVertical` (manifest: lucide: "grip-vertical").
// Drop icons-src/outlined/drag-indicator.svg in place and re-run `pnpm icons:build`.
import { GripVertical as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** DragIndicatorIcon — 2x3 grid of dots */
export function DragIndicatorIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="drag-indicator"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
DragIndicatorIcon.displayName = "DragIndicatorIcon"
