"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `drag_indicator` (U+E945), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** DragIndicatorIcon — 2x3 grid of dots */
export const DragIndicatorIcon = tectonIcon("drag-indicator")
