"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `eco` (U+EA35), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** EcoIcon — single leaf */
export const EcoIcon = tectonIcon("eco")
