"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `edit_square` (U+F88D), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** EditSquareIcon — square with pencil over top right corner */
export const EditSquareIcon = tectonIcon("edit-square")
