// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/edit-square.ts (outline)
//   filled: icons-src/tecton/edit-square.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** EditSquareIcon — square with pencil over top right corner */
export function EditSquareIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="edit-square"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M6.025 9.97505V7.17505L13.0667 0.125046L15.8417 2.93338L8.825 9.97505H6.025ZM13.3417 4.10838L14.5 2.91671L13.0667 1.47505L11.8917 2.65838L13.3417 4.10838ZM2.075 13.925V2.07505H9.75833L5.06666 6.76671V10.9334H9.175L13.925 6.18338V13.925H2.075Z">
          </path>
        </>
      ) : (
        <>
          <path d="M2.075 13.925V2.07505H9.75833L8.8 3.03338H3.03333V12.9667H12.9667V7.14171L13.925 6.18338V13.925H2.075ZM6.025 9.97505V7.17505L13.0667 0.125046L15.8417 2.93338L8.825 9.97505H6.025ZM6.98333 9.01671H8.43333L12.6667 4.77505L11.2083 3.35005L6.98333 7.55005V9.01671Z">
          </path>
        </>
      )}
    </svg>
  )
}
EditSquareIcon.displayName = "EditSquareIcon"
