// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Zap` (manifest: lucide: "zap").
// Drop icons-src/outlined/electricity.svg in place and re-run `pnpm icons:build`.
import { Zap as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ElectricityIcon — lightning bolt */
export function ElectricityIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="electricity"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ElectricityIcon.displayName = "ElectricityIcon"
