// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/engineering.ts (outline)
//   filled: icons-src/tecton/engineering.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** EngineeringIcon — drafting compass / divider */
export function EngineeringIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="engineering"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M4.525 13.9167L4.38333 12.8667L6.475 7.09175C6.59722 7.20842 6.72916 7.30425 6.87083 7.37925C7.0125 7.45425 7.16389 7.51953 7.325 7.57508L5.29166 13.1667L4.525 13.9167ZM11.4833 13.9167L10.7167 13.1667L8.65 7.59175C8.81111 7.53619 8.96528 7.47091 9.1125 7.39592C9.25972 7.32092 9.39444 7.22508 9.51666 7.10842L11.625 12.8667L11.4833 13.9167ZM6.61666 6.74175C6.23333 6.35842 6.04166 5.89453 6.04166 5.35008C6.04166 4.88897 6.17639 4.47925 6.44583 4.12091C6.71528 3.76258 7.075 3.53619 7.525 3.44175V2.04175H8.48333V3.44175C8.93333 3.53619 9.29444 3.76258 9.56666 4.12091C9.83889 4.47925 9.975 4.88897 9.975 5.35008C9.975 5.89453 9.78333 6.35842 9.4 6.74175C9.01666 7.12508 8.55278 7.31675 8.00833 7.31675C7.46389 7.31675 7 7.12508 6.61666 6.74175ZM8.725 6.06675C8.91944 5.8723 9.01666 5.63341 9.01666 5.35008C9.01666 5.06675 8.91944 4.82786 8.725 4.63341C8.53055 4.43897 8.29166 4.34175 8.00833 4.34175C7.725 4.34175 7.48611 4.43897 7.29166 4.63341C7.09722 4.82786 7 5.06675 7 5.35008C7 5.63341 7.09722 5.8723 7.29166 6.06675C7.48611 6.26119 7.725 6.35842 8.00833 6.35842C8.29166 6.35842 8.53055 6.26119 8.725 6.06675Z">
      </path>
    </svg>
  )
}
EngineeringIcon.displayName = "EngineeringIcon"
