"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `architecture` (U+EA3B), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** EngineeringIcon — drafting compass / divider */
export const EngineeringIcon = tectonIcon("engineering")
