// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `DraftingCompass` (manifest: lucide: "drafting-compass").
// Drop icons-src/outlined/engineering.svg in place and re-run `pnpm icons:build`.
import { DraftingCompass as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** EngineeringIcon — drafting compass / divider */
export function EngineeringIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="engineering"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
EngineeringIcon.displayName = "EngineeringIcon"
