"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100030 outlined, U+100830 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ExportUploadIcon — arrow up out of a tray */
export const ExportUploadIcon = tectonIcon("export-upload")
