// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Factory` (manifest: lucide: "factory").
// Drop icons-src/outlined/facility.svg in place and re-run `pnpm icons:build`.
import { Factory as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** FacilityIcon — factory / plant building with sawtooth roof and stack */
export function FacilityIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="facility"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
FacilityIcon.displayName = "FacilityIcon"
