"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100033 outlined, U+100833 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** FilterIcon — funnel */
export const FilterIcon = tectonIcon("filter")
