"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `filter_list` (U+E152), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** FilterListIcon — three lines of decreasing length */
export const FilterListIcon = tectonIcon("filter-list")
