"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `folder_match` (U+F3D4), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** FolderMatchIcon — folder with a magnifier and a document */
export const FolderMatchIcon = tectonIcon("folder-match")
