// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Folder` (manifest: lucide: "folder").
// Drop icons-src/outlined/folder.svg in place and re-run `pnpm icons:build`.
import { Folder as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** FolderIcon — folder outline */
export function FolderIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="folder"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
FolderIcon.displayName = "FolderIcon"
