"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `fork_right` (U+EBAC), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ForkRightIcon — path splitting to the right */
export const ForkRightIcon = tectonIcon("fork-right")
