"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `format_italic` (U+E23F), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** FormatItalicIcon — slanted letter I */
export const FormatItalicIcon = tectonIcon("format-italic")
