"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `format_bold` (U+E238), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** FormatBoldIcon — bold letter B */
export const FormatBoldIcon = tectonIcon("format-bold")
