// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Waves` (manifest: lucide: "waves").
// Drop icons-src/outlined/frameworks.svg in place and re-run `pnpm icons:build`.
import { Waves as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** FrameworksIcon — three stacked wavy lines */
export function FrameworksIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="frameworks"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
FrameworksIcon.displayName = "FrameworksIcon"
