"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100037 outlined, U+100837 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** FrameworksIcon — three stacked wavy lines */
export const FrameworksIcon = tectonIcon("frameworks")
