"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100039 outlined, U+100839 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** GeostructureIcon — irregular hexagon-like blob outline (geologic structure) */
export const GeostructureIcon = tectonIcon("geostructure")
