"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `graphic_eq` (U+E1B8), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** GraphicEqIcon — five vertical bars of varying height */
export const GraphicEqIcon = tectonIcon("graphic-eq")
