// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `LayoutGrid` (manifest: lucide: "layout-grid").
// Drop icons-src/outlined/grid-view.svg in place and re-run `pnpm icons:build`.
import { LayoutGrid as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** GridViewIcon — 2x2 grid of squares */
export function GridViewIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="grid-view"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
GridViewIcon.displayName = "GridViewIcon"
