"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `grid_view` (U+E9B0), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** GridViewIcon — 2x2 grid of squares */
export const GridViewIcon = tectonIcon("grid-view")
