"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `history` (U+E8B3), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** HistoryIcon — clock with counter-clockwise arrow */
export const HistoryIcon = tectonIcon("history")
