// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `House` (manifest: lucide: "house").
// Drop icons-src/outlined/home.svg in place and re-run `pnpm icons:build`.
import { House as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** HomeIcon — house outline */
export function HomeIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="home"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
HomeIcon.displayName = "HomeIcon"
