// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `SquareMinus` (manifest: lucide: "square-minus").
// Drop icons-src/outlined/indeterminate-checkbox.svg in place and re-run `pnpm icons:build`.
import { SquareMinus as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** IndeterminateCheckboxIcon — square with minus */
export function IndeterminateCheckboxIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="indeterminate-checkbox"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
IndeterminateCheckboxIcon.displayName = "IndeterminateCheckboxIcon"
