// GENERATED by scripts/build-icons.mts — do not edit
import type { TectonIconEntry } from "./types"
import { ChristmasTreeIcon } from "./christmas-tree"
import { DrillBitIcon } from "./drill-bit"
import { FaultIcon } from "./fault"
import { GeobodiesIcon } from "./geobodies"
import { GeostructureIcon } from "./geostructure"
import { HorizonIcon } from "./horizon"
import { LogCurveIcon } from "./log-curve"
import { OilRigOffshoreIcon } from "./oil-rig-offshore"
import { RockFormationsIcon } from "./rock-formations"
import { SeismicIcon } from "./seismic"
import { StrataIcon } from "./strata"
import { SurfaceIcon } from "./surface"
import { TrajectoryIcon } from "./trajectory"
import { ValveIcon } from "./valve"
import { VelocityModelIcon } from "./velocity-model"
import { WellIcon } from "./well"
import { WellPickIcon } from "./well-pick"
import { WellPlanIcon } from "./well-plan"

export type { TectonIconComponent, TectonIconEntry, TectonIconProps, TectonIconSource, TectonIconVariant } from "./types"

export { ChristmasTreeIcon } from "./christmas-tree"
export { DrillBitIcon } from "./drill-bit"
export { FaultIcon } from "./fault"
export { GeobodiesIcon } from "./geobodies"
export { GeostructureIcon } from "./geostructure"
export { HorizonIcon } from "./horizon"
export { LogCurveIcon } from "./log-curve"
export { OilRigOffshoreIcon } from "./oil-rig-offshore"
export { RockFormationsIcon } from "./rock-formations"
export { SeismicIcon } from "./seismic"
export { StrataIcon } from "./strata"
export { SurfaceIcon } from "./surface"
export { TrajectoryIcon } from "./trajectory"
export { ValveIcon } from "./valve"
export { VelocityModelIcon } from "./velocity-model"
export { WellIcon } from "./well"
export { WellPickIcon } from "./well-pick"
export { WellPlanIcon } from "./well-plan"

/** Every Tecton icon, in manifest (alphabetical) order — drives the docs gallery. */
export const tectonIcons: readonly TectonIconEntry[] = [
  { name: "ChristmasTree", label: "ChristmasTreeIcon", slug: "christmas-tree", description: "wellhead 'christmas tree' valve stack: vertical pipe with stacked crossbars", Icon: ChristmasTreeIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "DrillBit", label: "DrillBitIcon", slug: "drill-bit", description: "drill bit: tapered bit head with shank", Icon: DrillBitIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Fault", label: "FaultIcon", slug: "fault", description: "diagonal line with offset crossing segment (geologic fault)", Icon: FaultIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Geobodies", label: "GeobodiesIcon", slug: "geobodies", description: "cluster of three hexagons", Icon: GeobodiesIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Geostructure", label: "GeostructureIcon", slug: "geostructure", description: "irregular hexagon-like blob outline (geologic structure)", Icon: GeostructureIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Horizon", label: "HorizonIcon", slug: "horizon", description: "single wave line (seismic horizon)", Icon: HorizonIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "LogCurve", label: "LogCurveIcon", slug: "log-curve", description: "vertical zig-zag curve (well log trace)", Icon: LogCurveIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "OilRigOffshore", label: "OilRigOffshoreIcon", slug: "oil-rig-offshore", description: "offshore platform: derrick on deck over water", Icon: OilRigOffshoreIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "RockFormations", label: "RockFormationsIcon", slug: "rock-formations", description: "triangle with layered strata lines (rock formations)", Icon: RockFormationsIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Seismic", label: "SeismicIcon", slug: "seismic", description: "horizontal line over concentric arcs (seismic reflection)", Icon: SeismicIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Strata", label: "StrataIcon", slug: "strata", description: "stacked layers with colored (pink-orange gradient) top layer", Icon: StrataIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: "layers" },
  { name: "Surface", label: "SurfaceIcon", slug: "surface", description: "curved 3D mesh/grid surface", Icon: SurfaceIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Trajectory", label: "TrajectoryIcon", slug: "trajectory", description: "curve from vertical to horizontal (well trajectory)", Icon: TrajectoryIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Valve", label: "ValveIcon", slug: "valve", description: "valve symbol: pipe with T-handle stem", Icon: ValveIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "VelocityModel", label: "VelocityModelIcon", slug: "velocity-model", description: "upward arrow through layered arcs (velocity model)", Icon: VelocityModelIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "Well", label: "WellIcon", slug: "well", description: "wellhead symbol: vertical line with two short side bars", Icon: WellIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "WellPick", label: "WellPickIcon", slug: "well-pick", description: "vertical line crossed by a horizontal pick marker with dot", Icon: WellPickIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
  { name: "WellPlan", label: "WellPlanIcon", slug: "well-plan", description: "dotted vertical line with wellhead symbol (planned well)", Icon: WellPlanIcon, source: "svg", sources: {"outlined":"svg","filled":"svg"}, domain: true, lucide: null },
]

/** Lookup by slug, e.g. `tectonIconsBySlug["add-circle"]`. */
export const tectonIconsBySlug: Readonly<Record<string, TectonIconEntry>> = Object.fromEntries(
  tectonIcons.map((entry) => [entry.slug, entry]),
)
