// GENERATED by scripts/build-icons.mts — do not edit
import { tectonIconNames, tectonIconTable } from "./names"
import { AddCircleIcon } from "./add-circle"
import { AddIcon } from "./add"
import { AddPinIcon } from "./add-pin"
import { AnnotateIcon } from "./annotate"
import { AppsIcon } from "./apps"
import { ArrowDownIcon } from "./arrow-down"
import { ArrowLeftIcon } from "./arrow-left"
import { ArrowRightIcon } from "./arrow-right"
import { ArrowUpIcon } from "./arrow-up"
import { CancelCircleIcon } from "./cancel-circle"
import { CaretCollapseIcon } from "./caret-collapse"
import { CaretUpDownIcon } from "./caret-up-down"
import { CheckCircleIcon } from "./check-circle"
import { CheckCircleOpenIcon } from "./check-circle-open"
import { CheckIcon } from "./check"
import { CheckboxIcon } from "./checkbox"
import { CheckboxOutlineBlankIcon } from "./checkbox-outline-blank"
import { ChevronDownIcon } from "./chevron-down"
import { ChevronDownSmallIcon } from "./chevron-down-small"
import { ChevronLeftIcon } from "./chevron-left"
import { ChevronLeftSmallIcon } from "./chevron-left-small"
import { ChevronRightIcon } from "./chevron-right"
import { ChevronRightSmallIcon } from "./chevron-right-small"
import { ChevronUpIcon } from "./chevron-up"
import { ChevronUpSmallIcon } from "./chevron-up-small"
import { ChristmasTreeIcon } from "./christmas-tree"
import { CloseIcon } from "./close"
import { CloseSmallIcon } from "./close-small"
import { Co2LeafIcon } from "./co-2-leaf"
import { CodeIcon } from "./code"
import { CollapseContentIcon } from "./collapse-content"
import { ControlsIcon } from "./controls"
import { CopyIcon } from "./copy"
import { CrownIcon } from "./crown"
import { CubeIcon } from "./cube"
import { DangerousIcon } from "./dangerous"
import { DatabaseIcon } from "./database"
import { DeleteIcon } from "./delete"
import { DesignIcon } from "./design"
import { DiamondMarkIcon } from "./diamond-mark"
import { DiscoveryIcon } from "./discovery"
import { DragIndicatorIcon } from "./drag-indicator"
import { DrillBitIcon } from "./drill-bit"
import { EditSquareIcon } from "./edit-square"
import { ElectricityIcon } from "./electricity"
import { EngineeringIcon } from "./engineering"
import { ErrorIcon } from "./error"
import { ExpandContentIcon } from "./expand-content"
import { ExportUploadIcon } from "./export-upload"
import { FacilityIcon } from "./facility"
import { FaultIcon } from "./fault"
import { FilterIcon } from "./filter"
import { FolderIcon } from "./folder"
import { FolderNewIcon } from "./folder-new"
import { FolderOpenIcon } from "./folder-open"
import { FrameworksIcon } from "./frameworks"
import { GeobodiesIcon } from "./geobodies"
import { GeostructureIcon } from "./geostructure"
import { GridViewIcon } from "./grid-view"
import { HistoryIcon } from "./history"
import { HomeIcon } from "./home"
import { HorizonIcon } from "./horizon"
import { ImageIcon } from "./image"
import { IndeterminateCheckboxIcon } from "./indeterminate-checkbox"
import { InfoIcon } from "./info"
import { InspectIcon } from "./inspect"
import { KanbanIcon } from "./kanban"
import { LayersIcon } from "./layers"
import { LineWeightIcon } from "./line-weight"
import { LinkIcon } from "./link"
import { LinkOffIcon } from "./link-off"
import { ListIcon } from "./list"
import { LockIcon } from "./lock"
import { LockOpenIcon } from "./lock-open"
import { LogCurveIcon } from "./log-curve"
import { MapIcon } from "./map"
import { MenuIcon } from "./menu"
import { MicrophoneIcon } from "./microphone"
import { MoneyIcon } from "./money"
import { MoreHorizIcon } from "./more-horiz"
import { MoreVertIcon } from "./more-vert"
import { NodeIcon } from "./node"
import { NotificationsIcon } from "./notifications"
import { NumericIcon } from "./numeric"
import { OilRigOffshoreIcon } from "./oil-rig-offshore"
import { OpenInNewIcon } from "./open-in-new"
import { PanToolIcon } from "./pan-tool"
import { PanelIcon } from "./panel"
import { PanelLeftIcon } from "./panel-left"
import { PersonIcon } from "./person"
import { PlayIcon } from "./play"
import { PreviewIcon } from "./preview"
import { ProgressActivityIcon } from "./progress-activity"
import { ProjectIcon } from "./project"
import { PulseIcon } from "./pulse"
import { RadioButtonIcon } from "./radio-button"
import { RedoIcon } from "./redo"
import { RemoveCircleIcon } from "./remove-circle"
import { RemoveIcon } from "./remove"
import { ReportsAnalyticsIcon } from "./reports-analytics"
import { RiskSkullIcon } from "./risk-skull"
import { Robot2Icon } from "./robot-2"
import { RockFormationsIcon } from "./rock-formations"
import { RotateIcon } from "./rotate"
import { RulerIcon } from "./ruler"
import { SearchIcon } from "./search"
import { SearchOffIcon } from "./search-off"
import { SeismicIcon } from "./seismic"
import { SelectCursorIcon } from "./select-cursor"
import { SelectIcon } from "./select"
import { SettingsIcon } from "./settings"
import { SliceIcon } from "./slice"
import { SortEnabledIcon } from "./sort-enabled"
import { SplitscreenIcon } from "./splitscreen"
import { StrataIcon } from "./strata"
import { SurfaceIcon } from "./surface"
import { SwapIcon } from "./swap"
import { TargetIcon } from "./target"
import { ThreeDIcon } from "./three-d"
import { TrajectoryIcon } from "./trajectory"
import { TrendIcon } from "./trend"
import { TrendingDownIcon } from "./trending-down"
import { TrendingUpIcon } from "./trending-up"
import { UndoIcon } from "./undo"
import { ValveIcon } from "./valve"
import { VelocityModelIcon } from "./velocity-model"
import { ViewColumnIcon } from "./view-column"
import { ViewModuleIcon } from "./view-module"
import { VisibilityIcon } from "./visibility"
import { VisibilityOffIcon } from "./visibility-off"
import { WarningIcon } from "./warning"
import { WaterIcon } from "./water"
import { WellIcon } from "./well"
import { WellPickIcon } from "./well-pick"
import { WellPlanIcon } from "./well-plan"
import { WindowIcon } from "./window"
import { ZoomInIcon } from "./zoom-in"
import { ZoomOutIcon } from "./zoom-out"
import type { TectonIconName } from "./names"
import type { TectonIconComponent, TectonIconEntry } from "./types"

export { Icon, tectonIcon, useTectonSymbolFontState } from "./icon"
export type { IconName, IconProps, TectonSymbolFontState } from "./icon"
export { tectonIconNames, tectonIconTable } from "./names"
export type { TectonIconName } from "./names"
export type {
  TectonIconComponent,
  TectonIconEntry,
  TectonIconMeta,
  TectonIconProps,
  TectonIconRecord,
  TectonIconSource,
  TectonIconVariant,
} from "./types"

export { AddCircleIcon } from "./add-circle"
export { AddIcon } from "./add"
export { AddPinIcon } from "./add-pin"
export { AnnotateIcon } from "./annotate"
export { AppsIcon } from "./apps"
export { ArrowDownIcon } from "./arrow-down"
export { ArrowLeftIcon } from "./arrow-left"
export { ArrowRightIcon } from "./arrow-right"
export { ArrowUpIcon } from "./arrow-up"
export { CancelCircleIcon } from "./cancel-circle"
export { CaretCollapseIcon } from "./caret-collapse"
export { CaretUpDownIcon } from "./caret-up-down"
export { CheckCircleIcon } from "./check-circle"
export { CheckCircleOpenIcon } from "./check-circle-open"
export { CheckIcon } from "./check"
export { CheckboxIcon } from "./checkbox"
export { CheckboxOutlineBlankIcon } from "./checkbox-outline-blank"
export { ChevronDownIcon } from "./chevron-down"
export { ChevronDownSmallIcon } from "./chevron-down-small"
export { ChevronLeftIcon } from "./chevron-left"
export { ChevronLeftSmallIcon } from "./chevron-left-small"
export { ChevronRightIcon } from "./chevron-right"
export { ChevronRightSmallIcon } from "./chevron-right-small"
export { ChevronUpIcon } from "./chevron-up"
export { ChevronUpSmallIcon } from "./chevron-up-small"
export { ChristmasTreeIcon } from "./christmas-tree"
export { CloseIcon } from "./close"
export { CloseSmallIcon } from "./close-small"
export { Co2LeafIcon } from "./co-2-leaf"
export { CodeIcon } from "./code"
export { CollapseContentIcon } from "./collapse-content"
export { ControlsIcon } from "./controls"
export { CopyIcon } from "./copy"
export { CrownIcon } from "./crown"
export { CubeIcon } from "./cube"
export { DangerousIcon } from "./dangerous"
export { DatabaseIcon } from "./database"
export { DeleteIcon } from "./delete"
export { DesignIcon } from "./design"
export { DiamondMarkIcon } from "./diamond-mark"
export { DiscoveryIcon } from "./discovery"
export { DragIndicatorIcon } from "./drag-indicator"
export { DrillBitIcon } from "./drill-bit"
export { EditSquareIcon } from "./edit-square"
export { ElectricityIcon } from "./electricity"
export { EngineeringIcon } from "./engineering"
export { ErrorIcon } from "./error"
export { ExpandContentIcon } from "./expand-content"
export { ExportUploadIcon } from "./export-upload"
export { FacilityIcon } from "./facility"
export { FaultIcon } from "./fault"
export { FilterIcon } from "./filter"
export { FolderIcon } from "./folder"
export { FolderNewIcon } from "./folder-new"
export { FolderOpenIcon } from "./folder-open"
export { FrameworksIcon } from "./frameworks"
export { GeobodiesIcon } from "./geobodies"
export { GeostructureIcon } from "./geostructure"
export { GridViewIcon } from "./grid-view"
export { HistoryIcon } from "./history"
export { HomeIcon } from "./home"
export { HorizonIcon } from "./horizon"
export { ImageIcon } from "./image"
export { IndeterminateCheckboxIcon } from "./indeterminate-checkbox"
export { InfoIcon } from "./info"
export { InspectIcon } from "./inspect"
export { KanbanIcon } from "./kanban"
export { LayersIcon } from "./layers"
export { LineWeightIcon } from "./line-weight"
export { LinkIcon } from "./link"
export { LinkOffIcon } from "./link-off"
export { ListIcon } from "./list"
export { LockIcon } from "./lock"
export { LockOpenIcon } from "./lock-open"
export { LogCurveIcon } from "./log-curve"
export { MapIcon } from "./map"
export { MenuIcon } from "./menu"
export { MicrophoneIcon } from "./microphone"
export { MoneyIcon } from "./money"
export { MoreHorizIcon } from "./more-horiz"
export { MoreVertIcon } from "./more-vert"
export { NodeIcon } from "./node"
export { NotificationsIcon } from "./notifications"
export { NumericIcon } from "./numeric"
export { OilRigOffshoreIcon } from "./oil-rig-offshore"
export { OpenInNewIcon } from "./open-in-new"
export { PanToolIcon } from "./pan-tool"
export { PanelIcon } from "./panel"
export { PanelLeftIcon } from "./panel-left"
export { PersonIcon } from "./person"
export { PlayIcon } from "./play"
export { PreviewIcon } from "./preview"
export { ProgressActivityIcon } from "./progress-activity"
export { ProjectIcon } from "./project"
export { PulseIcon } from "./pulse"
export { RadioButtonIcon } from "./radio-button"
export { RedoIcon } from "./redo"
export { RemoveCircleIcon } from "./remove-circle"
export { RemoveIcon } from "./remove"
export { ReportsAnalyticsIcon } from "./reports-analytics"
export { RiskSkullIcon } from "./risk-skull"
export { Robot2Icon } from "./robot-2"
export { RockFormationsIcon } from "./rock-formations"
export { RotateIcon } from "./rotate"
export { RulerIcon } from "./ruler"
export { SearchIcon } from "./search"
export { SearchOffIcon } from "./search-off"
export { SeismicIcon } from "./seismic"
export { SelectCursorIcon } from "./select-cursor"
export { SelectIcon } from "./select"
export { SettingsIcon } from "./settings"
export { SliceIcon } from "./slice"
export { SortEnabledIcon } from "./sort-enabled"
export { SplitscreenIcon } from "./splitscreen"
export { StrataIcon } from "./strata"
export { SurfaceIcon } from "./surface"
export { SwapIcon } from "./swap"
export { TargetIcon } from "./target"
export { ThreeDIcon } from "./three-d"
export { TrajectoryIcon } from "./trajectory"
export { TrendIcon } from "./trend"
export { TrendingDownIcon } from "./trending-down"
export { TrendingUpIcon } from "./trending-up"
export { UndoIcon } from "./undo"
export { ValveIcon } from "./valve"
export { VelocityModelIcon } from "./velocity-model"
export { ViewColumnIcon } from "./view-column"
export { ViewModuleIcon } from "./view-module"
export { VisibilityIcon } from "./visibility"
export { VisibilityOffIcon } from "./visibility-off"
export { WarningIcon } from "./warning"
export { WaterIcon } from "./water"
export { WellIcon } from "./well"
export { WellPickIcon } from "./well-pick"
export { WellPlanIcon } from "./well-plan"
export { WindowIcon } from "./window"
export { ZoomInIcon } from "./zoom-in"
export { ZoomOutIcon } from "./zoom-out"

/** The component behind each name — what `tectonIcons[].Icon` renders. */
const components: Record<TectonIconName, TectonIconComponent> = {
  "add-circle": AddCircleIcon,
  "add": AddIcon,
  "add-pin": AddPinIcon,
  "annotate": AnnotateIcon,
  "apps": AppsIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  "cancel-circle": CancelCircleIcon,
  "caret-collapse": CaretCollapseIcon,
  "caret-up-down": CaretUpDownIcon,
  "check-circle": CheckCircleIcon,
  "check-circle-open": CheckCircleOpenIcon,
  "check": CheckIcon,
  "checkbox": CheckboxIcon,
  "checkbox-outline-blank": CheckboxOutlineBlankIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-down-small": ChevronDownSmallIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-left-small": ChevronLeftSmallIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-right-small": ChevronRightSmallIcon,
  "chevron-up": ChevronUpIcon,
  "chevron-up-small": ChevronUpSmallIcon,
  "christmas-tree": ChristmasTreeIcon,
  "close": CloseIcon,
  "close-small": CloseSmallIcon,
  "co-2-leaf": Co2LeafIcon,
  "code": CodeIcon,
  "collapse-content": CollapseContentIcon,
  "controls": ControlsIcon,
  "copy": CopyIcon,
  "crown": CrownIcon,
  "cube": CubeIcon,
  "dangerous": DangerousIcon,
  "database": DatabaseIcon,
  "delete": DeleteIcon,
  "design": DesignIcon,
  "diamond-mark": DiamondMarkIcon,
  "discovery": DiscoveryIcon,
  "drag-indicator": DragIndicatorIcon,
  "drill-bit": DrillBitIcon,
  "edit-square": EditSquareIcon,
  "electricity": ElectricityIcon,
  "engineering": EngineeringIcon,
  "error": ErrorIcon,
  "expand-content": ExpandContentIcon,
  "export-upload": ExportUploadIcon,
  "facility": FacilityIcon,
  "fault": FaultIcon,
  "filter": FilterIcon,
  "folder": FolderIcon,
  "folder-new": FolderNewIcon,
  "folder-open": FolderOpenIcon,
  "frameworks": FrameworksIcon,
  "geobodies": GeobodiesIcon,
  "geostructure": GeostructureIcon,
  "grid-view": GridViewIcon,
  "history": HistoryIcon,
  "home": HomeIcon,
  "horizon": HorizonIcon,
  "image": ImageIcon,
  "indeterminate-checkbox": IndeterminateCheckboxIcon,
  "info": InfoIcon,
  "inspect": InspectIcon,
  "kanban": KanbanIcon,
  "layers": LayersIcon,
  "line-weight": LineWeightIcon,
  "link": LinkIcon,
  "link-off": LinkOffIcon,
  "list": ListIcon,
  "lock": LockIcon,
  "lock-open": LockOpenIcon,
  "log-curve": LogCurveIcon,
  "map": MapIcon,
  "menu": MenuIcon,
  "microphone": MicrophoneIcon,
  "money": MoneyIcon,
  "more-horiz": MoreHorizIcon,
  "more-vert": MoreVertIcon,
  "node": NodeIcon,
  "notifications": NotificationsIcon,
  "numeric": NumericIcon,
  "oil-rig-offshore": OilRigOffshoreIcon,
  "open-in-new": OpenInNewIcon,
  "pan-tool": PanToolIcon,
  "panel": PanelIcon,
  "panel-left": PanelLeftIcon,
  "person": PersonIcon,
  "play": PlayIcon,
  "preview": PreviewIcon,
  "progress-activity": ProgressActivityIcon,
  "project": ProjectIcon,
  "pulse": PulseIcon,
  "radio-button": RadioButtonIcon,
  "redo": RedoIcon,
  "remove-circle": RemoveCircleIcon,
  "remove": RemoveIcon,
  "reports-analytics": ReportsAnalyticsIcon,
  "risk-skull": RiskSkullIcon,
  "robot-2": Robot2Icon,
  "rock-formations": RockFormationsIcon,
  "rotate": RotateIcon,
  "ruler": RulerIcon,
  "search": SearchIcon,
  "search-off": SearchOffIcon,
  "seismic": SeismicIcon,
  "select-cursor": SelectCursorIcon,
  "select": SelectIcon,
  "settings": SettingsIcon,
  "slice": SliceIcon,
  "sort-enabled": SortEnabledIcon,
  "splitscreen": SplitscreenIcon,
  "strata": StrataIcon,
  "surface": SurfaceIcon,
  "swap": SwapIcon,
  "target": TargetIcon,
  "three-d": ThreeDIcon,
  "trajectory": TrajectoryIcon,
  "trend": TrendIcon,
  "trending-down": TrendingDownIcon,
  "trending-up": TrendingUpIcon,
  "undo": UndoIcon,
  "valve": ValveIcon,
  "velocity-model": VelocityModelIcon,
  "view-column": ViewColumnIcon,
  "view-module": ViewModuleIcon,
  "visibility": VisibilityIcon,
  "visibility-off": VisibilityOffIcon,
  "warning": WarningIcon,
  "water": WaterIcon,
  "well": WellIcon,
  "well-pick": WellPickIcon,
  "well-plan": WellPlanIcon,
  "window": WindowIcon,
  "zoom-in": ZoomInIcon,
  "zoom-out": ZoomOutIcon,
}

/** Every Tecton icon, in manifest (alphabetical) order — drives the docs gallery. */
export const tectonIcons: ReadonlyArray<TectonIconEntry> = tectonIconNames.map((slug) => ({
  ...tectonIconTable[slug],
  slug,
  Icon: components[slug],
}))

/** Lookup by slug, e.g. `tectonIconsBySlug["add-circle"]`. */
export const tectonIconsBySlug: Readonly<Record<string, TectonIconEntry>> = Object.fromEntries(
  tectonIcons.map((entry) => [entry.slug, entry]),
)
