"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `info` (U+E88E), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** InfoIcon — circle with i */
export const InfoIcon = tectonIcon("info")
