// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Info` (manifest: lucide: "info").
// Drop icons-src/outlined/info.svg in place and re-run `pnpm icons:build`.
import { Info as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** InfoIcon — circle with i */
export function InfoIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="info"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
InfoIcon.displayName = "InfoIcon"
