// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/inspect.ts (outline)
//   filled: icons-src/tecton/inspect.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** InspectIcon — scan corners with magnifier in center */
export function InspectIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="inspect"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M8.68333 8.686C9.00556 8.36544 9.16667 7.971 9.16667 7.50267C9.16667 7.03422 9.00644 6.63889 8.686 6.31667C8.36544 5.99444 7.971 5.83333 7.50267 5.83333C7.03422 5.83333 6.63889 5.99356 6.31667 6.314C5.99444 6.63456 5.83333 7.029 5.83333 7.49733C5.83333 7.96578 5.99356 8.36111 6.314 8.68333C6.63456 9.00556 7.029 9.16667 7.49733 9.16667C7.96578 9.16667 8.36111 9.00644 8.68333 8.686ZM10.7167 11.4333L8.98333 9.7C8.73889 9.85556 8.49167 9.97222 8.24167 10.05C7.99167 10.1278 7.74706 10.1667 7.50783 10.1667C6.76928 10.1667 6.13889 9.90556 5.61667 9.38333C5.09444 8.86111 4.83333 8.23333 4.83333 7.5C4.83333 6.76667 5.09444 6.13889 5.61667 5.61667C6.13889 5.09444 6.76667 4.83333 7.5 4.83333C8.23333 4.83333 8.86111 5.09444 9.38333 5.61667C9.90556 6.13889 10.1667 6.76928 10.1667 7.50783C10.1667 7.74706 10.125 7.99167 10.0417 8.24167C9.95833 8.49167 9.83889 8.73889 9.68333 8.98333L11.4333 10.7333L10.7167 11.4333ZM3 14C2.73333 14 2.5 13.9 2.3 13.7C2.1 13.5 2 13.2667 2 13V10.1333H3V13H5.86667V14H3ZM10.1333 14V13H13V10.1333H14V13C14 13.2667 13.9 13.5 13.7 13.7C13.5 13.9 13.2667 14 13 14H10.1333ZM2 5.86667V3C2 2.73333 2.1 2.5 2.3 2.3C2.5 2.1 2.73333 2 3 2H5.86667V3H3V5.86667H2ZM13 5.86667V3H10.1333V2H13C13.2667 2 13.5 2.1 13.7 2.3C13.9 2.5 14 2.73333 14 3V5.86667H13Z">
          </path>
        </>
      ) : (
        <>
          <path d="M8.68332 8.686C9.00554 8.36544 9.16665 7.971 9.16665 7.50267C9.16665 7.03422 9.00643 6.63889 8.68598 6.31667C8.36543 5.99444 7.97098 5.83333 7.50265 5.83333C7.03421 5.83333 6.63887 5.99356 6.31665 6.314C5.99443 6.63456 5.83332 7.029 5.83332 7.49733C5.83332 7.96578 5.99354 8.36111 6.31398 8.68333C6.63454 9.00556 7.02899 9.16667 7.49732 9.16667C7.96576 9.16667 8.3611 9.00644 8.68332 8.686ZM10.7167 11.4333L8.98332 9.7C8.73887 9.85556 8.49165 9.97222 8.24165 10.05C7.99165 10.1278 7.74704 10.1667 7.50782 10.1667C6.76926 10.1667 6.13887 9.90556 5.61665 9.38333C5.09443 8.86111 4.83332 8.23333 4.83332 7.5C4.83332 6.76667 5.09443 6.13889 5.61665 5.61667C6.13887 5.09444 6.76665 4.83333 7.49999 4.83333C8.23332 4.83333 8.8611 5.09444 9.38332 5.61667C9.90554 6.13889 10.1667 6.76928 10.1667 7.50783C10.1667 7.74706 10.125 7.99167 10.0417 8.24167C9.95832 8.49167 9.83887 8.73889 9.68332 8.98333L11.4333 10.7333L10.7167 11.4333ZM2.99998 14C2.73332 14 2.49998 13.9 2.29998 13.7C2.09998 13.5 1.99998 13.2667 1.99998 13V10.1333H2.99998V13H5.86665V14H2.99998ZM10.1333 14V13H13V10.1333H14V13C14 13.2667 13.9 13.5 13.7 13.7C13.5 13.9 13.2667 14 13 14H10.1333ZM1.99998 5.86667V3C1.99998 2.73333 2.09998 2.5 2.29998 2.3C2.49998 2.1 2.73332 2 2.99998 2H5.86665V3H2.99998V5.86667H1.99998ZM13 5.86667V3H10.1333V2H13C13.2667 2 13.5 2.1 13.7 2.3C13.9 2.5 14 2.73333 14 3V5.86667H13Z">
          </path>
        </>
      )}
    </svg>
  )
}
InspectIcon.displayName = "InspectIcon"
