"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `keyboard` (U+E312), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** KeyboardIcon — keyboard with key rows */
export const KeyboardIcon = tectonIcon("keyboard")
