"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100043 outlined, U+100843 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** LayersIcon — two stacked diamonds */
export const LayersIcon = tectonIcon("layers")
