// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/layers.ts (outline)
//   filled: icons-src/tecton/layers.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** LayersIcon — two stacked diamonds */
export function LayersIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="layers"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M8.00002 13.6251L2.10002 9.05841L2.90002 8.46674L8.00002 12.4167L13.1084 8.46674L13.9 9.05841L8.00002 13.6251ZM8.00002 11.2084L2.10002 6.64174L8.00002 2.07507L13.9 6.64174L8.00002 11.2084Z">
          </path>
        </>
      ) : (
        <>
          <path d="M8.00002 13.6251L2.10002 9.05841L2.90002 8.46674L8.00002 12.4167L13.1084 8.46674L13.9 9.05841L8.00002 13.6251ZM8.00002 11.2084L2.10002 6.64174L8.00002 2.07507L13.9 6.64174L8.00002 11.2084ZM8.00002 10.0001L12.3334 6.64174L8.00002 3.28341L3.67502 6.64174L8.00002 10.0001Z">
          </path>
        </>
      )}
    </svg>
  )
}
LayersIcon.displayName = "LayersIcon"
