// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Layers` (manifest: lucide: "layers").
// Drop icons-src/outlined/layers.svg in place and re-run `pnpm icons:build`.
import { Layers as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** LayersIcon — two stacked diamonds */
export function LayersIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="layers"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
LayersIcon.displayName = "LayersIcon"
