"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `left_panel_open` (U+F716), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** LeftPanelOpenIcon — frame with the left panel opening */
export const LeftPanelOpenIcon = tectonIcon("left-panel-open")
