"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `library_add_check` (U+E9B7), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** LibraryAddCheckIcon — stacked pages with a check mark */
export const LibraryAddCheckIcon = tectonIcon("library-add-check")
