// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/line-weight.ts (outline)
//   filled: icons-src/tecton/line-weight.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** LineWeightIcon — stacked horizontal bars of increasing thickness */
export function LineWeightIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="line-weight"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M2.52499 13.25V12.7667H14.15V13.25H2.52499ZM2.52499 11.8083V10.85H14.15V11.8083H2.52499ZM2.52499 9.89167V8.45833H14.15V9.89167H2.52499ZM2.52499 7.5V2.75H14.15V7.5H2.52499Z">
      </path>
    </svg>
  )
}
LineWeightIcon.displayName = "LineWeightIcon"
