// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Link` (manifest: lucide: "link").
// Drop icons-src/outlined/link.svg in place and re-run `pnpm icons:build`.
import { Link as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** LinkIcon — chain link */
export function LinkIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="link"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
LinkIcon.displayName = "LinkIcon"
