// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/link.ts (outline)
//   filled: icons-src/tecton/link.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** LinkIcon — chain link */
export function LinkIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="link"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M7.49167 11.275H4.69201C3.78623 11.275 3.01389 10.9555 2.37501 10.3166C1.73612 9.67775 1.41667 8.90553 1.41667 7.99998C1.41667 7.09442 1.73612 6.3222 2.37501 5.68331C3.01389 5.04442 3.78623 4.72498 4.69201 4.72498H7.49167V5.68331H4.69001C4.04856 5.68331 3.50234 5.90809 3.05134 6.35764C2.60045 6.80709 2.37501 7.35292 2.37501 7.99514C2.37501 8.63725 2.60023 9.1847 3.05067 9.63748C3.50112 10.0903 4.04812 10.3166 4.69167 10.3166H7.49167V11.275ZM5.45001 8.47498V7.51664H10.55V8.47498H5.45001ZM8.50834 11.275V10.3166H11.31C11.9514 10.3166 12.4977 10.0919 12.9487 9.64231C13.3996 9.19286 13.625 8.64703 13.625 8.00481C13.625 7.3627 13.3998 6.81525 12.9493 6.36248C12.4989 5.9097 11.9519 5.68331 11.3083 5.68331H8.50834V4.72498H11.308C12.2138 4.72498 12.9861 5.04442 13.625 5.68331C14.2639 6.3222 14.5833 7.09442 14.5833 7.99998C14.5833 8.90553 14.2639 9.67775 13.625 10.3166C12.9861 10.9555 12.2138 11.275 11.308 11.275H8.50834Z">
      </path>
    </svg>
  )
}
LinkIcon.displayName = "LinkIcon"
