// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/link-off.ts (outline)
//   filled: icons-src/tecton/link-off.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** LinkOffIcon — chain link with diagonal strike */
export function LinkOffIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="link-off"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M12.4583 11.0999L11.6667 10.3165C12.2259 10.2062 12.6921 9.94116 13.0653 9.52138C13.4385 9.10149 13.625 8.61099 13.625 8.04988C13.625 7.4101 13.3988 6.86405 12.9465 6.41171C12.4942 5.95938 11.9481 5.73321 11.3083 5.73321H8.76668V4.77488H11.3062C12.2132 4.77488 12.9861 5.09432 13.625 5.73321C14.2639 6.3721 14.5833 7.14466 14.5833 8.05088C14.5833 8.72888 14.3861 9.33988 13.9917 9.88388C13.5972 10.4279 13.0861 10.8332 12.4583 11.0999ZM9.87301 8.52488L8.91668 7.56655H10.55V8.52488H9.87301ZM13.5583 14.9832L1.13335 2.56654L1.82501 1.87488L14.25 14.2999L13.5583 14.9832ZM7.49168 11.2749H4.69201C3.78624 11.2749 3.0139 10.9554 2.37501 10.3165C1.73612 9.67766 1.41668 8.90655 1.41668 8.00321C1.41668 7.20888 1.6639 6.50832 2.15835 5.90154C2.65279 5.29488 3.28612 4.91932 4.05835 4.77488L4.95835 5.68321H4.69168C4.0519 5.68321 3.50585 5.90927 3.05351 6.36138C2.60118 6.81349 2.37501 7.35932 2.37501 7.99888C2.37501 8.63843 2.60118 9.1846 3.05351 9.63738C3.50585 10.0902 4.0519 10.3165 4.69168 10.3165H7.49168V11.2749ZM5.45001 8.47488V7.51654H6.79168L7.75001 8.47488H5.45001Z">
      </path>
    </svg>
  )
}
LinkOffIcon.displayName = "LinkOffIcon"
