"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `link_off` (U+E16F), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** LinkOffIcon — chain link with diagonal strike */
export const LinkOffIcon = tectonIcon("link-off")
