"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `list` (U+E896), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ListIcon — three bullet lines */
export const ListIcon = tectonIcon("list")
