// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `List` (manifest: lucide: "list").
// Drop icons-src/outlined/list.svg in place and re-run `pnpm icons:build`.
import { List as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ListIcon — three bullet lines */
export function ListIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="list"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ListIcon.displayName = "ListIcon"
