// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/list.ts (outline)
//   filled: icons-src/tecton/list.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** ListIcon — three bullet lines */
export function ListIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="list"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M4.86666 5.725V4.76666H13.9167V5.725H4.86666ZM4.86666 8.475V7.51666H13.9167V8.475H4.86666ZM4.86666 11.225V10.2667H13.9167V11.225H4.86666ZM2.56666 5.725C2.43888 5.725 2.32638 5.67638 2.22916 5.57916C2.13194 5.48194 2.08333 5.36527 2.08333 5.22916C2.08333 5.10416 2.13194 4.99583 2.22916 4.90416C2.32638 4.8125 2.44305 4.76666 2.57916 4.76666C2.70972 4.76666 2.82083 4.81338 2.91249 4.90683C3.00416 5.00016 3.04999 5.11177 3.04999 5.24166C3.04999 5.36944 3.00388 5.48194 2.91166 5.57916C2.81944 5.67638 2.70444 5.725 2.56666 5.725ZM2.56666 8.475C2.43888 8.475 2.32638 8.42639 2.22916 8.32916C2.13194 8.23194 2.08333 8.11411 2.08333 7.97566C2.08333 7.84844 2.13194 7.73872 2.22916 7.6465C2.32638 7.55439 2.44305 7.50833 2.57916 7.50833C2.70972 7.50833 2.82083 7.55511 2.91249 7.64866C3.00416 7.74222 3.04999 7.854 3.04999 7.984C3.04999 8.11688 3.00388 8.23194 2.91166 8.32916C2.81944 8.42639 2.70444 8.475 2.56666 8.475ZM2.56666 11.225C2.43888 11.225 2.32638 11.1778 2.22916 11.0833C2.13194 10.9889 2.08333 10.875 2.08333 10.7417C2.08333 10.6099 2.13194 10.4964 2.22916 10.4012C2.32638 10.3059 2.44305 10.2583 2.57916 10.2583C2.70972 10.2583 2.82083 10.3066 2.91249 10.4032C3.00416 10.4998 3.04999 10.6154 3.04999 10.75C3.04999 10.8778 3.00388 10.9889 2.91166 11.0833C2.81944 11.1778 2.70444 11.225 2.56666 11.225Z">
      </path>
    </svg>
  )
}
ListIcon.displayName = "ListIcon"
