// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Lock` (manifest: lucide: "lock").
// Drop icons-src/outlined/lock.svg in place and re-run `pnpm icons:build`.
import { Lock as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** LockIcon — closed padlock */
export function LockIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="lock"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
LockIcon.displayName = "LockIcon"
