// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/lock-open.ts (outline)
//   filled: icons-src/tecton/lock-open.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** LockOpenIcon — open padlock */
export function LockOpenIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="lock-open"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M2.74165 14.5832V5.48317H10.15V3.8935C10.15 3.29584 9.94299 2.78917 9.52899 2.3735C9.11488 1.95773 8.60654 1.74984 8.00399 1.74984C7.40132 1.74984 6.89165 1.95723 6.47499 2.372C6.05832 2.78689 5.84999 3.29617 5.84999 3.89984H4.89165C4.89165 3.03373 5.19382 2.29912 5.79815 1.696C6.40249 1.093 7.13721 0.791504 8.00232 0.791504C8.86743 0.791504 9.60138 1.09345 10.2042 1.69734C10.8069 2.30123 11.1083 3.03623 11.1083 3.90234V5.48317H13.2583V14.5832H2.74165ZM8.89165 10.932C9.1361 10.6924 9.25832 10.4044 9.25832 10.0678C9.25832 9.74184 9.13565 9.44484 8.89032 9.17684C8.64488 8.90884 8.34765 8.77484 7.99865 8.77484C7.64954 8.77484 7.35276 8.90834 7.10832 9.17534C6.86388 9.44245 6.74165 9.74184 6.74165 10.0735C6.74165 10.4051 6.86432 10.6909 7.10965 10.9312C7.3551 11.1714 7.65232 11.2915 8.00132 11.2915C8.35043 11.2915 8.64721 11.1717 8.89165 10.932Z">
          </path>
        </>
      ) : (
        <>
          <path d="M2.74165 14.5832V5.48317H10.15V3.8935C10.15 3.29584 9.94299 2.78917 9.52899 2.3735C9.11488 1.95773 8.60654 1.74984 8.00399 1.74984C7.40132 1.74984 6.89165 1.95723 6.47499 2.372C6.05832 2.78689 5.84999 3.29617 5.84999 3.89984H4.89165C4.89165 3.03373 5.19382 2.29912 5.79815 1.696C6.40249 1.093 7.13721 0.791504 8.00232 0.791504C8.86743 0.791504 9.60138 1.09345 10.2042 1.69734C10.8069 2.30123 11.1083 3.03623 11.1083 3.90234V5.48317H13.2583V14.5832H2.74165ZM3.69999 13.6248H12.3V6.4415H3.69999V13.6248ZM8.89165 10.932C9.1361 10.6924 9.25832 10.4044 9.25832 10.0678C9.25832 9.74184 9.13565 9.44484 8.89032 9.17684C8.64488 8.90884 8.34765 8.77484 7.99865 8.77484C7.64954 8.77484 7.35276 8.90834 7.10832 9.17534C6.86388 9.44245 6.74165 9.74184 6.74165 10.0735C6.74165 10.4051 6.86432 10.6909 7.10965 10.9312C7.3551 11.1714 7.65232 11.2915 8.00132 11.2915C8.35043 11.2915 8.64721 11.1717 8.89165 10.932Z">
          </path>
        </>
      )}
    </svg>
  )
}
LockOpenIcon.displayName = "LockOpenIcon"
