// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/lock.ts (outline)
//   filled: icons-src/tecton/lock.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** LockIcon — closed padlock */
export function LockIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="lock"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M2.74165 14.5834V5.48342H4.89165V3.89975C4.89165 3.03497 5.19382 2.3008 5.79815 1.69725C6.40249 1.09358 7.13721 0.791748 8.00232 0.791748C8.86743 0.791748 9.60138 1.09369 10.2042 1.69758C10.8069 2.30147 11.1083 3.03647 11.1083 3.90258V5.48342H13.2583V14.5834H2.74165ZM8.89165 10.9322C9.1361 10.6927 9.25832 10.4046 9.25832 10.0681C9.25832 9.74208 9.13565 9.44508 8.89032 9.17708C8.64488 8.90908 8.34765 8.77508 7.99865 8.77508C7.64954 8.77508 7.35276 8.90858 7.10832 9.17558C6.86388 9.44269 6.74165 9.74208 6.74165 10.0737C6.74165 10.4053 6.86432 10.6912 7.10965 10.9314C7.3551 11.1716 7.65232 11.2917 8.00132 11.2917C8.35043 11.2917 8.64721 11.1719 8.89165 10.9322ZM5.84999 5.48342H10.15V3.89375C10.15 3.29608 9.94299 2.78941 9.52899 2.37375C9.11488 1.95797 8.60654 1.75008 8.00399 1.75008C7.40132 1.75008 6.89165 1.95747 6.47499 2.37225C6.05832 2.78714 5.84999 3.29514 5.84999 3.89625V5.48342Z">
          </path>
        </>
      ) : (
        <>
          <path d="M2.74165 14.5834V5.48342H4.89165V3.89975C4.89165 3.03497 5.19382 2.3008 5.79815 1.69725C6.40249 1.09358 7.13721 0.791748 8.00232 0.791748C8.86743 0.791748 9.60138 1.09369 10.2042 1.69758C10.8069 2.30147 11.1083 3.03647 11.1083 3.90258V5.48342H13.2583V14.5834H2.74165ZM3.69999 13.6251H12.3V6.44175H3.69999V13.6251ZM8.89165 10.9322C9.1361 10.6927 9.25832 10.4046 9.25832 10.0681C9.25832 9.74208 9.13565 9.44508 8.89032 9.17708C8.64488 8.90908 8.34765 8.77508 7.99865 8.77508C7.64954 8.77508 7.35276 8.90858 7.10832 9.17558C6.86388 9.44269 6.74165 9.74208 6.74165 10.0737C6.74165 10.4053 6.86432 10.6912 7.10965 10.9314C7.3551 11.1716 7.65232 11.2917 8.00132 11.2917C8.35043 11.2917 8.64721 11.1719 8.89165 10.9322ZM5.84999 5.48342H10.15V3.89375C10.15 3.29608 9.94299 2.78941 9.52899 2.37375C9.11488 1.95797 8.60654 1.75008 8.00399 1.75008C7.40132 1.75008 6.89165 1.95747 6.47499 2.37225C6.05832 2.78714 5.84999 3.29514 5.84999 3.89625V5.48342Z">
          </path>
        </>
      )}
    </svg>
  )
}
LockIcon.displayName = "LockIcon"
