"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `lock_open` (U+E898), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** LockOpenIcon — open padlock */
export const LockOpenIcon = tectonIcon("lock-open")
