// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `LockOpen` (manifest: lucide: "lock-open").
// Drop icons-src/outlined/lock-open.svg in place and re-run `pnpm icons:build`.
import { LockOpen as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** LockOpenIcon — open padlock */
export function LockOpenIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="lock-open"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
LockOpenIcon.displayName = "LockOpenIcon"
