"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `logout` (U+E9BA), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** LogoutIcon — arrow leaving a bracket */
export const LogoutIcon = tectonIcon("logout")
