// GENERATED by scripts/build-icons.mts — do not edit
//
// lucide-react identifiers used by src/components + src/tecton, resolved to
// Tecton glyphs where a real SVG source exists. Consumed by ./lucide-compat.ts.
// Everything else lucide exports passes straight through (star re-export;
// the explicit exports below shadow it).

export * from "lucide-react"

// 18 Tecton override(s)
export { ArrowDownIcon } from "./arrow-down" // src/components/message-scroller.tsx
export { CheckIcon } from "./check" // src/components/dropdown-menu.tsx, src/components/checkbox.tsx, src/components/combobox.tsx, src/components/questionnaire.tsx, src/components/command.tsx, src/components/context-menu.tsx, src/components/select.tsx, src/tecton/copy-button.tsx
export { ChevronDownIcon } from "./chevron-down" // src/components/native-select.tsx, src/components/accordion.tsx, src/components/combobox.tsx, src/components/select.tsx
export { ChevronLeftIcon } from "./chevron-left" // src/components/pagination.tsx, src/components/carousel.tsx, src/components/calendar.tsx, src/tecton/data-table.tsx
export { ChevronRightIcon } from "./chevron-right" // src/components/breadcrumb.tsx, src/components/pagination.tsx, src/components/carousel.tsx, src/components/dropdown-menu.tsx, src/components/calendar.tsx, src/components/context-menu.tsx, src/tecton/tree-view.tsx, src/tecton/data-table.tsx
export { ChevronUpIcon } from "./chevron-up" // src/components/accordion.tsx
export { ErrorIcon as CircleAlertIcon } from "./error" // src/tecton/status-alert.tsx
export { CheckCircleIcon as CircleCheckIcon } from "./check-circle" // src/components/sonner.tsx, src/tecton/status-alert.tsx
export { CopyIcon } from "./copy" // src/tecton/copy-button.tsx
export { VisibilityIcon as EyeIcon } from "./visibility" // src/tecton/tree-view.tsx
export { VisibilityOffIcon as EyeOffIcon } from "./visibility-off" // src/tecton/tree-view.tsx
export { FolderIcon } from "./folder" // src/tecton/tree-view.tsx
export { FolderOpenIcon } from "./folder-open" // src/tecton/tree-view.tsx
export { InfoIcon } from "./info" // src/components/sonner.tsx, src/tecton/status-alert.tsx
export { RemoveIcon as MinusIcon } from "./remove" // src/components/input-otp.tsx, src/tecton/stat.tsx
export { SearchIcon } from "./search" // src/components/command.tsx, src/components/select.tsx
export { WarningIcon as TriangleAlertIcon } from "./warning" // src/components/sonner.tsx, src/tecton/status-alert.tsx
export { CloseIcon as XIcon } from "./close" // src/components/dialog.tsx, src/components/combobox.tsx, src/components/sheet.tsx, src/tecton/status-alert.tsx, src/tecton/chip.tsx

// 8 lucide pass-through(s) (no Tecton SVG source yet)
export { ExternalLinkIcon } from "lucide-react" // src/tecton/link.tsx
export { Loader2Icon } from "lucide-react" // src/components/spinner.tsx, src/components/sonner.tsx
export { MoreHorizontalIcon } from "lucide-react" // src/components/breadcrumb.tsx, src/components/pagination.tsx
export { MoreVerticalIcon } from "lucide-react" // src/tecton/tree-view.tsx
export { OctagonXIcon } from "lucide-react" // src/components/sonner.tsx
export { PanelLeftIcon } from "lucide-react" // src/components/sidebar.tsx
export { TrendingDownIcon } from "lucide-react" // src/tecton/stat.tsx
export { TrendingUpIcon } from "lucide-react" // src/tecton/stat.tsx

/** Which identifiers are served by Tecton vs lucide — handy for docs / tests. */
export const tectonLucideCompat = {
  ArrowDownIcon: "arrow-down",
  CheckIcon: "check",
  ChevronDownIcon: "chevron-down",
  ChevronLeftIcon: "chevron-left",
  ChevronRightIcon: "chevron-right",
  ChevronUpIcon: "chevron-up",
  CircleAlertIcon: "error",
  CircleCheckIcon: "check-circle",
  CopyIcon: "copy",
  ExternalLinkIcon: "lucide",
  EyeIcon: "visibility",
  EyeOffIcon: "visibility-off",
  FolderIcon: "folder",
  FolderOpenIcon: "folder-open",
  InfoIcon: "info",
  Loader2Icon: "lucide",
  MinusIcon: "remove",
  MoreHorizontalIcon: "lucide",
  MoreVerticalIcon: "lucide",
  OctagonXIcon: "lucide",
  PanelLeftIcon: "lucide",
  SearchIcon: "search",
  TrendingDownIcon: "lucide",
  TrendingUpIcon: "lucide",
  TriangleAlertIcon: "warning",
  XIcon: "close",
} as const
