// GENERATED by scripts/build-icons.mts — do not edit
//
// lucide-react identifiers used by src/components, src/tecton and src/blocks,
// plus every lucide name (and alias) a Tecton SVG stands in for, resolved to
// Tecton glyphs where a real SVG source exists. Consumed by ./lucide-compat.ts.
// Everything else lucide exports passes straight through (star re-export;
// the explicit exports below shadow it).

export * from "lucide-react"

// 381 Tecton override(s)
export { PulseIcon as Activity } from "./pulse" // catalogue
export { PulseIcon as ActivityIcon } from "./pulse" // catalogue
export { ErrorIcon as AlertCircle } from "./error" // catalogue
export { ErrorIcon as AlertCircleIcon } from "./error" // catalogue
export { WarningIcon as AlertTriangle } from "./warning" // catalogue
export { WarningIcon as AlertTriangleIcon } from "./warning" // src/blocks/detail-01/components/concept-section.tsx
export { ArrowDownIcon as ArrowDown } from "./arrow-down" // catalogue
export { ArrowDownIcon } from "./arrow-down" // src/components/message-scroller.tsx
export { ArrowLeftIcon as ArrowLeft } from "./arrow-left" // catalogue
export { ArrowLeftIcon } from "./arrow-left" // catalogue
export { ArrowRightIcon as ArrowRight } from "./arrow-right" // catalogue
export { ArrowRightIcon } from "./arrow-right" // catalogue
export { ArrowUpIcon as ArrowUp } from "./arrow-up" // catalogue
export { SortEnabledIcon as ArrowUpDown } from "./sort-enabled" // catalogue
export { SortEnabledIcon as ArrowUpDownIcon } from "./sort-enabled" // catalogue
export { ArrowUpIcon } from "./arrow-up" // src/blocks/ai-agent-panel/components/agent-composer.tsx
export { OpenInNewIcon as ArrowUpRightFromSquare } from "./open-in-new" // catalogue
export { OpenInNewIcon as ArrowUpRightFromSquareIcon } from "./open-in-new" // catalogue
export { ReportsAnalyticsIcon as BarChart3 } from "./reports-analytics" // catalogue
export { ReportsAnalyticsIcon as BarChart3Icon } from "./reports-analytics" // catalogue
export { NotificationsIcon as Bell } from "./notifications" // catalogue
export { NotificationsIcon as BellIcon } from "./notifications" // src/blocks/dashboard-01/components/top-nav.tsx, src/blocks/settings-01/page.tsx, src/blocks/sidebar-01/components/nav-user.tsx, src/blocks/sidebar-02/components/nav-user.tsx, src/blocks/sidebar-04/components/nav-user.tsx
export { Robot2Icon as Bot } from "./robot-2" // catalogue
export { Robot2Icon as BotIcon } from "./robot-2" // catalogue
export { CubeIcon as Box } from "./cube" // catalogue
export { CubeIcon as BoxIcon } from "./cube" // src/blocks/sidebar-01/data.ts, src/blocks/sidebar-02/data.ts, src/blocks/sidebar-04/data.ts
export { SelectIcon as BoxSelect } from "./select" // catalogue
export { SelectIcon as BoxSelectIcon } from "./select" // catalogue
export { ReportsAnalyticsIcon as ChartColumn } from "./reports-analytics" // catalogue
export { ReportsAnalyticsIcon as ChartColumnIcon } from "./reports-analytics" // src/blocks/sidebar-01/data.ts, src/blocks/sidebar-02/data.ts, src/blocks/sidebar-04/data.ts
export { TrendIcon as ChartNoAxesCombined } from "./trend" // catalogue
export { TrendIcon as ChartNoAxesCombinedIcon } from "./trend" // catalogue
export { CheckIcon as Check } from "./check" // catalogue
export { CheckCircleIcon as CheckCircle2 } from "./check-circle" // catalogue
export { CheckCircleIcon as CheckCircle2Icon } from "./check-circle" // catalogue
export { CheckIcon } from "./check" // src/components/checkbox.tsx, src/components/combobox.tsx, src/components/command.tsx, src/components/context-menu.tsx, src/components/dropdown-menu.tsx, src/components/questionnaire.tsx, src/components/select.tsx, src/tecton/copy-button.tsx, src/blocks/ai-agent-panel/components/agent-message-list.tsx
export { CheckboxIcon as CheckSquare2 } from "./checkbox" // catalogue
export { CheckboxIcon as CheckSquare2Icon } from "./checkbox" // catalogue
export { ChevronDownIcon as ChevronDown } from "./chevron-down" // catalogue
export { ChevronDownIcon } from "./chevron-down" // src/components/accordion.tsx, src/components/combobox.tsx, src/components/native-select.tsx, src/components/select.tsx, src/tecton/app-finder.tsx, src/blocks/ai-agent-panel/components/agent-message-list.tsx, src/blocks/canvas-01/components/preset-list.tsx, src/blocks/facies-modeling-panel/components/facies-form.tsx
export { ChevronLeftIcon as ChevronLeft } from "./chevron-left" // catalogue
export { ChevronLeftIcon } from "./chevron-left" // src/components/calendar.tsx, src/components/carousel.tsx, src/components/pagination.tsx, src/blocks/list-01/components/wells-table.tsx
export { ChevronRightIcon as ChevronRight } from "./chevron-right" // catalogue
export { ChevronRightIcon } from "./chevron-right" // src/components/breadcrumb.tsx, src/components/calendar.tsx, src/components/carousel.tsx, src/components/context-menu.tsx, src/components/dropdown-menu.tsx, src/components/pagination.tsx, src/tecton/tree-view.tsx, src/blocks/detail-01/components/project-sidebar.tsx, src/blocks/fda-card/components/fda-card.tsx, src/blocks/list-01/components/wells-table.tsx, src/blocks/sidebar-01/components/nav-main.tsx
export { CaretCollapseIcon as ChevronsDownUp } from "./caret-collapse" // catalogue
export { CaretCollapseIcon as ChevronsDownUpIcon } from "./caret-collapse" // catalogue
export { CaretUpDownIcon as ChevronsUpDown } from "./caret-up-down" // catalogue
export { CaretUpDownIcon as ChevronsUpDownIcon } from "./caret-up-down" // src/blocks/sidebar-01/components/nav-user.tsx, src/blocks/sidebar-01/components/project-switcher.tsx, src/blocks/sidebar-02/components/nav-user.tsx, src/blocks/sidebar-04/components/nav-user.tsx
export { ChevronUpIcon as ChevronUp } from "./chevron-up" // catalogue
export { ChevronUpIcon } from "./chevron-up" // src/components/accordion.tsx, src/blocks/detail-01/components/concept-section.tsx
export { RadioButtonIcon as Circle } from "./radio-button" // catalogue
export { ErrorIcon as CircleAlert } from "./error" // catalogue
export { ErrorIcon as CircleAlertIcon } from "./error" // src/blocks/login-01/components/login-form.tsx
export { CheckCircleIcon as CircleCheck } from "./check-circle" // catalogue
export { CheckCircleIcon as CircleCheckIcon } from "./check-circle" // src/components/sonner.tsx, src/blocks/detail-01/components/concept-section.tsx, src/blocks/facies-modeling-panel/page.tsx, src/blocks/settings-01/page.tsx
export { CheckCircleOpenIcon as CircleDashed } from "./check-circle-open" // catalogue
export { CheckCircleOpenIcon as CircleDashedIcon } from "./check-circle-open" // src/blocks/detail-01/components/concept-section.tsx
export { RadioButtonIcon as CircleIcon } from "./radio-button" // catalogue
export { RemoveCircleIcon as CircleMinus } from "./remove-circle" // catalogue
export { RemoveCircleIcon as CircleMinusIcon } from "./remove-circle" // catalogue
export { AddCircleIcon as CirclePlus } from "./add-circle" // catalogue
export { AddCircleIcon as CirclePlusIcon } from "./add-circle" // catalogue
export { CancelCircleIcon as CircleX } from "./cancel-circle" // catalogue
export { CancelCircleIcon as CircleXIcon } from "./cancel-circle" // catalogue
export { CodeIcon as Code } from "./code" // catalogue
export { CodeIcon } from "./code" // catalogue
export { SplitscreenIcon as Columns } from "./splitscreen" // catalogue
export { SplitscreenIcon as Columns2 } from "./splitscreen" // catalogue
export { SplitscreenIcon as Columns2Icon } from "./splitscreen" // catalogue
export { ViewColumnIcon as Columns3 } from "./view-column" // catalogue
export { ViewColumnIcon as Columns3Icon } from "./view-column" // catalogue
export { SplitscreenIcon as ColumnsIcon } from "./splitscreen" // catalogue
export { DiscoveryIcon as Compass } from "./discovery" // catalogue
export { DiscoveryIcon as CompassIcon } from "./discovery" // catalogue
export { CopyIcon as Copy } from "./copy" // catalogue
export { CopyIcon } from "./copy" // src/tecton/copy-button.tsx, src/blocks/fda-card/components/fda-card.tsx, src/blocks/fda-comparison-table/components/fda-columns.tsx, src/blocks/well-design-card/components/well-design-card.tsx
export { CrownIcon as Crown } from "./crown" // catalogue
export { CrownIcon } from "./crown" // src/blocks/cost-vs-risk-panel/page.tsx, src/blocks/well-design-card/components/well-design-card.tsx
export { DatabaseIcon as Database } from "./database" // catalogue
export { DatabaseIcon } from "./database" // src/blocks/canvas-01/components/preset-list.tsx, src/blocks/list-01/components/wells-table.tsx
export { DiamondMarkIcon as Diamond } from "./diamond-mark" // catalogue
export { DiamondMarkIcon as DiamondIcon } from "./diamond-mark" // catalogue
export { MoneyIcon as DollarSign } from "./money" // catalogue
export { MoneyIcon as DollarSignIcon } from "./money" // catalogue
export { EngineeringIcon as DraftingCompass } from "./engineering" // catalogue
export { EngineeringIcon as DraftingCompassIcon } from "./engineering" // catalogue
export { WaterIcon as Droplet } from "./water" // catalogue
export { WaterIcon as DropletIcon } from "./water" // src/blocks/detail-01/components/concept-section.tsx
export { EditSquareIcon as Edit } from "./edit-square" // catalogue
export { EditSquareIcon as EditIcon } from "./edit-square" // catalogue
export { MoreVertIcon as EllipsisVertical } from "./more-vert" // catalogue
export { MoreVertIcon as EllipsisVerticalIcon } from "./more-vert" // catalogue
export { ExpandContentIcon as Expand } from "./expand-content" // catalogue
export { ExpandContentIcon as ExpandIcon } from "./expand-content" // catalogue
export { VisibilityIcon as Eye } from "./visibility" // catalogue
export { VisibilityIcon as EyeIcon } from "./visibility" // src/tecton/tree-view.tsx
export { VisibilityOffIcon as EyeOff } from "./visibility-off" // catalogue
export { VisibilityOffIcon as EyeOffIcon } from "./visibility-off" // src/tecton/tree-view.tsx
export { FacilityIcon as Factory } from "./facility" // catalogue
export { FacilityIcon as FactoryIcon } from "./facility" // src/blocks/detail-01/components/concept-section.tsx
export { FilterIcon as Filter } from "./filter" // catalogue
export { FilterIcon } from "./filter" // catalogue
export { TargetIcon as Focus } from "./target" // catalogue
export { TargetIcon as FocusIcon } from "./target" // catalogue
export { FolderIcon as Folder } from "./folder" // catalogue
export { FolderIcon } from "./folder" // src/tecton/tree-view.tsx, src/blocks/sidebar-02/components/nav-recent.tsx
export { FolderOpenIcon as FolderOpen } from "./folder-open" // catalogue
export { FolderOpenIcon } from "./folder-open" // src/tecton/tree-view.tsx
export { FolderNewIcon as FolderPlus } from "./folder-new" // catalogue
export { FolderNewIcon as FolderPlusIcon } from "./folder-new" // catalogue
export { SwapIcon as FoldHorizontal } from "./swap" // catalogue
export { SwapIcon as FoldHorizontalIcon } from "./swap" // catalogue
export { FilterIcon as Funnel } from "./filter" // catalogue
export { FilterIcon as FunnelIcon } from "./filter" // catalogue
export { ViewModuleIcon as Grid } from "./view-module" // catalogue
export { WindowIcon as Grid2x2 } from "./window" // catalogue
export { WindowIcon as Grid2X2 } from "./window" // catalogue
export { WindowIcon as Grid2x2Icon } from "./window" // catalogue
export { WindowIcon as Grid2X2Icon } from "./window" // catalogue
export { ViewModuleIcon as Grid3x3 } from "./view-module" // catalogue
export { ViewModuleIcon as Grid3X3 } from "./view-module" // catalogue
export { ViewModuleIcon as Grid3x3Icon } from "./view-module" // catalogue
export { ViewModuleIcon as Grid3X3Icon } from "./view-module" // catalogue
export { ViewModuleIcon as GridIcon } from "./view-module" // catalogue
export { AppsIcon as Grip } from "./apps" // catalogue
export { AppsIcon as GripIcon } from "./apps" // catalogue
export { DragIndicatorIcon as GripVertical } from "./drag-indicator" // catalogue
export { DragIndicatorIcon as GripVerticalIcon } from "./drag-indicator" // catalogue
export { PanToolIcon as Hand } from "./pan-tool" // catalogue
export { PanToolIcon as HandIcon } from "./pan-tool" // src/blocks/canvas-01/page.tsx
export { NumericIcon as Hash } from "./numeric" // catalogue
export { NumericIcon as HashIcon } from "./numeric" // catalogue
export { AnnotateIcon as Highlighter } from "./annotate" // catalogue
export { AnnotateIcon as HighlighterIcon } from "./annotate" // catalogue
export { HomeIcon as Home } from "./home" // catalogue
export { HomeIcon } from "./home" // src/blocks/shell-01/components/shell-header.tsx
export { HomeIcon as House } from "./home" // catalogue
export { HomeIcon as HouseIcon } from "./home" // catalogue
export { ImageIcon as Image } from "./image" // catalogue
export { ImageIcon } from "./image" // catalogue
export { InfoIcon as Info } from "./info" // catalogue
export { InfoIcon } from "./info" // src/components/sonner.tsx, src/blocks/settings-01/components/settings-forms.tsx
export { KanbanIcon as KanbanSquare } from "./kanban" // catalogue
export { KanbanIcon as KanbanSquareIcon } from "./kanban" // catalogue
export { LayersIcon as Layers } from "./layers" // catalogue
export { LayersIcon as Layers3 } from "./layers" // catalogue
export { LayersIcon as Layers3Icon } from "./layers" // catalogue
export { LayersIcon } from "./layers" // src/blocks/ai-agent-panel/components/agent-panel-header.tsx, src/blocks/canvas-01/page.tsx, src/blocks/dashboard-01/components/top-nav.tsx, src/blocks/login-01/components/login-form.tsx, src/blocks/sidebar-03/page.tsx
export { GridViewIcon as LayoutGrid } from "./grid-view" // catalogue
export { GridViewIcon as LayoutGridIcon } from "./grid-view" // catalogue
export { LinkIcon as Link } from "./link" // catalogue
export { LinkIcon } from "./link" // catalogue
export { ListIcon as List } from "./list" // catalogue
export { ListIcon } from "./list" // src/blocks/detail-01/page.tsx
export { LockIcon as Lock } from "./lock" // catalogue
export { LockIcon } from "./lock" // catalogue
export { LockOpenIcon as LockOpen } from "./lock-open" // catalogue
export { LockOpenIcon } from "./lock-open" // catalogue
export { PulseIcon as LucideActivity } from "./pulse" // catalogue
export { ErrorIcon as LucideAlertCircle } from "./error" // catalogue
export { WarningIcon as LucideAlertTriangle } from "./warning" // catalogue
export { ArrowDownIcon as LucideArrowDown } from "./arrow-down" // catalogue
export { ArrowLeftIcon as LucideArrowLeft } from "./arrow-left" // catalogue
export { ArrowRightIcon as LucideArrowRight } from "./arrow-right" // catalogue
export { ArrowUpIcon as LucideArrowUp } from "./arrow-up" // catalogue
export { SortEnabledIcon as LucideArrowUpDown } from "./sort-enabled" // catalogue
export { OpenInNewIcon as LucideArrowUpRightFromSquare } from "./open-in-new" // catalogue
export { ReportsAnalyticsIcon as LucideBarChart3 } from "./reports-analytics" // catalogue
export { NotificationsIcon as LucideBell } from "./notifications" // catalogue
export { Robot2Icon as LucideBot } from "./robot-2" // catalogue
export { CubeIcon as LucideBox } from "./cube" // catalogue
export { SelectIcon as LucideBoxSelect } from "./select" // catalogue
export { ReportsAnalyticsIcon as LucideChartColumn } from "./reports-analytics" // catalogue
export { TrendIcon as LucideChartNoAxesCombined } from "./trend" // catalogue
export { CheckIcon as LucideCheck } from "./check" // catalogue
export { CheckCircleIcon as LucideCheckCircle2 } from "./check-circle" // catalogue
export { CheckboxIcon as LucideCheckSquare2 } from "./checkbox" // catalogue
export { ChevronDownIcon as LucideChevronDown } from "./chevron-down" // catalogue
export { ChevronLeftIcon as LucideChevronLeft } from "./chevron-left" // catalogue
export { ChevronRightIcon as LucideChevronRight } from "./chevron-right" // catalogue
export { CaretCollapseIcon as LucideChevronsDownUp } from "./caret-collapse" // catalogue
export { CaretUpDownIcon as LucideChevronsUpDown } from "./caret-up-down" // catalogue
export { ChevronUpIcon as LucideChevronUp } from "./chevron-up" // catalogue
export { RadioButtonIcon as LucideCircle } from "./radio-button" // catalogue
export { ErrorIcon as LucideCircleAlert } from "./error" // catalogue
export { CheckCircleIcon as LucideCircleCheck } from "./check-circle" // catalogue
export { CheckCircleOpenIcon as LucideCircleDashed } from "./check-circle-open" // catalogue
export { RemoveCircleIcon as LucideCircleMinus } from "./remove-circle" // catalogue
export { AddCircleIcon as LucideCirclePlus } from "./add-circle" // catalogue
export { CancelCircleIcon as LucideCircleX } from "./cancel-circle" // catalogue
export { CodeIcon as LucideCode } from "./code" // catalogue
export { SplitscreenIcon as LucideColumns } from "./splitscreen" // catalogue
export { SplitscreenIcon as LucideColumns2 } from "./splitscreen" // catalogue
export { ViewColumnIcon as LucideColumns3 } from "./view-column" // catalogue
export { DiscoveryIcon as LucideCompass } from "./discovery" // catalogue
export { CopyIcon as LucideCopy } from "./copy" // catalogue
export { CrownIcon as LucideCrown } from "./crown" // catalogue
export { DatabaseIcon as LucideDatabase } from "./database" // catalogue
export { DiamondMarkIcon as LucideDiamond } from "./diamond-mark" // catalogue
export { MoneyIcon as LucideDollarSign } from "./money" // catalogue
export { EngineeringIcon as LucideDraftingCompass } from "./engineering" // catalogue
export { WaterIcon as LucideDroplet } from "./water" // catalogue
export { EditSquareIcon as LucideEdit } from "./edit-square" // catalogue
export { MoreVertIcon as LucideEllipsisVertical } from "./more-vert" // catalogue
export { ExpandContentIcon as LucideExpand } from "./expand-content" // catalogue
export { VisibilityIcon as LucideEye } from "./visibility" // catalogue
export { VisibilityOffIcon as LucideEyeOff } from "./visibility-off" // catalogue
export { FacilityIcon as LucideFactory } from "./facility" // catalogue
export { FilterIcon as LucideFilter } from "./filter" // catalogue
export { TargetIcon as LucideFocus } from "./target" // catalogue
export { FolderIcon as LucideFolder } from "./folder" // catalogue
export { FolderOpenIcon as LucideFolderOpen } from "./folder-open" // catalogue
export { FolderNewIcon as LucideFolderPlus } from "./folder-new" // catalogue
export { SwapIcon as LucideFoldHorizontal } from "./swap" // catalogue
export { FilterIcon as LucideFunnel } from "./filter" // catalogue
export { ViewModuleIcon as LucideGrid } from "./view-module" // catalogue
export { WindowIcon as LucideGrid2x2 } from "./window" // catalogue
export { WindowIcon as LucideGrid2X2 } from "./window" // catalogue
export { ViewModuleIcon as LucideGrid3x3 } from "./view-module" // catalogue
export { ViewModuleIcon as LucideGrid3X3 } from "./view-module" // catalogue
export { AppsIcon as LucideGrip } from "./apps" // catalogue
export { DragIndicatorIcon as LucideGripVertical } from "./drag-indicator" // catalogue
export { PanToolIcon as LucideHand } from "./pan-tool" // catalogue
export { NumericIcon as LucideHash } from "./numeric" // catalogue
export { AnnotateIcon as LucideHighlighter } from "./annotate" // catalogue
export { HomeIcon as LucideHome } from "./home" // catalogue
export { HomeIcon as LucideHouse } from "./home" // catalogue
export { ImageIcon as LucideImage } from "./image" // catalogue
export { InfoIcon as LucideInfo } from "./info" // catalogue
export { KanbanIcon as LucideKanbanSquare } from "./kanban" // catalogue
export { LayersIcon as LucideLayers } from "./layers" // catalogue
export { LayersIcon as LucideLayers3 } from "./layers" // catalogue
export { GridViewIcon as LucideLayoutGrid } from "./grid-view" // catalogue
export { LinkIcon as LucideLink } from "./link" // catalogue
export { ListIcon as LucideList } from "./list" // catalogue
export { LockIcon as LucideLock } from "./lock" // catalogue
export { LockOpenIcon as LucideLockOpen } from "./lock-open" // catalogue
export { MapIcon as LucideMap } from "./map" // catalogue
export { AddPinIcon as LucideMapPinPlus } from "./add-pin" // catalogue
export { MenuIcon as LucideMenu } from "./menu" // catalogue
export { MicrophoneIcon as LucideMic } from "./microphone" // catalogue
export { CollapseContentIcon as LucideMinimize } from "./collapse-content" // catalogue
export { RemoveIcon as LucideMinus } from "./remove" // catalogue
export { RemoveCircleIcon as LucideMinusCircle } from "./remove-circle" // catalogue
export { IndeterminateCheckboxIcon as LucideMinusSquare } from "./indeterminate-checkbox" // catalogue
export { MoreVertIcon as LucideMoreVertical } from "./more-vert" // catalogue
export { SelectCursorIcon as LucideMousePointer } from "./select-cursor" // catalogue
export { PanelIcon as LucidePanelRight } from "./panel" // catalogue
export { ViewColumnIcon as LucidePanelsLeftRight } from "./view-column" // catalogue
export { EditSquareIcon as LucidePenBox } from "./edit-square" // catalogue
export { DesignIcon as LucidePencilRuler } from "./design" // catalogue
export { EditSquareIcon as LucidePenSquare } from "./edit-square" // catalogue
export { PlayIcon as LucidePlay } from "./play" // catalogue
export { AddIcon as LucidePlus } from "./add" // catalogue
export { AddCircleIcon as LucidePlusCircle } from "./add-circle" // catalogue
export { RedoIcon as LucideRedo } from "./redo" // catalogue
export { RotateIcon as LucideRotate3d } from "./rotate" // catalogue
export { RotateIcon as LucideRotate3D } from "./rotate" // catalogue
export { RulerIcon as LucideRuler } from "./ruler" // catalogue
export { PreviewIcon as LucideScanEye } from "./preview" // catalogue
export { InspectIcon as LucideScanSearch } from "./inspect" // catalogue
export { SearchIcon as LucideSearch } from "./search" // catalogue
export { SettingsIcon as LucideSettings } from "./settings" // catalogue
export { RiskSkullIcon as LucideSkull } from "./risk-skull" // catalogue
export { ControlsIcon as LucideSlidersHorizontal } from "./controls" // catalogue
export { Co2LeafIcon as LucideSprout } from "./co-2-leaf" // catalogue
export { CheckboxOutlineBlankIcon as LucideSquare } from "./checkbox-outline-blank" // catalogue
export { OpenInNewIcon as LucideSquareArrowOutUpRight } from "./open-in-new" // catalogue
export { CheckboxIcon as LucideSquareCheck } from "./checkbox" // catalogue
export { SelectIcon as LucideSquareDashed } from "./select" // catalogue
export { KanbanIcon as LucideSquareKanban } from "./kanban" // catalogue
export { IndeterminateCheckboxIcon as LucideSquareMinus } from "./indeterminate-checkbox" // catalogue
export { EditSquareIcon as LucideSquarePen } from "./edit-square" // catalogue
export { WarningIcon as LucideTriangleAlert } from "./warning" // catalogue
export { UndoIcon as LucideUndo } from "./undo" // catalogue
export { LinkOffIcon as LucideUnlink } from "./link-off" // catalogue
export { LockOpenIcon as LucideUnlock } from "./lock-open" // catalogue
export { ExportUploadIcon as LucideUpload } from "./export-upload" // catalogue
export { PersonIcon as LucideUser } from "./person" // catalogue
export { NodeIcon as LucideWaypoints } from "./node" // catalogue
export { CloseIcon as LucideX } from "./close" // catalogue
export { CancelCircleIcon as LucideXCircle } from "./cancel-circle" // catalogue
export { ElectricityIcon as LucideZap } from "./electricity" // catalogue
export { ZoomInIcon as LucideZoomIn } from "./zoom-in" // catalogue
export { ZoomOutIcon as LucideZoomOut } from "./zoom-out" // catalogue
export { MapIcon as Map } from "./map" // catalogue
export { MapIcon } from "./map" // src/blocks/sidebar-03/page.tsx
export { AddPinIcon as MapPinPlus } from "./add-pin" // catalogue
export { AddPinIcon as MapPinPlusIcon } from "./add-pin" // catalogue
export { MenuIcon as Menu } from "./menu" // catalogue
export { MenuIcon } from "./menu" // catalogue
export { MicrophoneIcon as Mic } from "./microphone" // catalogue
export { MicrophoneIcon as MicIcon } from "./microphone" // src/blocks/ai-agent-panel/components/agent-composer.tsx
export { CollapseContentIcon as Minimize } from "./collapse-content" // catalogue
export { CollapseContentIcon as MinimizeIcon } from "./collapse-content" // catalogue
export { RemoveIcon as Minus } from "./remove" // catalogue
export { RemoveCircleIcon as MinusCircle } from "./remove-circle" // catalogue
export { RemoveCircleIcon as MinusCircleIcon } from "./remove-circle" // catalogue
export { RemoveIcon as MinusIcon } from "./remove" // src/components/input-otp.tsx, src/tecton/stat.tsx
export { IndeterminateCheckboxIcon as MinusSquare } from "./indeterminate-checkbox" // catalogue
export { IndeterminateCheckboxIcon as MinusSquareIcon } from "./indeterminate-checkbox" // catalogue
export { MoreVertIcon as MoreVertical } from "./more-vert" // catalogue
export { MoreVertIcon as MoreVerticalIcon } from "./more-vert" // src/tecton/tree-view.tsx, src/blocks/ai-agent-panel/components/agent-panel-header.tsx, src/blocks/canvas-01/components/preset-list.tsx, src/blocks/canvas-01/page.tsx, src/blocks/detail-01/components/concept-section.tsx, src/blocks/fda-card/components/fda-card.tsx, src/blocks/fda-comparison-table/components/fda-columns.tsx, src/blocks/list-01/components/wells-table.tsx, src/blocks/well-design-card/components/well-design-card.tsx
export { SelectCursorIcon as MousePointer } from "./select-cursor" // catalogue
export { SelectCursorIcon as MousePointerIcon } from "./select-cursor" // catalogue
export { PanelIcon as PanelRight } from "./panel" // catalogue
export { PanelIcon as PanelRightIcon } from "./panel" // src/blocks/cost-vs-risk-panel/page.tsx, src/blocks/facies-modeling-panel/page.tsx, src/blocks/horizons-panel/page.tsx
export { ViewColumnIcon as PanelsLeftRight } from "./view-column" // catalogue
export { ViewColumnIcon as PanelsLeftRightIcon } from "./view-column" // catalogue
export { EditSquareIcon as PenBox } from "./edit-square" // catalogue
export { EditSquareIcon as PenBoxIcon } from "./edit-square" // catalogue
export { DesignIcon as PencilRuler } from "./design" // catalogue
export { DesignIcon as PencilRulerIcon } from "./design" // catalogue
export { EditSquareIcon as PenSquare } from "./edit-square" // catalogue
export { EditSquareIcon as PenSquareIcon } from "./edit-square" // catalogue
export { PlayIcon as Play } from "./play" // catalogue
export { PlayIcon } from "./play" // src/blocks/facies-modeling-panel/page.tsx
export { AddIcon as Plus } from "./add" // catalogue
export { AddCircleIcon as PlusCircle } from "./add-circle" // catalogue
export { AddCircleIcon as PlusCircleIcon } from "./add-circle" // catalogue
export { AddIcon as PlusIcon } from "./add" // src/blocks/dashboard-01/components/project-tree.tsx, src/blocks/dashboard-01/page.tsx, src/blocks/detail-01/components/concept-section.tsx, src/blocks/detail-01/components/project-sidebar.tsx, src/blocks/fda-comparison-table/page.tsx, src/blocks/list-01/components/wells-table.tsx, src/blocks/list-01/page.tsx, src/blocks/sidebar-01/components/project-switcher.tsx, src/blocks/sidebar-03/components/app-sidebar.tsx
export { RedoIcon as Redo } from "./redo" // catalogue
export { RedoIcon } from "./redo" // src/blocks/canvas-01/page.tsx
export { RotateIcon as Rotate3d } from "./rotate" // catalogue
export { RotateIcon as Rotate3D } from "./rotate" // catalogue
export { RotateIcon as Rotate3dIcon } from "./rotate" // catalogue
export { RotateIcon as Rotate3DIcon } from "./rotate" // catalogue
export { RulerIcon as Ruler } from "./ruler" // catalogue
export { RulerIcon } from "./ruler" // src/blocks/canvas-01/page.tsx, src/blocks/sidebar-03/page.tsx
export { PreviewIcon as ScanEye } from "./preview" // catalogue
export { PreviewIcon as ScanEyeIcon } from "./preview" // catalogue
export { InspectIcon as ScanSearch } from "./inspect" // catalogue
export { InspectIcon as ScanSearchIcon } from "./inspect" // catalogue
export { SearchIcon as Search } from "./search" // catalogue
export { SearchIcon } from "./search" // src/components/command.tsx, src/components/select.tsx, src/tecton/shell-actions.tsx, src/blocks/dashboard-01/components/top-nav.tsx, src/blocks/list-01/components/wells-filter-bar.tsx, src/blocks/sidebar-02/components/app-sidebar.tsx, src/blocks/sidebar-03/components/app-sidebar.tsx
export { SettingsIcon as Settings } from "./settings" // catalogue
export { SettingsIcon } from "./settings" // src/blocks/dashboard-01/components/top-nav.tsx, src/blocks/shell-01/components/shell-header.tsx, src/blocks/sidebar-01/components/nav-user.tsx, src/blocks/sidebar-02/components/nav-user.tsx, src/blocks/sidebar-02/data.ts, src/blocks/sidebar-04/components/nav-user.tsx, src/blocks/sidebar-04/data.ts
export { RiskSkullIcon as Skull } from "./risk-skull" // catalogue
export { RiskSkullIcon as SkullIcon } from "./risk-skull" // catalogue
export { ControlsIcon as SlidersHorizontal } from "./controls" // catalogue
export { ControlsIcon as SlidersHorizontalIcon } from "./controls" // src/blocks/facies-modeling-panel/components/facies-form.tsx
export { Co2LeafIcon as Sprout } from "./co-2-leaf" // catalogue
export { Co2LeafIcon as SproutIcon } from "./co-2-leaf" // catalogue
export { CheckboxOutlineBlankIcon as Square } from "./checkbox-outline-blank" // catalogue
export { OpenInNewIcon as SquareArrowOutUpRight } from "./open-in-new" // catalogue
export { OpenInNewIcon as SquareArrowOutUpRightIcon } from "./open-in-new" // catalogue
export { CheckboxIcon as SquareCheck } from "./checkbox" // catalogue
export { CheckboxIcon as SquareCheckIcon } from "./checkbox" // catalogue
export { SelectIcon as SquareDashed } from "./select" // catalogue
export { SelectIcon as SquareDashedIcon } from "./select" // src/blocks/canvas-01/page.tsx
export { CheckboxOutlineBlankIcon as SquareIcon } from "./checkbox-outline-blank" // catalogue
export { KanbanIcon as SquareKanban } from "./kanban" // catalogue
export { KanbanIcon as SquareKanbanIcon } from "./kanban" // catalogue
export { IndeterminateCheckboxIcon as SquareMinus } from "./indeterminate-checkbox" // catalogue
export { IndeterminateCheckboxIcon as SquareMinusIcon } from "./indeterminate-checkbox" // catalogue
export { EditSquareIcon as SquarePen } from "./edit-square" // catalogue
export { EditSquareIcon as SquarePenIcon } from "./edit-square" // catalogue
export { WarningIcon as TriangleAlert } from "./warning" // catalogue
export { WarningIcon as TriangleAlertIcon } from "./warning" // src/components/sonner.tsx, src/blocks/facies-modeling-panel/page.tsx
export { UndoIcon as Undo } from "./undo" // catalogue
export { UndoIcon } from "./undo" // src/blocks/canvas-01/page.tsx
export { LinkOffIcon as Unlink } from "./link-off" // catalogue
export { LinkOffIcon as UnlinkIcon } from "./link-off" // catalogue
export { LockOpenIcon as Unlock } from "./lock-open" // catalogue
export { LockOpenIcon as UnlockIcon } from "./lock-open" // catalogue
export { ExportUploadIcon as Upload } from "./export-upload" // catalogue
export { ExportUploadIcon as UploadIcon } from "./export-upload" // src/blocks/canvas-01/page.tsx, src/blocks/list-01/page.tsx
export { PersonIcon as User } from "./person" // catalogue
export { PersonIcon as UserIcon } from "./person" // src/blocks/dashboard-01/components/top-nav.tsx, src/blocks/settings-01/page.tsx, src/blocks/shell-01/components/shell-header.tsx, src/blocks/sidebar-01/components/nav-user.tsx, src/blocks/sidebar-02/components/nav-user.tsx, src/blocks/sidebar-04/components/nav-user.tsx
export { NodeIcon as Waypoints } from "./node" // catalogue
export { NodeIcon as WaypointsIcon } from "./node" // src/blocks/detail-01/page.tsx
export { CloseIcon as X } from "./close" // catalogue
export { CancelCircleIcon as XCircle } from "./cancel-circle" // catalogue
export { CancelCircleIcon as XCircleIcon } from "./cancel-circle" // catalogue
export { CloseIcon as XIcon } from "./close" // src/components/combobox.tsx, src/components/dialog.tsx, src/components/sheet.tsx, src/tecton/chip.tsx, src/blocks/ai-agent-panel/components/agent-panel-header.tsx, src/blocks/facies-modeling-panel/page.tsx, src/blocks/list-01/components/wells-filter-bar.tsx, src/blocks/login-01/components/login-form.tsx, src/blocks/settings-01/page.tsx
export { ElectricityIcon as Zap } from "./electricity" // catalogue
export { ElectricityIcon as ZapIcon } from "./electricity" // catalogue
export { ZoomInIcon as ZoomIn } from "./zoom-in" // catalogue
export { ZoomInIcon } from "./zoom-in" // src/blocks/canvas-01/page.tsx, src/blocks/sidebar-03/page.tsx
export { ZoomOutIcon as ZoomOut } from "./zoom-out" // catalogue
export { ZoomOutIcon } from "./zoom-out" // src/blocks/canvas-01/page.tsx, src/blocks/sidebar-03/page.tsx

// 39 lucide pass-through(s) (no Tecton SVG source yet)
export { AppWindowIcon } from "lucide-react" // src/blocks/shell-01/components/shell-command-palette.tsx
export { BugIcon } from "lucide-react" // src/blocks/shell-01/components/shell-header.tsx
export { BuildingIcon } from "lucide-react" // src/blocks/login-01/components/login-form.tsx
export { CircleHelpIcon } from "lucide-react" // src/blocks/shell-01/components/shell-header.tsx
export { CommandIcon } from "lucide-react" // src/blocks/shell-01/components/shell-command-palette.tsx
export { DicesIcon } from "lucide-react" // src/blocks/facies-modeling-panel/components/facies-form.tsx
export { DownloadIcon } from "lucide-react" // src/blocks/dashboard-01/page.tsx, src/blocks/list-01/page.tsx
export { DrillIcon } from "lucide-react" // src/blocks/sidebar-01/data.ts, src/blocks/sidebar-02/data.ts, src/blocks/sidebar-04/data.ts
export { ExternalLinkIcon } from "lucide-react" // src/tecton/link.tsx
export { FileTextIcon } from "lucide-react" // src/blocks/sidebar-01/data.ts
export { GitCompareIcon } from "lucide-react" // src/blocks/sidebar-01/data.ts, src/blocks/sidebar-02/data.ts, src/blocks/sidebar-04/data.ts
export { HexagonIcon } from "lucide-react" // src/blocks/sidebar-01/components/project-switcher.tsx, src/blocks/sidebar-02/components/app-sidebar.tsx, src/blocks/sidebar-02/components/nav-recent.tsx, src/blocks/sidebar-03/components/app-sidebar.tsx, src/blocks/sidebar-04/components/nav-rail.tsx
export { LassoIcon } from "lucide-react" // src/blocks/canvas-01/page.tsx
export { LayoutDashboardIcon } from "lucide-react" // src/blocks/sidebar-01/data.ts, src/blocks/sidebar-02/data.ts, src/blocks/sidebar-04/data.ts
export { LeafIcon } from "lucide-react" // src/blocks/sidebar-01/data.ts
export { LifeBuoyIcon } from "lucide-react" // src/blocks/sidebar-02/data.ts
export { Loader2Icon } from "lucide-react" // src/components/sonner.tsx, src/components/spinner.tsx
export { LogOutIcon } from "lucide-react" // src/blocks/dashboard-01/components/top-nav.tsx, src/blocks/shell-01/components/shell-header.tsx, src/blocks/sidebar-01/components/nav-user.tsx, src/blocks/sidebar-02/components/nav-user.tsx, src/blocks/sidebar-04/components/nav-user.tsx
export { MessageSquareIcon } from "lucide-react" // src/blocks/sidebar-02/data.ts
export { MoreHorizontalIcon } from "lucide-react" // src/components/breadcrumb.tsx, src/components/pagination.tsx, src/blocks/sidebar-02/components/nav-recent.tsx
export { MountainIcon } from "lucide-react" // src/blocks/sidebar-01/data.ts, src/blocks/sidebar-02/data.ts, src/blocks/sidebar-04/data.ts
export { MousePointer2Icon } from "lucide-react" // src/blocks/canvas-01/page.tsx
export { OctagonXIcon } from "lucide-react" // src/components/sonner.tsx
export { PaletteIcon } from "lucide-react" // src/blocks/settings-01/page.tsx
export { PanelLeftIcon } from "lucide-react" // src/components/sidebar.tsx
export { PanelRightCloseIcon } from "lucide-react" // src/blocks/sidebar-04/components/tool-panel.tsx
export { PanelRightOpenIcon } from "lucide-react" // src/blocks/sidebar-04/page.tsx
export { PaperclipIcon } from "lucide-react" // src/blocks/ai-agent-panel/components/agent-composer.tsx
export { PencilIcon } from "lucide-react" // src/blocks/canvas-01/page.tsx, src/blocks/fda-comparison-table/components/fda-columns.tsx, src/blocks/well-design-card/components/well-design-card.tsx
export { RotateCcwIcon } from "lucide-react" // src/blocks/sidebar-04/components/tool-panel.tsx
export { ScanIcon } from "lucide-react" // src/blocks/canvas-01/page.tsx
export { Share2Icon } from "lucide-react" // src/blocks/sidebar-02/components/nav-recent.tsx
export { ShareIcon } from "lucide-react" // src/blocks/dashboard-01/page.tsx, src/blocks/fda-card/components/fda-card.tsx, src/blocks/fda-comparison-table/components/fda-columns.tsx
export { SparklesIcon } from "lucide-react" // src/blocks/ai-agent-panel/components/agent-message-list.tsx, src/blocks/shell-01/components/shell-header.tsx
export { StarIcon } from "lucide-react" // src/blocks/sidebar-02/components/nav-recent.tsx
export { TrashIcon } from "lucide-react" // src/blocks/fda-card/components/fda-card.tsx, src/blocks/fda-comparison-table/components/fda-columns.tsx, src/blocks/well-design-card/components/well-design-card.tsx
export { TrendingDownIcon } from "lucide-react" // src/tecton/stat.tsx
export { TrendingUpIcon } from "lucide-react" // src/tecton/stat.tsx
export { WavesIcon } from "lucide-react" // src/blocks/detail-01/components/concept-section.tsx

/** Which identifiers are served by Tecton vs lucide — handy for docs / tests. */
export const tectonLucideCompat = {
  Activity: "pulse",
  ActivityIcon: "pulse",
  AlertCircle: "error",
  AlertCircleIcon: "error",
  AlertTriangle: "warning",
  AlertTriangleIcon: "warning",
  AppWindowIcon: "lucide",
  ArrowDown: "arrow-down",
  ArrowDownIcon: "arrow-down",
  ArrowLeft: "arrow-left",
  ArrowLeftIcon: "arrow-left",
  ArrowRight: "arrow-right",
  ArrowRightIcon: "arrow-right",
  ArrowUp: "arrow-up",
  ArrowUpDown: "sort-enabled",
  ArrowUpDownIcon: "sort-enabled",
  ArrowUpIcon: "arrow-up",
  ArrowUpRightFromSquare: "open-in-new",
  ArrowUpRightFromSquareIcon: "open-in-new",
  BarChart3: "reports-analytics",
  BarChart3Icon: "reports-analytics",
  Bell: "notifications",
  BellIcon: "notifications",
  Bot: "robot-2",
  BotIcon: "robot-2",
  Box: "cube",
  BoxIcon: "cube",
  BoxSelect: "select",
  BoxSelectIcon: "select",
  BugIcon: "lucide",
  BuildingIcon: "lucide",
  ChartColumn: "reports-analytics",
  ChartColumnIcon: "reports-analytics",
  ChartNoAxesCombined: "trend",
  ChartNoAxesCombinedIcon: "trend",
  Check: "check",
  CheckCircle2: "check-circle",
  CheckCircle2Icon: "check-circle",
  CheckIcon: "check",
  CheckSquare2: "checkbox",
  CheckSquare2Icon: "checkbox",
  ChevronDown: "chevron-down",
  ChevronDownIcon: "chevron-down",
  ChevronLeft: "chevron-left",
  ChevronLeftIcon: "chevron-left",
  ChevronRight: "chevron-right",
  ChevronRightIcon: "chevron-right",
  ChevronsDownUp: "caret-collapse",
  ChevronsDownUpIcon: "caret-collapse",
  ChevronsUpDown: "caret-up-down",
  ChevronsUpDownIcon: "caret-up-down",
  ChevronUp: "chevron-up",
  ChevronUpIcon: "chevron-up",
  Circle: "radio-button",
  CircleAlert: "error",
  CircleAlertIcon: "error",
  CircleCheck: "check-circle",
  CircleCheckIcon: "check-circle",
  CircleDashed: "check-circle-open",
  CircleDashedIcon: "check-circle-open",
  CircleHelpIcon: "lucide",
  CircleIcon: "radio-button",
  CircleMinus: "remove-circle",
  CircleMinusIcon: "remove-circle",
  CirclePlus: "add-circle",
  CirclePlusIcon: "add-circle",
  CircleX: "cancel-circle",
  CircleXIcon: "cancel-circle",
  Code: "code",
  CodeIcon: "code",
  Columns: "splitscreen",
  Columns2: "splitscreen",
  Columns2Icon: "splitscreen",
  Columns3: "view-column",
  Columns3Icon: "view-column",
  ColumnsIcon: "splitscreen",
  CommandIcon: "lucide",
  Compass: "discovery",
  CompassIcon: "discovery",
  Copy: "copy",
  CopyIcon: "copy",
  Crown: "crown",
  CrownIcon: "crown",
  Database: "database",
  DatabaseIcon: "database",
  Diamond: "diamond-mark",
  DiamondIcon: "diamond-mark",
  DicesIcon: "lucide",
  DollarSign: "money",
  DollarSignIcon: "money",
  DownloadIcon: "lucide",
  DraftingCompass: "engineering",
  DraftingCompassIcon: "engineering",
  DrillIcon: "lucide",
  Droplet: "water",
  DropletIcon: "water",
  Edit: "edit-square",
  EditIcon: "edit-square",
  EllipsisVertical: "more-vert",
  EllipsisVerticalIcon: "more-vert",
  Expand: "expand-content",
  ExpandIcon: "expand-content",
  ExternalLinkIcon: "lucide",
  Eye: "visibility",
  EyeIcon: "visibility",
  EyeOff: "visibility-off",
  EyeOffIcon: "visibility-off",
  Factory: "facility",
  FactoryIcon: "facility",
  FileTextIcon: "lucide",
  Filter: "filter",
  FilterIcon: "filter",
  Focus: "target",
  FocusIcon: "target",
  Folder: "folder",
  FolderIcon: "folder",
  FolderOpen: "folder-open",
  FolderOpenIcon: "folder-open",
  FolderPlus: "folder-new",
  FolderPlusIcon: "folder-new",
  FoldHorizontal: "swap",
  FoldHorizontalIcon: "swap",
  Funnel: "filter",
  FunnelIcon: "filter",
  GitCompareIcon: "lucide",
  Grid: "view-module",
  Grid2x2: "window",
  Grid2X2: "window",
  Grid2x2Icon: "window",
  Grid2X2Icon: "window",
  Grid3x3: "view-module",
  Grid3X3: "view-module",
  Grid3x3Icon: "view-module",
  Grid3X3Icon: "view-module",
  GridIcon: "view-module",
  Grip: "apps",
  GripIcon: "apps",
  GripVertical: "drag-indicator",
  GripVerticalIcon: "drag-indicator",
  Hand: "pan-tool",
  HandIcon: "pan-tool",
  Hash: "numeric",
  HashIcon: "numeric",
  HexagonIcon: "lucide",
  Highlighter: "annotate",
  HighlighterIcon: "annotate",
  Home: "home",
  HomeIcon: "home",
  House: "home",
  HouseIcon: "home",
  Image: "image",
  ImageIcon: "image",
  Info: "info",
  InfoIcon: "info",
  KanbanSquare: "kanban",
  KanbanSquareIcon: "kanban",
  LassoIcon: "lucide",
  Layers: "layers",
  Layers3: "layers",
  Layers3Icon: "layers",
  LayersIcon: "layers",
  LayoutDashboardIcon: "lucide",
  LayoutGrid: "grid-view",
  LayoutGridIcon: "grid-view",
  LeafIcon: "lucide",
  LifeBuoyIcon: "lucide",
  Link: "link",
  LinkIcon: "link",
  List: "list",
  ListIcon: "list",
  Loader2Icon: "lucide",
  Lock: "lock",
  LockIcon: "lock",
  LockOpen: "lock-open",
  LockOpenIcon: "lock-open",
  LogOutIcon: "lucide",
  LucideActivity: "pulse",
  LucideAlertCircle: "error",
  LucideAlertTriangle: "warning",
  LucideArrowDown: "arrow-down",
  LucideArrowLeft: "arrow-left",
  LucideArrowRight: "arrow-right",
  LucideArrowUp: "arrow-up",
  LucideArrowUpDown: "sort-enabled",
  LucideArrowUpRightFromSquare: "open-in-new",
  LucideBarChart3: "reports-analytics",
  LucideBell: "notifications",
  LucideBot: "robot-2",
  LucideBox: "cube",
  LucideBoxSelect: "select",
  LucideChartColumn: "reports-analytics",
  LucideChartNoAxesCombined: "trend",
  LucideCheck: "check",
  LucideCheckCircle2: "check-circle",
  LucideCheckSquare2: "checkbox",
  LucideChevronDown: "chevron-down",
  LucideChevronLeft: "chevron-left",
  LucideChevronRight: "chevron-right",
  LucideChevronsDownUp: "caret-collapse",
  LucideChevronsUpDown: "caret-up-down",
  LucideChevronUp: "chevron-up",
  LucideCircle: "radio-button",
  LucideCircleAlert: "error",
  LucideCircleCheck: "check-circle",
  LucideCircleDashed: "check-circle-open",
  LucideCircleMinus: "remove-circle",
  LucideCirclePlus: "add-circle",
  LucideCircleX: "cancel-circle",
  LucideCode: "code",
  LucideColumns: "splitscreen",
  LucideColumns2: "splitscreen",
  LucideColumns3: "view-column",
  LucideCompass: "discovery",
  LucideCopy: "copy",
  LucideCrown: "crown",
  LucideDatabase: "database",
  LucideDiamond: "diamond-mark",
  LucideDollarSign: "money",
  LucideDraftingCompass: "engineering",
  LucideDroplet: "water",
  LucideEdit: "edit-square",
  LucideEllipsisVertical: "more-vert",
  LucideExpand: "expand-content",
  LucideEye: "visibility",
  LucideEyeOff: "visibility-off",
  LucideFactory: "facility",
  LucideFilter: "filter",
  LucideFocus: "target",
  LucideFolder: "folder",
  LucideFolderOpen: "folder-open",
  LucideFolderPlus: "folder-new",
  LucideFoldHorizontal: "swap",
  LucideFunnel: "filter",
  LucideGrid: "view-module",
  LucideGrid2x2: "window",
  LucideGrid2X2: "window",
  LucideGrid3x3: "view-module",
  LucideGrid3X3: "view-module",
  LucideGrip: "apps",
  LucideGripVertical: "drag-indicator",
  LucideHand: "pan-tool",
  LucideHash: "numeric",
  LucideHighlighter: "annotate",
  LucideHome: "home",
  LucideHouse: "home",
  LucideImage: "image",
  LucideInfo: "info",
  LucideKanbanSquare: "kanban",
  LucideLayers: "layers",
  LucideLayers3: "layers",
  LucideLayoutGrid: "grid-view",
  LucideLink: "link",
  LucideList: "list",
  LucideLock: "lock",
  LucideLockOpen: "lock-open",
  LucideMap: "map",
  LucideMapPinPlus: "add-pin",
  LucideMenu: "menu",
  LucideMic: "microphone",
  LucideMinimize: "collapse-content",
  LucideMinus: "remove",
  LucideMinusCircle: "remove-circle",
  LucideMinusSquare: "indeterminate-checkbox",
  LucideMoreVertical: "more-vert",
  LucideMousePointer: "select-cursor",
  LucidePanelRight: "panel",
  LucidePanelsLeftRight: "view-column",
  LucidePenBox: "edit-square",
  LucidePencilRuler: "design",
  LucidePenSquare: "edit-square",
  LucidePlay: "play",
  LucidePlus: "add",
  LucidePlusCircle: "add-circle",
  LucideRedo: "redo",
  LucideRotate3d: "rotate",
  LucideRotate3D: "rotate",
  LucideRuler: "ruler",
  LucideScanEye: "preview",
  LucideScanSearch: "inspect",
  LucideSearch: "search",
  LucideSettings: "settings",
  LucideSkull: "risk-skull",
  LucideSlidersHorizontal: "controls",
  LucideSprout: "co-2-leaf",
  LucideSquare: "checkbox-outline-blank",
  LucideSquareArrowOutUpRight: "open-in-new",
  LucideSquareCheck: "checkbox",
  LucideSquareDashed: "select",
  LucideSquareKanban: "kanban",
  LucideSquareMinus: "indeterminate-checkbox",
  LucideSquarePen: "edit-square",
  LucideTriangleAlert: "warning",
  LucideUndo: "undo",
  LucideUnlink: "link-off",
  LucideUnlock: "lock-open",
  LucideUpload: "export-upload",
  LucideUser: "person",
  LucideWaypoints: "node",
  LucideX: "close",
  LucideXCircle: "cancel-circle",
  LucideZap: "electricity",
  LucideZoomIn: "zoom-in",
  LucideZoomOut: "zoom-out",
  Map: "map",
  MapIcon: "map",
  MapPinPlus: "add-pin",
  MapPinPlusIcon: "add-pin",
  Menu: "menu",
  MenuIcon: "menu",
  MessageSquareIcon: "lucide",
  Mic: "microphone",
  MicIcon: "microphone",
  Minimize: "collapse-content",
  MinimizeIcon: "collapse-content",
  Minus: "remove",
  MinusCircle: "remove-circle",
  MinusCircleIcon: "remove-circle",
  MinusIcon: "remove",
  MinusSquare: "indeterminate-checkbox",
  MinusSquareIcon: "indeterminate-checkbox",
  MoreHorizontalIcon: "lucide",
  MoreVertical: "more-vert",
  MoreVerticalIcon: "more-vert",
  MountainIcon: "lucide",
  MousePointer: "select-cursor",
  MousePointer2Icon: "lucide",
  MousePointerIcon: "select-cursor",
  OctagonXIcon: "lucide",
  PaletteIcon: "lucide",
  PanelLeftIcon: "lucide",
  PanelRight: "panel",
  PanelRightCloseIcon: "lucide",
  PanelRightIcon: "panel",
  PanelRightOpenIcon: "lucide",
  PanelsLeftRight: "view-column",
  PanelsLeftRightIcon: "view-column",
  PaperclipIcon: "lucide",
  PenBox: "edit-square",
  PenBoxIcon: "edit-square",
  PencilIcon: "lucide",
  PencilRuler: "design",
  PencilRulerIcon: "design",
  PenSquare: "edit-square",
  PenSquareIcon: "edit-square",
  Play: "play",
  PlayIcon: "play",
  Plus: "add",
  PlusCircle: "add-circle",
  PlusCircleIcon: "add-circle",
  PlusIcon: "add",
  Redo: "redo",
  RedoIcon: "redo",
  Rotate3d: "rotate",
  Rotate3D: "rotate",
  Rotate3dIcon: "rotate",
  Rotate3DIcon: "rotate",
  RotateCcwIcon: "lucide",
  Ruler: "ruler",
  RulerIcon: "ruler",
  ScanEye: "preview",
  ScanEyeIcon: "preview",
  ScanIcon: "lucide",
  ScanSearch: "inspect",
  ScanSearchIcon: "inspect",
  Search: "search",
  SearchIcon: "search",
  Settings: "settings",
  SettingsIcon: "settings",
  Share2Icon: "lucide",
  ShareIcon: "lucide",
  Skull: "risk-skull",
  SkullIcon: "risk-skull",
  SlidersHorizontal: "controls",
  SlidersHorizontalIcon: "controls",
  SparklesIcon: "lucide",
  Sprout: "co-2-leaf",
  SproutIcon: "co-2-leaf",
  Square: "checkbox-outline-blank",
  SquareArrowOutUpRight: "open-in-new",
  SquareArrowOutUpRightIcon: "open-in-new",
  SquareCheck: "checkbox",
  SquareCheckIcon: "checkbox",
  SquareDashed: "select",
  SquareDashedIcon: "select",
  SquareIcon: "checkbox-outline-blank",
  SquareKanban: "kanban",
  SquareKanbanIcon: "kanban",
  SquareMinus: "indeterminate-checkbox",
  SquareMinusIcon: "indeterminate-checkbox",
  SquarePen: "edit-square",
  SquarePenIcon: "edit-square",
  StarIcon: "lucide",
  TrashIcon: "lucide",
  TrendingDownIcon: "lucide",
  TrendingUpIcon: "lucide",
  TriangleAlert: "warning",
  TriangleAlertIcon: "warning",
  Undo: "undo",
  UndoIcon: "undo",
  Unlink: "link-off",
  UnlinkIcon: "link-off",
  Unlock: "lock-open",
  UnlockIcon: "lock-open",
  Upload: "export-upload",
  UploadIcon: "export-upload",
  User: "person",
  UserIcon: "person",
  WavesIcon: "lucide",
  Waypoints: "node",
  WaypointsIcon: "node",
  X: "close",
  XCircle: "cancel-circle",
  XCircleIcon: "cancel-circle",
  XIcon: "close",
  Zap: "electricity",
  ZapIcon: "electricity",
  ZoomIn: "zoom-in",
  ZoomInIcon: "zoom-in",
  ZoomOut: "zoom-out",
  ZoomOutIcon: "zoom-out",
} as const
