/**
 * lucide-compat — a drop-in replacement for the `lucide-react` module surface.
 *
 * The shadcn-generated components in `src/components/` import this module by
 * name: the registry mirror rewrites the import the shadcn CLI would have
 * written to `lucide-react` (scripts/registry-mirror/icon-imports.mts), so CLI
 * managed code we do not edit still renders Tecton glyphs. The Tecton layer in
 * `src/tecton/` imports the named components from `@tecton/react/icons`
 * directly and does not go through here at all.
 *
 * Every identifier lucide-react exports is still available (star re-export),
 * and for each one a Tecton icon stands in for, the generated map below shadows
 * it with the Tecton component (`ChevronDownIcon` → `./chevron-down`, …).
 *
 * That makes it a drop-in replacement for the whole `lucide-react` surface, so
 * an **application** whose own code imports lucide names — a synced shadcn
 * example, a block — can alias the package at the bundler and get Tecton glyphs
 * without editing a file.
 *
 * Caveat: the generated map ends with `export * from "lucide-react"`, so a
 * blanket alias would resolve this module to itself (a cycle). Scope the alias
 * to importers outside `src/icons/` (`dist/icons/` in a published build). With
 * Vite:
 *
 *   {
 *     name: "tecton-lucide-compat",
 *     enforce: "pre",
 *     async resolveId(source, importer) {
 *       if (source !== "lucide-react" || !importer) return null
 *       if (/[\\/]tecton-react[\\/](?:src|dist)[\\/]icons[\\/]/.test(importer)) return null
 *       const r = await this.resolve("@tecton/react/icons/lucide-compat", importer, { skipSelf: true })
 *       return r?.id ?? null
 *     },
 *   }
 *
 * `apps/www/vite.config.ts` in this repository is that plugin.
 *
 * `src/icons/lucide-compat.map.ts` is regenerated by `pnpm icons:build`
 * (scripts/build-icons.mts) — it scans `src/components` and `src/tecton` for the
 * identifiers imported from here (or from `lucide-react`) and pairs each with
 * the Tecton icon that stands in for it. This file is hand-written and stable.
 */
export * from "./lucide-compat.map"
