"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `mail` (U+E159), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** MailIcon — envelope */
export const MailIcon = tectonIcon("mail")
