// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Map` (manifest: lucide: "map").
// Drop icons-src/outlined/map.svg in place and re-run `pnpm icons:build`.
import { Map as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** MapIcon — folded map */
export function MapIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="map"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
MapIcon.displayName = "MapIcon"
