"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `map` (U+E55B), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** MapIcon — folded map */
export const MapIcon = tectonIcon("map")
