// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `DollarSign` (manifest: lucide: "dollar-sign").
// Drop icons-src/outlined/money.svg in place and re-run `pnpm icons:build`.
import { DollarSign as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** MoneyIcon — dollar sign */
export function MoneyIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="money"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
MoneyIcon.displayName = "MoneyIcon"
