"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `monitor` (U+EF5B), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** MonitorIcon — display on a stand */
export const MonitorIcon = tectonIcon("monitor")
