// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Waypoints` (manifest: lucide: "waypoints").
// Drop icons-src/outlined/node.svg in place and re-run `pnpm icons:build`.
import { Waypoints as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** NodeIcon — three circle nodes connected by lines */
export function NodeIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="node"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
NodeIcon.displayName = "NodeIcon"
