"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100050 outlined, U+100850 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** NodeIcon — three circle nodes connected by lines */
export const NodeIcon = tectonIcon("node")
