// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Bell` (manifest: lucide: "bell").
// Drop icons-src/outlined/notifications.svg in place and re-run `pnpm icons:build`.
import { Bell as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** NotificationsIcon — bell */
export function NotificationsIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="notifications"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
NotificationsIcon.displayName = "NotificationsIcon"
