"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `notifications_active` (U+E7F7), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** NotificationsActiveIcon — bell with motion lines */
export const NotificationsActiveIcon = tectonIcon("notifications-active")
