// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Hash` (manifest: lucide: "hash").
// Drop icons-src/outlined/numeric.svg in place and re-run `pnpm icons:build`.
import { Hash as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** NumericIcon — hash / number sign */
export function NumericIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="numeric"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
NumericIcon.displayName = "NumericIcon"
