"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100053 outlined, U+100853 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** OilRigOffshoreIcon — offshore platform: derrick on deck over water */
export const OilRigOffshoreIcon = tectonIcon("oil-rig-offshore")
