"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `open_in_full` (U+F1CE), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** OpenInFullIcon — two diagonal arrows pointing apart */
export const OpenInFullIcon = tectonIcon("open-in-full")
