"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `palette` (U+E40A), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** PaletteIcon — painter's palette with wells */
export const PaletteIcon = tectonIcon("palette")
