// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Hand` (manifest: lucide: "hand").
// Drop icons-src/outlined/pan-tool.svg in place and re-run `pnpm icons:build`.
import { Hand as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** PanToolIcon — open hand */
export function PanToolIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="pan-tool"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
PanToolIcon.displayName = "PanToolIcon"
