// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/pan-tool.ts (outline)
//   filled: icons-src/tecton/pan-tool.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** PanToolIcon — open hand */
export function PanToolIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="pan-tool"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M6.63334 13.9835C6.361 13.9835 6.10123 13.9252 5.854 13.8085C5.60689 13.6918 5.39445 13.5224 5.21667 13.3002L0.983337 8.11683L1.38334 7.6835C1.59445 7.46127 1.85556 7.34183 2.16667 7.32516C2.47778 7.3085 2.76112 7.39461 3.01667 7.5835L4.66667 8.71683V1.8335C4.66667 1.69183 4.71489 1.57305 4.81134 1.47716C4.90767 1.38138 5.02711 1.3335 5.16967 1.3335C5.31211 1.3335 5.43056 1.38138 5.525 1.47716C5.61945 1.57305 5.66667 1.69183 5.66667 1.8335V7.81683H7.45V4.16683C7.45 4.02516 7.49823 3.90638 7.59467 3.8105C7.691 3.71472 7.81045 3.66683 7.953 3.66683C8.09545 3.66683 8.21389 3.71472 8.30834 3.8105C8.40278 3.90638 8.45 4.02516 8.45 4.16683V7.81683H10.2333V5.16683C10.2333 5.02516 10.2816 4.90639 10.378 4.8105C10.4743 4.71472 10.5938 4.66683 10.7363 4.66683C10.8788 4.66683 10.9972 4.71472 11.0917 4.8105C11.1861 4.90639 11.2333 5.02516 11.2333 5.16683V7.81683H13V6.81683C13 6.67516 13.0482 6.55639 13.1447 6.4605C13.241 6.36472 13.3604 6.31683 13.503 6.31683C13.6454 6.31683 13.7639 6.36472 13.8583 6.4605C13.9528 6.55639 14 6.67516 14 6.81683V11.4835C14 12.1835 13.7583 12.7752 13.275 13.2585C12.7917 13.7418 12.2 13.9835 11.5 13.9835H6.63334Z">
          </path>
        </>
      ) : (
        <>
          <path d="M6.63334 13.9835C6.361 13.9835 6.10123 13.9252 5.854 13.8085C5.60689 13.6918 5.39445 13.5224 5.21667 13.3002L0.983337 8.11683L1.38334 7.6835C1.59445 7.46127 1.85556 7.34183 2.16667 7.32516C2.47778 7.3085 2.76112 7.39461 3.01667 7.5835L4.66667 8.71683V1.8335C4.66667 1.69183 4.71489 1.57305 4.81134 1.47716C4.90767 1.38138 5.02711 1.3335 5.16967 1.3335C5.31211 1.3335 5.43056 1.38138 5.525 1.47716C5.61945 1.57305 5.66667 1.69183 5.66667 1.8335V10.6335L2.61667 8.51683L6.01667 12.6835C6.09623 12.7768 6.18906 12.8502 6.29517 12.9035C6.40128 12.9568 6.514 12.9835 6.63334 12.9835H11.5C11.9222 12.9835 12.2778 12.8391 12.5667 12.5502C12.8556 12.2613 13 11.9057 13 11.4835V6.81683C13 6.67516 13.0482 6.55639 13.1447 6.4605C13.241 6.36472 13.3604 6.31683 13.503 6.31683C13.6454 6.31683 13.7639 6.36472 13.8583 6.4605C13.9528 6.55639 14 6.67516 14 6.81683V11.4835C14 12.1835 13.7583 12.7752 13.275 13.2585C12.7917 13.7418 12.2 13.9835 11.5 13.9835H6.63334ZM7.45 8.65016V4.16683C7.45 4.02516 7.49823 3.90638 7.59467 3.8105C7.691 3.71472 7.81045 3.66683 7.953 3.66683C8.09545 3.66683 8.21389 3.71472 8.30834 3.8105C8.40278 3.90638 8.45 4.02516 8.45 4.16683V8.65016H7.45ZM10.2333 8.65016V5.16683C10.2333 5.02516 10.2816 4.90639 10.378 4.8105C10.4743 4.71472 10.5938 4.66683 10.7363 4.66683C10.8788 4.66683 10.9972 4.71472 11.0917 4.8105C11.1861 4.90639 11.2333 5.02516 11.2333 5.16683V8.65016H10.2333Z">
          </path>
        </>
      )}
    </svg>
  )
}
PanToolIcon.displayName = "PanToolIcon"
