"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `dock_to_left` (U+F7E5), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** PanelIcon — rectangle with vertical divider toward the right */
export const PanelIcon = tectonIcon("panel")
