// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `PanelRight` (manifest: lucide: "panel-right").
// Drop icons-src/outlined/panel.svg in place and re-run `pnpm icons:build`.
import { PanelRight as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** PanelIcon — rectangle with vertical divider toward the right */
export function PanelIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="panel"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
PanelIcon.displayName = "PanelIcon"
