// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/panel.ts (outline)
//   filled: icons-src/tecton/panel.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** PanelIcon — rectangle with vertical divider toward the right */
export function PanelIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="panel"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M3.03333 12.9666H9.61666V3.03328H3.03333V12.9666ZM2.075 13.925V2.07495H13.925V13.925H2.075Z">
          </path>
        </>
      ) : (
        <>
          <path d="M10.575 12.9666H12.9667V3.03328H10.575V12.9666ZM3.03333 12.9666H9.61666V3.03328H3.03333V12.9666ZM2.075 13.925V2.07495H13.925V13.925H2.075Z">
          </path>
        </>
      )}
    </svg>
  )
}
PanelIcon.displayName = "PanelIcon"
