// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `User` (manifest: lucide: "user").
// Drop icons-src/outlined/person.svg in place and re-run `pnpm icons:build`.
import { User as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** PersonIcon — person bust */
export function PersonIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="person"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
PersonIcon.displayName = "PersonIcon"
