"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `person_add` (U+EA4D), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** PersonAddIcon — person bust with a plus */
export const PersonAddIcon = tectonIcon("person-add")
