"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `person` (U+F0D3), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** PersonIcon — person bust */
export const PersonIcon = tectonIcon("person")
