// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/person.ts (outline)
//   filled: icons-src/tecton/person.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** PersonIcon — person bust */
export function PersonIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="person"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M6.22499 7.30862C5.76943 6.85329 5.54165 6.26162 5.54165 5.53362C5.54165 4.80562 5.76932 4.21384 6.22465 3.75828C6.67999 3.30273 7.27165 3.07495 7.99965 3.07495C8.72765 3.07495 9.31943 3.30262 9.77499 3.75795C10.2305 4.21328 10.4583 4.80495 10.4583 5.53295C10.4583 6.26095 10.2307 6.85273 9.77532 7.30828C9.31999 7.76384 8.72832 7.99162 8.00032 7.99162C7.27232 7.99162 6.68054 7.76395 6.22499 7.30862ZM2.74165 13.225V11.7083C2.74165 11.2888 2.84582 10.9326 3.05415 10.6396C3.26249 10.3465 3.53143 10.1241 3.86099 9.97228C4.5981 9.64628 5.30276 9.39995 5.97499 9.23328C6.64721 9.06662 7.32221 8.98328 7.99999 8.98328C8.67776 8.98328 9.34999 9.06801 10.0167 9.23745C10.6833 9.4069 11.3861 9.65273 12.125 9.97495C12.4639 10.125 12.7375 10.3469 12.9458 10.6408C13.1542 10.9347 13.2583 11.2918 13.2583 11.7123V13.225H2.74165Z">
          </path>
        </>
      ) : (
        <>
          <path d="M6.22499 7.30862C5.76943 6.85329 5.54165 6.26162 5.54165 5.53362C5.54165 4.80562 5.76932 4.21384 6.22465 3.75828C6.67999 3.30273 7.27165 3.07495 7.99965 3.07495C8.72765 3.07495 9.31943 3.30262 9.77499 3.75795C10.2305 4.21328 10.4583 4.80495 10.4583 5.53295C10.4583 6.26095 10.2307 6.85273 9.77532 7.30828C9.31999 7.76384 8.72832 7.99162 8.00032 7.99162C7.27232 7.99162 6.68054 7.76395 6.22499 7.30862ZM2.74165 13.225V11.7083C2.74165 11.2888 2.84582 10.9326 3.05415 10.6396C3.26249 10.3465 3.53154 10.124 3.86132 9.97212C4.59821 9.64623 5.30276 9.39995 5.97499 9.23328C6.64721 9.06662 7.32221 8.98328 7.99999 8.98328C8.67776 8.98328 9.34999 9.06801 10.0167 9.23745C10.6833 9.4069 11.386 9.65267 12.1247 9.97478C12.4638 10.1249 12.7375 10.3469 12.9458 10.6408C13.1542 10.9347 13.2583 11.2918 13.2583 11.7123V13.225H2.74165ZM3.69999 12.2666H12.3V11.7105C12.3 11.5291 12.2458 11.3571 12.1375 11.1943C12.0292 11.0314 11.9 10.9111 11.75 10.8333C11.0389 10.4944 10.3928 10.2611 9.81182 10.1333C9.23071 10.0055 8.62749 9.94162 8.00215 9.94162C7.37293 9.94162 6.76388 10.0055 6.17499 10.1333C5.5861 10.2611 4.94165 10.4944 4.24165 10.8333C4.0861 10.9111 3.95693 11.0318 3.85415 11.1955C3.75138 11.3591 3.69999 11.5314 3.69999 11.7123V12.2666ZM9.07499 6.60828C9.35832 6.32495 9.49999 5.96662 9.49999 5.53328C9.49999 5.09995 9.35832 4.74162 9.07499 4.45828C8.79165 4.17495 8.43332 4.03328 7.99999 4.03328C7.56665 4.03328 7.20832 4.17495 6.92499 4.45828C6.64165 4.74162 6.49999 5.09995 6.49999 5.53328C6.49999 5.96662 6.64165 6.32495 6.92499 6.60828C7.20832 6.89162 7.56665 7.03328 7.99999 7.03328C8.43332 7.03328 8.79165 6.89162 9.07499 6.60828Z">
          </path>
        </>
      )}
    </svg>
  )
}
PersonIcon.displayName = "PersonIcon"
