"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `play_arrow` (U+E037), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** PlayIcon — right-pointing triangle */
export const PlayIcon = tectonIcon("play")
