// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/project.ts (outline)
//   filled: icons-src/tecton/project.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** ProjectIcon — framed rectangle with angled inner panel */
export function ProjectIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="project"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M1.41667 13.2582V2.74158H14.5833V13.2582H1.41667ZM2.76667 12.2999H13.625V3.69991H10.175L11.7917 9.96658L2.76667 12.2999Z">
          </path>
        </>
      ) : (
        <>
          <path d="M1.41667 13.2582V2.74158H14.5833V13.2582H1.41667ZM2.37501 11.4082L10.6083 9.26658L9.17784 3.69991H2.37501V11.4082ZM2.76667 12.2999H13.625V3.69991H10.175L11.7917 9.96658L2.76667 12.2999Z">
          </path>
        </>
      )}
    </svg>
  )
}
ProjectIcon.displayName = "ProjectIcon"
