"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+10005A outlined, U+10085A filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ProjectIcon — framed rectangle with angled inner panel */
export const ProjectIcon = tectonIcon("project")
