"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+10005B outlined, U+10085B filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** PulseIcon — heartbeat / activity line */
export const PulseIcon = tectonIcon("pulse")
