// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Activity` (manifest: lucide: "activity").
// Drop icons-src/outlined/pulse.svg in place and re-run `pnpm icons:build`.
import { Activity as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** PulseIcon — heartbeat / activity line */
export function PulseIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="pulse"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
PulseIcon.displayName = "PulseIcon"
