// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Circle` (manifest: lucide: "circle").
// Drop icons-src/outlined/radio-button.svg in place and re-run `pnpm icons:build`.
import { Circle as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** RadioButtonIcon — empty circle */
export function RadioButtonIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="radio-button"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
RadioButtonIcon.displayName = "RadioButtonIcon"
