// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/redo.ts (outline)
//   filled: icons-src/tecton/redo.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** RedoIcon — curved arrow to the right */
export function RedoIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="redo"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M6.53335 12.6665C5.4778 12.6665 4.56946 12.3109 3.80835 11.5998C3.04724 10.8887 2.66669 10.0109 2.66669 8.9665C2.66669 7.92206 3.04724 7.04428 3.80835 6.33317C4.56946 5.62206 5.4778 5.2665 6.53335 5.2665H11.4334L9.53335 3.3665L10.2334 2.6665L13.3334 5.7665L10.2334 8.8665L9.53335 8.1665L11.4334 6.2665H6.51669C5.73891 6.2665 5.06946 6.52484 4.50835 7.0415C3.94724 7.55817 3.66669 8.19984 3.66669 8.9665C3.66669 9.73317 3.94724 10.3748 4.50835 10.8915C5.06946 11.4082 5.73891 11.6665 6.51669 11.6665H11.6834V12.6665H6.53335Z">
          </path>
        </>
      ) : (
        <>
          <path d="M6.53331 12.6665C5.47775 12.6665 4.56942 12.3109 3.80831 11.5998C3.0472 10.8887 2.66664 10.0109 2.66664 8.9665C2.66664 7.92206 3.0472 7.04428 3.80831 6.33317C4.56942 5.62206 5.47775 5.2665 6.53331 5.2665H11.4333L9.53331 3.3665L10.2333 2.6665L13.3333 5.7665L10.2333 8.8665L9.53331 8.1665L11.4333 6.2665H6.51664C5.73886 6.2665 5.06942 6.52484 4.50831 7.0415C3.9472 7.55817 3.66664 8.19984 3.66664 8.9665C3.66664 9.73317 3.9472 10.3748 4.50831 10.8915C5.06942 11.4082 5.73886 11.6665 6.51664 11.6665H11.6833V12.6665H6.53331Z">
          </path>
        </>
      )}
    </svg>
  )
}
RedoIcon.displayName = "RedoIcon"
