// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `CircleMinus` (manifest: lucide: "circle-minus").
// Drop icons-src/outlined/remove-circle.svg in place and re-run `pnpm icons:build`.
import { CircleMinus as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** RemoveCircleIcon — circle with minus */
export function RemoveCircleIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="remove-circle"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
RemoveCircleIcon.displayName = "RemoveCircleIcon"
