// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ChartColumn` (manifest: lucide: "chart-column").
// Drop icons-src/outlined/reports-analytics.svg in place and re-run `pnpm icons:build`.
import { ChartColumn as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ReportsAnalyticsIcon — bar chart inside a square */
export function ReportsAnalyticsIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="reports-analytics"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ReportsAnalyticsIcon.displayName = "ReportsAnalyticsIcon"
