"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `right_panel_close` (U+F705), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** RightPanelCloseIcon — frame with the right panel closing */
export const RightPanelCloseIcon = tectonIcon("right-panel-close")
