"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `rotate_right` (U+E41A), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** RotateRightIcon — circular arrow turning clockwise */
export const RotateRightIcon = tectonIcon("rotate-right")
