// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Rotate3d` (manifest: lucide: "rotate-3d").
// Drop icons-src/outlined/rotate.svg in place and re-run `pnpm icons:build`.
import { Rotate3d as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** RotateIcon — curved arrow around a flat ellipse */
export function RotateIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="rotate"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
RotateIcon.displayName = "RotateIcon"
