// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/ruler.ts (outline)
//   filled: icons-src/tecton/ruler.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** RulerIcon — right-triangle set square with tick marks */
export function RulerIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="ruler"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M2.05835 13.9418V1.56677L4.35835 3.86677L3.67502 4.55011L4.12502 5.00011L4.80835 4.31677L6.73335 6.24177L6.05002 6.92511L6.49168 7.36677L7.17502 6.68344L9.12502 8.63344L8.44168 9.31677L8.88335 9.75844L9.56668 9.07511L11.5 11.0084L10.8167 11.6918L11.2584 12.1334L11.9417 11.4501L14.4334 13.9418H2.05835ZM3.35002 12.6501H11.025L3.35002 4.97511V12.6501Z">
      </path>
    </svg>
  )
}
RulerIcon.displayName = "RulerIcon"
