"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100065 outlined, U+100865 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** RulerIcon — right-triangle set square with tick marks */
export const RulerIcon = tectonIcon("ruler")
