// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/search.ts (outline)
//   filled: icons-src/tecton/search.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** SearchIcon — magnifying glass */
export function SearchIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="search"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M13.225 13.9084L8.87533 9.55838C8.54733 9.85283 8.16111 10.0778 7.71666 10.2334C7.27222 10.3889 6.80644 10.4667 6.31933 10.4667C5.13489 10.4667 4.13139 10.0557 3.30883 9.23372C2.48627 8.41183 2.075 7.42016 2.075 6.25872C2.075 5.09738 2.48444 4.1056 3.30333 3.28338C4.12233 2.46116 5.11955 2.05005 6.295 2.05005C7.45944 2.05005 8.45 2.46122 9.26666 3.28355C10.0833 4.10577 10.4917 5.09783 10.4917 6.25972C10.4917 6.73105 10.4139 7.18755 10.2583 7.62922C10.1028 8.07088 9.87222 8.48488 9.56666 8.87122L13.9333 13.2L13.225 13.9084ZM6.3 9.50838C7.19444 9.50838 7.95694 9.19138 8.5875 8.55738C9.21805 7.92338 9.53333 7.15672 9.53333 6.25738C9.53333 5.35805 9.21805 4.59172 8.5875 3.95838C7.95694 3.32505 7.19305 3.00838 6.29583 3.00838C5.3875 3.00838 4.61666 3.32538 3.98333 3.95938C3.35 4.59338 3.03333 5.36005 3.03333 6.25938C3.03333 7.15872 3.35022 7.92505 3.984 8.55838C4.61777 9.19172 5.38978 9.50838 6.3 9.50838Z">
      </path>
    </svg>
  )
}
SearchIcon.displayName = "SearchIcon"
