"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `search` (U+EF7A), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** SearchIcon — magnifying glass */
export const SearchIcon = tectonIcon("search")
