"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+10006A outlined, U+10086A filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** SettingsIcon — gear */
export const SettingsIcon = tectonIcon("settings")
