"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `shapes` (U+E602), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ShapesIcon — overlapping circle, square and triangle */
export const ShapesIcon = tectonIcon("shapes")
