"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `ios_share` (U+E6B8), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ShareIcon — box with an arrow leaving the top */
export const ShareIcon = tectonIcon("share")
