"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `gpp_maybe` (U+F014), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ShieldAlertIcon — shield with an exclamation mark */
export const ShieldAlertIcon = tectonIcon("shield-alert")
