"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `shield` (U+E9E0), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ShieldIcon — shield outline */
export const ShieldIcon = tectonIcon("shield")
