// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/slice.ts (outline)
//   filled: icons-src/tecton/slice.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** SliceIcon — dashed horizontal band between two dotted lines */
export function SliceIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="slice"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M2 2H3V3H2V2Z">
      </path>
      <path d="M2 4.74561H3V5.74561H2V4.74561Z">
      </path>
      <path d="M1 7.49121H15V8.49121H1V7.49121Z">
      </path>
      <path d="M2 10.2368H3V11.2368H2V10.2368Z">
      </path>
      <path d="M2 12.9824H3V13.9824H2V12.9824Z">
      </path>
      <path d="M4.75 2H5.75V3H4.75V2Z">
      </path>
      <path d="M4.75 12.9824H5.75V13.9824H4.75V12.9824Z">
      </path>
      <path d="M7.5 2H8.5V3H7.5V2Z">
      </path>
      <path d="M7.5 12.9824H8.5V13.9824H7.5V12.9824Z">
      </path>
      <path d="M10.25 2H11.25V3H10.25V2Z">
      </path>
      <path d="M10.25 12.9824H11.25V13.9824H10.25V12.9824Z">
      </path>
      <path d="M13 2H14V3H13V2Z">
      </path>
      <path d="M13 4.74561H14V5.74561H13V4.74561Z">
      </path>
      <path d="M13 10.2368H14V11.2368H13V10.2368Z">
      </path>
      <path d="M13 12.9824H14V13.9824H13V12.9824Z">
      </path>
    </svg>
  )
}
SliceIcon.displayName = "SliceIcon"
