"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+10006B outlined, U+10086B filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** SliceIcon — dashed horizontal band between two dotted lines */
export const SliceIcon = tectonIcon("slice")
