// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ArrowUpDown` (manifest: lucide: "arrow-up-down").
// Drop icons-src/outlined/sort-enabled.svg in place and re-run `pnpm icons:build`.
import { ArrowUpDown as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** SortEnabledIcon — paired up and down arrows */
export function SortEnabledIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="sort-enabled"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
SortEnabledIcon.displayName = "SortEnabledIcon"
