// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/splitscreen.ts (outline)
//   filled: icons-src/tecton/splitscreen.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** SplitscreenIcon — two side-by-side panels with small plus */
export function SplitscreenIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="splitscreen"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M2.08333 13.9166V2.08325H7.11666V13.9166H2.08333ZM8.875 13.9166V2.08325H13.9167V10.3916C13.8111 10.3749 13.7037 10.361 13.5945 10.3499C13.4852 10.3388 13.3778 10.3333 13.2723 10.3333C12.462 10.3333 11.7696 10.6191 11.1952 11.1909C10.6206 11.7626 10.3333 12.4575 10.3333 13.2758C10.3333 13.3824 10.3389 13.4895 10.35 13.5969C10.3611 13.7045 10.3778 13.811 10.4 13.9166H8.875ZM12.9583 15.2499V13.9166H11.625V12.9583H12.9583V11.6249H13.9167V12.9583H15.25V13.9166H13.9167V15.2499H12.9583Z">
          </path>
        </>
      ) : (
        <>
          <path d="M12.9583 3.04159H12.9667H10.3417H10.4H9.83333H12.9583ZM8.875 2.08325H13.9167V10.3333H12.9583V3.04159H9.83333V13.9166H8.875V2.08325ZM2.08333 13.9166V2.08325H7.11666V13.9166H2.08333ZM6.15833 3.04159H3.04166V12.9583H6.15833V3.04159ZM12.9583 15.2499V13.9166H11.625V12.9583H12.9583V11.6249H13.9167V12.9583H15.25V13.9166H13.9167V15.2499H12.9583Z">
          </path>
        </>
      )}
    </svg>
  )
}
SplitscreenIcon.displayName = "SplitscreenIcon"
