"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `stacks` (U+F500), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** StacksIcon — stacked rounded cards */
export const StacksIcon = tectonIcon("stacks")
