"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+10006F outlined, U+10086F filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** SurfaceIcon — curved 3D mesh/grid surface */
export const SurfaceIcon = tectonIcon("surface")
