// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `FoldHorizontal` (manifest: lucide: "fold-horizontal").
// Drop icons-src/outlined/swap.svg in place and re-run `pnpm icons:build`.
import { FoldHorizontal as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** SwapIcon — two horizontal arrows pointing toward each other */
export function SwapIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="swap"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
SwapIcon.displayName = "SwapIcon"
