"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `compare_arrows` (U+E915), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** SwapIcon — two horizontal arrows pointing toward each other */
export const SwapIcon = tectonIcon("swap")
