"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `tablet` (U+E32F), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** TabletIcon — tablet outline */
export const TabletIcon = tectonIcon("tablet")
