"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `table` (U+F191), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** TableIcon — grid with a header row */
export const TableIcon = tectonIcon("table")
