"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+100071 outlined, U+100871 filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** TargetIcon — scan corners with circle in center */
export const TargetIcon = tectonIcon("target")
