// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Box` (manifest: lucide: "box").
// Drop icons-src/outlined/three-d.svg in place and re-run `pnpm icons:build`.
import { Box as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ThreeDIcon — isometric cube inside scan corners */
export function ThreeDIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="three-d"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ThreeDIcon.displayName = "ThreeDIcon"
