"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `view_in_ar` (U+EFC9), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ThreeDIcon — isometric cube inside scan corners */
export const ThreeDIcon = tectonIcon("three-d")
