"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `translate` (U+E8E2), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** TranslateIcon — letter A beside a CJK glyph */
export const TranslateIcon = tectonIcon("translate")
