// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/trend.ts (outline)
//   filled: icons-src/tecton/trend.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** TrendIcon — rising line chart over bar columns */
export function TrendIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="trend"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M2 14V12.7333L3 11.7333V14H2ZM4.75 14V10.0667L5.75 9.06667V14H4.75ZM7.5 14V9.06667L8.5 10.0833V14H7.5ZM10.25 14V10.0833L11.25 9.08333V14H10.25ZM13 14V7.4L14 6.4V14H13ZM2 10.0667V8.65L6.66667 4.01667L9.33333 6.68333L14 2V3.41667L9.33333 8.1L6.66667 5.43333L2 10.0667Z">
      </path>
    </svg>
  )
}
TrendIcon.displayName = "TrendIcon"
