// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Undo` (manifest: lucide: "undo").
// Drop icons-src/outlined/undo.svg in place and re-run `pnpm icons:build`.
import { Undo as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** UndoIcon — curved arrow to the left */
export function UndoIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="undo"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
UndoIcon.displayName = "UndoIcon"
