"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `undo` (U+E166), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** UndoIcon — curved arrow to the left */
export const UndoIcon = tectonIcon("undo")
