// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/undo.ts (outline)
//   filled: icons-src/tecton/undo.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** UndoIcon — curved arrow to the left */
export function UndoIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="undo"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M4.31667 12.6665V11.6665H9.48334C10.2611 11.6665 10.9306 11.4082 11.4917 10.8915C12.0528 10.3748 12.3333 9.73317 12.3333 8.9665C12.3333 8.19984 12.0528 7.55817 11.4917 7.0415C10.9306 6.52484 10.2611 6.2665 9.48334 6.2665H4.56667L6.46667 8.1665L5.76667 8.8665L2.66667 5.7665L5.76667 2.6665L6.46667 3.3665L4.56667 5.2665H9.46667C10.5222 5.2665 11.4306 5.62206 12.1917 6.33317C12.9528 7.04428 13.3333 7.92206 13.3333 8.9665C13.3333 10.0109 12.9528 10.8887 12.1917 11.5998C11.4306 12.3109 10.5222 12.6665 9.46667 12.6665H4.31667Z">
          </path>
        </>
      ) : (
        <>
          <path d="M4.31664 12.6665V11.6665H9.48331C10.2611 11.6665 10.9305 11.4082 11.4916 10.8915C12.0528 10.3748 12.3333 9.73317 12.3333 8.9665C12.3333 8.19984 12.0528 7.55817 11.4916 7.0415C10.9305 6.52484 10.2611 6.2665 9.48331 6.2665H4.56664L6.46664 8.1665L5.76664 8.8665L2.66664 5.7665L5.76664 2.6665L6.46664 3.3665L4.56664 5.2665H9.46664C10.5222 5.2665 11.4305 5.62206 12.1916 6.33317C12.9528 7.04428 13.3333 7.92206 13.3333 8.9665C13.3333 10.0109 12.9528 10.8887 12.1916 11.5998C11.4305 12.3109 10.5222 12.6665 9.46664 12.6665H4.31664Z">
          </path>
        </>
      )}
    </svg>
  )
}
UndoIcon.displayName = "UndoIcon"
