"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `verified` (U+EF76), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** VerifiedIcon — scalloped badge with a check mark */
export const VerifiedIcon = tectonIcon("verified")
