// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Grid3x3` (manifest: lucide: "grid-3x3").
// Drop icons-src/outlined/view-module.svg in place and re-run `pnpm icons:build`.
import { Grid3x3 as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ViewModuleIcon — rectangle split into 3x2 grid of cells */
export function ViewModuleIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="view-module"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ViewModuleIcon.displayName = "ViewModuleIcon"
