"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `view_column` (U+E8EC), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ViewColumnIcon — rectangle split into three vertical columns */
export const ViewColumnIcon = tectonIcon("view-column")
