"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `view_module` (U+E8F0), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ViewModuleIcon — rectangle split into 3x2 grid of cells */
export const ViewModuleIcon = tectonIcon("view-module")
