// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `EyeOff` (manifest: lucide: "eye-off").
// Drop icons-src/outlined/visibility-off.svg in place and re-run `pnpm icons:build`.
import { EyeOff as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** VisibilityOffIcon — eye with diagonal strike */
export function VisibilityOffIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="visibility-off"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
VisibilityOffIcon.displayName = "VisibilityOffIcon"
