// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/warning.ts (outline)
//   filled: icons-src/tecton/warning.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** WarningIcon — triangle with exclamation mark */
export function WarningIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="warning"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M0.666672 14.0002L8.00001 1.3335L15.3333 14.0002H0.666672ZM8.42501 11.9055C8.51945 11.8092 8.56667 11.6897 8.56667 11.5472C8.56667 11.4047 8.51845 11.2863 8.42201 11.1918C8.32567 11.0974 8.20623 11.0502 8.06367 11.0502C7.92123 11.0502 7.80278 11.0984 7.70834 11.1948C7.61389 11.2912 7.56667 11.4106 7.56667 11.5532C7.56667 11.6956 7.61489 11.8141 7.71134 11.9085C7.80767 12.0029 7.92712 12.0502 8.06967 12.0502C8.21212 12.0502 8.33056 12.0019 8.42501 11.9055ZM7.56667 10.2002H8.56667V6.46683H7.56667V10.2002Z">
          </path>
        </>
      ) : (
        <>
          <path d="M0.666656 14.0002L7.99999 1.3335L15.3333 14.0002H0.666656ZM2.39999 13.0002H13.6L7.99999 3.3335L2.39999 13.0002ZM8.42499 11.9055C8.51943 11.8092 8.56666 11.6897 8.56666 11.5472C8.56666 11.4047 8.51844 11.2863 8.42199 11.1918C8.32566 11.0974 8.20621 11.0502 8.06366 11.0502C7.92121 11.0502 7.80277 11.0984 7.70832 11.1948C7.61388 11.2912 7.56666 11.4106 7.56666 11.5532C7.56666 11.6956 7.61488 11.8141 7.71132 11.9085C7.80766 12.0029 7.9271 12.0502 8.06966 12.0502C8.2121 12.0502 8.33055 12.0019 8.42499 11.9055ZM7.56666 10.2002H8.56666V6.46683H7.56666V10.2002Z">
          </path>
        </>
      )}
    </svg>
  )
}
WarningIcon.displayName = "WarningIcon"
