"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `warning` (U+F083), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** WarningIcon — triangle with exclamation mark */
export const WarningIcon = tectonIcon("warning")
