// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `TriangleAlert` (manifest: lucide: "triangle-alert").
// Drop icons-src/outlined/warning.svg in place and re-run `pnpm icons:build`.
import { TriangleAlert as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** WarningIcon — triangle with exclamation mark */
export function WarningIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="warning"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
WarningIcon.displayName = "WarningIcon"
