"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `web_asset` (U+E069), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** WebAssetIcon — browser window with a title bar */
export const WebAssetIcon = tectonIcon("web-asset")
