"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Tecton's own drawing (U+10007F outlined, U+10087F filled), rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** WellPickIcon — vertical line crossed by a horizontal pick marker with dot */
export const WellPickIcon = tectonIcon("well-pick")
