// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/well-plan.ts (outline)
//   filled: icons-src/tecton/well-plan.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** WellPlanIcon — dotted vertical line with wellhead symbol (planned well) */
export function WellPlanIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="well-plan"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <path d="M5.00002 3.00854H6.00002V7.50854H5.00002V3.00854Z">
      </path>
      <path d="M11 3.00854H12V7.50854H11V3.00854Z">
      </path>
      <path d="M3.54468 3.00854H6.00002V4.00854H3.54468V3.00854Z">
      </path>
      <path d="M11 3.00854H13.5176V4.00854H11V3.00854Z">
      </path>
      <path d="M7.98969 8H8.99399V10H7.99399L7.98969 8Z">
      </path>
      <path d="M7.99399 3.0058H8.99829L8.99399 6H7.98969L7.99399 3.0058Z">
      </path>
      <path d="M8.05893 12H9.06323V14.0422H8.05893V12Z">
      </path>
    </svg>
  )
}
WellPlanIcon.displayName = "WellPlanIcon"
