"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `window` (U+F088), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** WindowIcon — square split into 2x2 panes */
export const WindowIcon = tectonIcon("window")
