// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `Grid2x2` (manifest: lucide: "grid-2x2").
// Drop icons-src/outlined/window.svg in place and re-run `pnpm icons:build`.
import { Grid2x2 as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** WindowIcon — square split into 2x2 panes */
export function WindowIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="window"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
WindowIcon.displayName = "WindowIcon"
