// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ZoomOut` (manifest: lucide: "zoom-out").
// Drop icons-src/outlined/zoom-out.svg in place and re-run `pnpm icons:build`.
import { ZoomOut as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ZoomOutIcon — magnifying glass with minus */
export function ZoomOutIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="zoom-out"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ZoomOutIcon.displayName = "ZoomOutIcon"
