// GENERATED by scripts/build-icons.mts — do not edit
// No SVG source yet — renders lucide-react's `ZoomIn` (manifest: lucide: "zoom-in").
// Drop icons-src/outlined/zoom-in.svg in place and re-run `pnpm icons:build`.
import { ZoomIn as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ZoomInIcon — magnifying glass with plus */
export function ZoomInIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon="zoom-in"
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
ZoomInIcon.displayName = "ZoomInIcon"
