// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/zoom-in.ts (outline)
//   filled: icons-src/tecton/zoom-in.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** ZoomInIcon — magnifying glass with plus */
export function ZoomInIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="zoom-in"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M13.2667 13.9834L8.88332 9.60007C8.54998 9.88895 8.16132 10.114 7.71732 10.2751C7.27332 10.4362 6.80087 10.5167 6.29998 10.5167C5.09821 10.5167 4.0811 10.1001 3.24865 9.26673C2.41621 8.4334 1.99998 7.42784 1.99998 6.25007C1.99998 5.07229 2.41665 4.06673 3.24998 3.2334C4.08332 2.40007 5.09165 1.9834 6.27498 1.9834C7.45832 1.9834 8.46387 2.40007 9.29165 3.2334C10.1194 4.06673 10.5333 5.07312 10.5333 6.25257C10.5333 6.72868 10.4555 7.18895 10.3 7.6334C10.1444 8.07784 9.9111 8.49451 9.59999 8.8834L14 13.2501L13.2667 13.9834ZM6.28332 9.51673C7.1861 9.51673 7.95349 9.19729 8.58548 8.5584C9.21737 7.91951 9.53332 7.15007 9.53332 6.25007C9.53332 5.35007 9.21737 4.58062 8.58548 3.94173C7.95349 3.30284 7.1861 2.9834 6.28332 2.9834C5.37132 2.9834 4.5961 3.30284 3.95765 3.94173C3.31921 4.58062 2.99998 5.35007 2.99998 6.25007C2.99998 7.15007 3.31921 7.91951 3.95765 8.5584C4.5961 9.19729 5.37132 9.51673 6.28332 9.51673ZM5.76665 8.10007V6.7334H4.39998V5.7334H5.76665V4.3834H6.76665V5.7334H8.11665V6.7334H6.76665V8.10007H5.76665Z">
          </path>
        </>
      ) : (
        <>
          <path d="M13.2667 13.9834L8.88333 9.60007C8.55 9.88895 8.16133 10.114 7.71733 10.2751C7.27333 10.4362 6.80089 10.5167 6.3 10.5167C5.09822 10.5167 4.08111 10.1001 3.24867 9.26673C2.41622 8.4334 2 7.42784 2 6.25007C2 5.07229 2.41667 4.06673 3.25 3.2334C4.08333 2.40007 5.09167 1.9834 6.275 1.9834C7.45833 1.9834 8.46389 2.40007 9.29167 3.2334C10.1194 4.06673 10.5333 5.07312 10.5333 6.25257C10.5333 6.72868 10.4556 7.18895 10.3 7.6334C10.1444 8.07784 9.91111 8.49451 9.6 8.8834L14 13.2501L13.2667 13.9834ZM6.28333 9.51673C7.18611 9.51673 7.9535 9.19729 8.5855 8.5584C9.21739 7.91951 9.53333 7.15007 9.53333 6.25007C9.53333 5.35007 9.21739 4.58062 8.5855 3.94173C7.9535 3.30284 7.18611 2.9834 6.28333 2.9834C5.37133 2.9834 4.59611 3.30284 3.95767 3.94173C3.31922 4.58062 3 5.35007 3 6.25007C3 7.15007 3.31922 7.91951 3.95767 8.5584C4.59611 9.19729 5.37133 9.51673 6.28333 9.51673ZM5.76667 8.10007V6.7334H4.4V5.7334H5.76667V4.3834H6.76667V5.7334H8.11667V6.7334H6.76667V8.10007H5.76667Z">
          </path>
        </>
      )}
    </svg>
  )
}
ZoomInIcon.displayName = "ZoomInIcon"
