// GENERATED by scripts/build-icons.mts — do not edit
// Source SVGs:
//   outlined: icons-src/tecton/zoom-out.ts (outline)
//   filled: icons-src/tecton/zoom-out.ts (filled)
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: { fill: "currentColor" },
  filled: { fill: "currentColor" },
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: "0 0 16 16",
  filled: "0 0 16 16",
}

/** The source's own stroke-width — default for the `strokeWidth` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: undefined,
  filled: undefined,
}

/** ZoomOutIcon — magnifying glass with minus */
export function ZoomOutIcon({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon="zoom-out"
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      {variant === "filled" ? (
        <>
          <path d="M13.2667 13.9834L8.88333 9.60007C8.55 9.88895 8.16111 10.114 7.71667 10.2751C7.27222 10.4362 6.8 10.5167 6.3 10.5167C5.1 10.5167 4.08333 10.1001 3.25 9.26673C2.41667 8.4334 2 7.42784 2 6.25007C2 5.07229 2.41667 4.06673 3.25 3.2334C4.08333 2.40007 5.09444 1.9834 6.28333 1.9834C7.46111 1.9834 8.46389 2.40007 9.29167 3.2334C10.1194 4.06673 10.5333 5.07229 10.5333 6.25007C10.5333 6.72784 10.4556 7.18895 10.3 7.6334C10.1444 8.07784 9.91111 8.49451 9.6 8.8834L14 13.2501L13.2667 13.9834ZM6.28333 9.51673C7.18333 9.51673 7.95 9.19729 8.58333 8.5584C9.21667 7.91951 9.53333 7.15007 9.53333 6.25007C9.53333 5.35007 9.21667 4.58062 8.58333 3.94173C7.95 3.30284 7.18333 2.9834 6.28333 2.9834C5.37222 2.9834 4.59722 3.30284 3.95833 3.94173C3.31944 4.58062 3 5.35007 3 6.25007C3 7.15007 3.31944 7.91951 3.95833 8.5584C4.59722 9.19729 5.37222 9.51673 6.28333 9.51673ZM4.58333 6.7334V5.7334H7.93333V6.7334H4.58333Z">
          </path>
        </>
      ) : (
        <>
          <path d="M13.2667 13.9834L8.88335 9.60007C8.55002 9.88895 8.16113 10.114 7.71668 10.2751C7.27224 10.4362 6.80002 10.5167 6.30002 10.5167C5.10002 10.5167 4.08335 10.1001 3.25002 9.26673C2.41668 8.4334 2.00002 7.42784 2.00002 6.25007C2.00002 5.07229 2.41668 4.06673 3.25002 3.2334C4.08335 2.40007 5.09446 1.9834 6.28335 1.9834C7.46113 1.9834 8.4639 2.40007 9.29168 3.2334C10.1195 4.06673 10.5333 5.07229 10.5333 6.25007C10.5333 6.72784 10.4556 7.18895 10.3 7.6334C10.1445 8.07784 9.91113 8.49451 9.60002 8.8834L14 13.2501L13.2667 13.9834ZM6.28335 9.51673C7.18335 9.51673 7.95002 9.19729 8.58335 8.5584C9.21668 7.91951 9.53335 7.15007 9.53335 6.25007C9.53335 5.35007 9.21668 4.58062 8.58335 3.94173C7.95002 3.30284 7.18335 2.9834 6.28335 2.9834C5.37224 2.9834 4.59724 3.30284 3.95835 3.94173C3.31946 4.58062 3.00002 5.35007 3.00002 6.25007C3.00002 7.15007 3.31946 7.91951 3.95835 8.5584C4.59724 9.19729 5.37224 9.51673 6.28335 9.51673ZM4.58335 6.7334V5.7334H7.93335V6.7334H4.58335Z">
          </path>
        </>
      )}
    </svg>
  )
}
ZoomOutIcon.displayName = "ZoomOutIcon"
