"use client"
// GENERATED by scripts/build-icons.mts — do not edit
// Material Symbols Sharp `zoom_out` (U+E900), FILL `variant`, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ZoomOutIcon — magnifying glass with minus */
export const ZoomOutIcon = tectonIcon("zoom-out")
