/**
 * upstream-icons — the icon identifiers upstream writes, translated to Tecton icons.
 *
 * Tecton ships its own icon set and no compatibility layer for anyone else's, so
 * the two places where upstream code crosses into this repository have to
 * translate. Upstream shadcn/ui names icons from the icon libraries it supports:
 * the aria base sources render `<IconPlaceholder … />` with one identifier per
 * library, and the docs examples import identifiers from an icon package. Both
 * are the same vocabulary, so both are translated through this one table.
 *
 * Consumed by:
 *   scripts/registry-mirror/icon-imports.mts   the registry post-build step,
 *                                              which resolves the placeholders
 *                                              to Tecton components before the
 *                                              shadcn CLI ever sees them
 *   apps/www/scripts/sync-upstream-docs.mts    `pnpm docs:sync`, which rewrites
 *                                              the synced examples' and pages'
 *                                              icon imports and identifiers
 *
 * Both fail loudly on an identifier that is not a key here: an upstream bump
 * that reaches for a new icon stops the build with the name to add, rather than
 * silently dropping a glyph. Add the identifier with the Tecton icon that
 * carries the same meaning (`packages/tecton-react/icons/icons.json` is the
 * catalogue; the docs gallery at /docs/icons renders it).
 *
 * The values are Tecton icon slugs; the exported component is the slug in
 * PascalCase with an `Icon` suffix (`close` → `CloseIcon`), which is what
 * `tectonIconExport()` returns and what `@tecton/react/icons` exports.
 */

const ICONS = {
  Activity: "pulse",
  ActivityIcon: "pulse",
  AlertCircle: "error",
  AlertCircleIcon: "error",
  AlertTriangle: "warning",
  AlertTriangleIcon: "warning",
  AppWindow: "web-asset",
  AppWindowIcon: "web-asset",
  Archive: "archive",
  ArchiveIcon: "archive",
  ArrowDown: "arrow-down",
  ArrowDownIcon: "arrow-down",
  ArrowLeft: "arrow-left",
  ArrowLeftIcon: "arrow-left",
  ArrowRight: "arrow-right",
  ArrowRightIcon: "arrow-right",
  ArrowUp: "arrow-up",
  ArrowUpDown: "sort-enabled",
  ArrowUpDownIcon: "sort-enabled",
  ArrowUpIcon: "arrow-up",
  ArrowUpRight: "arrow-outward",
  ArrowUpRightIcon: "arrow-outward",
  AudioLines: "graphic-eq",
  AudioLinesIcon: "graphic-eq",
  AudioWaveform: "airwave",
  AudioWaveformIcon: "airwave",
  BadgeCheck: "verified",
  BadgeCheckIcon: "verified",
  BarChart3: "reports-analytics",
  BarChart3Icon: "reports-analytics",
  Bell: "notifications",
  BellIcon: "notifications",
  BellRing: "notifications-active",
  BellRingIcon: "notifications-active",
  Blocks: "widgets",
  BlocksIcon: "widgets",
  Bluetooth: "bluetooth",
  BluetoothIcon: "bluetooth",
  Bold: "format-bold",
  BoldIcon: "format-bold",
  BookOpen: "menu-book",
  BookOpenCheck: "library-add-check",
  BookOpenCheckIcon: "library-add-check",
  BookOpenIcon: "menu-book",
  Bookmark: "bookmark",
  BookmarkIcon: "bookmark",
  Bot: "robot-2",
  BotIcon: "robot-2",
  Box: "cube",
  BoxIcon: "cube",
  BoxSelect: "select",
  BoxSelectIcon: "select",
  Braces: "data-object",
  BracesIcon: "data-object",
  Bug: "bug-report",
  BugIcon: "bug-report",
  Building: "apartment",
  Building2: "corporate-fare",
  Building2Icon: "corporate-fare",
  BuildingComplex: "corporate-fare",
  BuildingComplexIcon: "corporate-fare",
  BuildingIcon: "apartment",
  Calculator: "calculate",
  CalculatorIcon: "calculate",
  Calendar: "calendar-month",
  CalendarIcon: "calendar-month",
  CalendarPlus: "calendar-add-on",
  CalendarPlusIcon: "calendar-add-on",
  ChartColumn: "reports-analytics",
  ChartColumnIcon: "reports-analytics",
  ChartNoAxesCombined: "trend",
  ChartNoAxesCombinedIcon: "trend",
  ChartPie: "pie-chart",
  ChartPieIcon: "pie-chart",
  Check: "check",
  CheckCircle2: "check-circle",
  CheckCircle2Icon: "check-circle",
  CheckIcon: "check",
  CheckSquare2: "checkbox",
  CheckSquare2Icon: "checkbox",
  ChevronDown: "chevron-down",
  ChevronDownIcon: "chevron-down",
  ChevronLeft: "chevron-left",
  ChevronLeftIcon: "chevron-left",
  ChevronRight: "chevron-right",
  ChevronRightIcon: "chevron-right",
  ChevronUp: "chevron-up",
  ChevronUpIcon: "chevron-up",
  ChevronsDownUp: "caret-collapse",
  ChevronsDownUpIcon: "caret-collapse",
  ChevronsUpDown: "caret-up-down",
  ChevronsUpDownIcon: "caret-up-down",
  Circle: "radio-button",
  CircleAlert: "error",
  CircleAlertIcon: "error",
  CircleCheck: "check-circle",
  CircleCheckIcon: "check-circle",
  CircleDashed: "check-circle-open",
  CircleDashedIcon: "check-circle-open",
  CircleFadingArrowUp: "upgrade",
  CircleFadingArrowUpIcon: "upgrade",
  CircleFadingPlus: "add-circle",
  CircleFadingPlusIcon: "add-circle",
  CircleHelp: "help",
  CircleHelpIcon: "help",
  CircleIcon: "radio-button",
  CircleMinus: "remove-circle",
  CircleMinusIcon: "remove-circle",
  CirclePlus: "add-circle",
  CirclePlusIcon: "add-circle",
  CircleQuestionMark: "help",
  CircleQuestionMarkIcon: "help",
  CircleX: "cancel-circle",
  CircleXIcon: "cancel-circle",
  ClipboardPaste: "content-paste",
  ClipboardPasteIcon: "content-paste",
  Clock: "schedule",
  Clock2: "schedule",
  Clock2Icon: "schedule",
  ClockIcon: "schedule",
  Cloud: "cloud",
  CloudIcon: "cloud",
  CloudOff: "cloud-off",
  CloudOffIcon: "cloud-off",
  Code: "code",
  CodeIcon: "code",
  Columns: "splitscreen",
  Columns2: "splitscreen",
  Columns2Icon: "splitscreen",
  Columns3: "view-column",
  Columns3Icon: "view-column",
  ColumnsIcon: "splitscreen",
  Command: "keyboard-command-key",
  CommandIcon: "keyboard-command-key",
  Compass: "discovery",
  CompassIcon: "discovery",
  Construction: "construction",
  ConstructionIcon: "construction",
  Copy: "copy",
  CopyIcon: "copy",
  CornerDownLeft: "keyboard-return",
  CornerDownLeftIcon: "keyboard-return",
  CreditCard: "credit-card",
  CreditCardIcon: "credit-card",
  Crown: "crown",
  CrownIcon: "crown",
  CurlyBraces: "data-object",
  CurlyBracesIcon: "data-object",
  Database: "database",
  DatabaseIcon: "database",
  Diamond: "diamond-mark",
  DiamondIcon: "diamond-mark",
  Dices: "casino",
  DicesIcon: "casino",
  DollarSign: "money",
  DollarSignIcon: "money",
  Download: "download",
  DownloadIcon: "download",
  DraftingCompass: "engineering",
  DraftingCompassIcon: "engineering",
  Drill: "drill-bit",
  DrillIcon: "drill-bit",
  Droplet: "water",
  DropletIcon: "water",
  Edit: "edit-square",
  EditIcon: "edit-square",
  Ellipsis: "more-horiz",
  EllipsisIcon: "more-horiz",
  EllipsisVertical: "more-vert",
  EllipsisVerticalIcon: "more-vert",
  Expand: "expand-content",
  ExpandIcon: "expand-content",
  ExternalLink: "open-in-new",
  ExternalLinkIcon: "open-in-new",
  Eye: "visibility",
  EyeIcon: "visibility",
  EyeOff: "visibility-off",
  EyeOffIcon: "visibility-off",
  FaceSlightlySmiling: "sentiment-satisfied",
  FaceSlightlySmilingIcon: "sentiment-satisfied",
  Factory: "facility",
  FactoryIcon: "facility",
  File: "draft",
  FileCode: "code-blocks",
  FileCodeIcon: "code-blocks",
  FileExclamationPoint: "warning",
  FileExclamationPointIcon: "warning",
  FileIcon: "draft",
  FileSearch: "find-in-page",
  FileSearchIcon: "find-in-page",
  FileText: "description",
  FileTextIcon: "description",
  FileWarning: "warning",
  FileWarningIcon: "warning",
  Filter: "filter",
  FilterIcon: "filter",
  Flag: "flag",
  FlagIcon: "flag",
  Focus: "target",
  FocusIcon: "target",
  FoldHorizontal: "swap",
  FoldHorizontalIcon: "swap",
  Folder: "folder",
  FolderCode: "folder-code",
  FolderCodeIcon: "folder-code",
  FolderIcon: "folder",
  FolderInput: "drive-file-move",
  FolderInputIcon: "drive-file-move",
  FolderOpen: "folder-open",
  FolderOpenIcon: "folder-open",
  FolderPlus: "folder-new",
  FolderPlusIcon: "folder-new",
  FolderSearch: "folder-match",
  FolderSearchIcon: "folder-match",
  Forward: "forward",
  ForwardIcon: "forward",
  Frame: "project",
  FrameIcon: "project",
  Fullscreen: "fullscreen",
  FullscreenIcon: "fullscreen",
  Funnel: "filter",
  FunnelIcon: "filter",
  GalleryVerticalEnd: "stacks",
  GalleryVerticalEndIcon: "stacks",
  GitBranch: "account-tree",
  GitBranchIcon: "account-tree",
  GitCompare: "difference",
  GitCompareIcon: "difference",
  GitFork: "fork-right",
  GitForkIcon: "fork-right",
  Globe: "public",
  GlobeIcon: "public",
  Grid: "view-module",
  Grid2X2: "window",
  Grid2X2Icon: "window",
  Grid2x2: "window",
  Grid2x2Icon: "window",
  Grid3X3: "view-module",
  Grid3X3Icon: "view-module",
  Grid3x3: "view-module",
  Grid3x3Icon: "view-module",
  GridIcon: "view-module",
  Grip: "apps",
  GripIcon: "apps",
  GripVertical: "drag-indicator",
  GripVerticalIcon: "drag-indicator",
  Hand: "pan-tool",
  HandIcon: "pan-tool",
  Hash: "numeric",
  HashIcon: "numeric",
  HelpCircle: "help",
  HelpCircleIcon: "help",
  Hexagon: "hexagon",
  HexagonIcon: "hexagon",
  Highlighter: "annotate",
  HighlighterIcon: "annotate",
  History: "history",
  HistoryIcon: "history",
  Home: "home",
  HomeIcon: "home",
  House: "home",
  HouseIcon: "home",
  Image: "image",
  ImageIcon: "image",
  Inbox: "inbox",
  InboxIcon: "inbox",
  Info: "info",
  InfoIcon: "info",
  Italic: "format-italic",
  ItalicIcon: "format-italic",
  KanbanSquare: "kanban",
  KanbanSquareIcon: "kanban",
  Keyboard: "keyboard",
  KeyboardIcon: "keyboard",
  Languages: "translate",
  LanguagesIcon: "translate",
  Lasso: "lasso-select",
  LassoIcon: "lasso-select",
  Layers: "layers",
  Layers3: "layers",
  Layers3Icon: "layers",
  LayersIcon: "layers",
  Layout: "space-dashboard",
  LayoutDashboard: "dashboard",
  LayoutDashboardIcon: "dashboard",
  LayoutGrid: "grid-view",
  LayoutGridIcon: "grid-view",
  LayoutIcon: "space-dashboard",
  Leaf: "eco",
  LeafIcon: "eco",
  LifeBuoy: "support",
  LifeBuoyIcon: "support",
  Link: "link",
  LinkIcon: "link",
  List: "list",
  ListFilter: "filter-list",
  ListFilterIcon: "filter-list",
  ListIcon: "list",
  Loader: "progress-activity",
  Loader2: "progress-activity",
  Loader2Icon: "progress-activity",
  LoaderCircle: "progress-activity",
  LoaderCircleIcon: "progress-activity",
  LoaderIcon: "progress-activity",
  Lock: "lock",
  LockIcon: "lock",
  LockOpen: "lock-open",
  LockOpenIcon: "lock-open",
  LogIn: "login",
  LogInIcon: "login",
  LogOut: "logout",
  LogOutIcon: "logout",
  Mail: "mail",
  MailCheck: "mark-email-read",
  MailCheckIcon: "mark-email-read",
  MailIcon: "mail",
  Map: "map",
  MapIcon: "map",
  MapPin: "location-on",
  MapPinIcon: "location-on",
  MapPinPlus: "add-pin",
  MapPinPlusIcon: "add-pin",
  Maximize: "expand-content",
  Maximize2: "open-in-full",
  Maximize2Icon: "open-in-full",
  MaximizeIcon: "expand-content",
  Menu: "menu",
  MenuIcon: "menu",
  MessageSquare: "chat",
  MessageSquareIcon: "chat",
  Mic: "microphone",
  MicIcon: "microphone",
  Minimize: "collapse-content",
  MinimizeIcon: "collapse-content",
  Minus: "remove",
  MinusCircle: "remove-circle",
  MinusCircleIcon: "remove-circle",
  MinusIcon: "remove",
  MinusSquare: "indeterminate-checkbox",
  MinusSquareIcon: "indeterminate-checkbox",
  Monitor: "monitor",
  MonitorIcon: "monitor",
  Moon: "dark-mode",
  MoonIcon: "dark-mode",
  MoreHorizontal: "more-horiz",
  MoreHorizontalIcon: "more-horiz",
  MoreVertical: "more-vert",
  MoreVerticalIcon: "more-vert",
  Mountain: "terrain",
  MountainIcon: "terrain",
  MousePointer: "select-cursor",
  MousePointer2: "select-cursor",
  MousePointer2Icon: "select-cursor",
  MousePointerIcon: "select-cursor",
  OctagonX: "dangerous",
  OctagonXIcon: "dangerous",
  Palette: "palette",
  PaletteIcon: "palette",
  PanelLeft: "panel-left",
  PanelLeftIcon: "panel-left",
  PanelLeftOpen: "left-panel-open",
  PanelLeftOpenIcon: "left-panel-open",
  PanelRight: "panel",
  PanelRightClose: "right-panel-close",
  PanelRightCloseIcon: "right-panel-close",
  PanelRightIcon: "panel",
  PanelRightOpen: "right-panel-open",
  PanelRightOpenIcon: "right-panel-open",
  PanelsLeftRight: "view-column",
  PanelsLeftRightIcon: "view-column",
  PanelsTopLeft: "space-dashboard",
  PanelsTopLeftIcon: "space-dashboard",
  Paperclip: "attach-file",
  PaperclipIcon: "attach-file",
  PenBox: "edit-square",
  PenBoxIcon: "edit-square",
  PenSquare: "edit-square",
  PenSquareIcon: "edit-square",
  Pencil: "edit-square",
  PencilIcon: "edit-square",
  PencilRuler: "design",
  PencilRulerIcon: "design",
  PieChart: "pie-chart",
  PieChartIcon: "pie-chart",
  Pin: "push-pin",
  PinIcon: "push-pin",
  Play: "play",
  PlayIcon: "play",
  Plus: "add",
  PlusCircle: "add-circle",
  PlusCircleIcon: "add-circle",
  PlusIcon: "add",
  Redo: "redo",
  RedoIcon: "redo",
  RefreshCcw: "sync",
  RefreshCcwIcon: "sync",
  RefreshCw: "sync",
  RefreshCwIcon: "sync",
  Rotate3D: "rotate",
  Rotate3DIcon: "rotate",
  Rotate3d: "rotate",
  Rotate3dIcon: "rotate",
  RotateCcw: "rotate-left",
  RotateCcwClock: "history",
  RotateCcwClockIcon: "history",
  RotateCcwIcon: "rotate-left",
  RotateCw: "rotate-right",
  RotateCwIcon: "rotate-right",
  Ruler: "ruler",
  RulerIcon: "ruler",
  Save: "save",
  SaveIcon: "save",
  Scan: "crop-free",
  ScanEye: "preview",
  ScanEyeIcon: "preview",
  ScanIcon: "crop-free",
  ScanSearch: "inspect",
  ScanSearchIcon: "inspect",
  Scissors: "content-cut",
  ScissorsIcon: "content-cut",
  Search: "search",
  SearchIcon: "search",
  SearchX: "search-off",
  SearchXIcon: "search-off",
  Send: "send",
  SendIcon: "send",
  Settings: "settings",
  Settings2: "controls",
  Settings2Icon: "controls",
  SettingsIcon: "settings",
  Shapes: "shapes",
  ShapesIcon: "shapes",
  Share: "share",
  Share2: "share-nodes",
  Share2Icon: "share-nodes",
  ShareIcon: "share",
  Shield: "shield",
  ShieldAlert: "shield-alert",
  ShieldAlertIcon: "shield-alert",
  ShieldIcon: "shield",
  Sidebar: "panel-left",
  SidebarIcon: "panel-left",
  SidebarOpen: "left-panel-open",
  SidebarOpenIcon: "left-panel-open",
  Skull: "risk-skull",
  SkullIcon: "risk-skull",
  SlidersHorizontal: "controls",
  SlidersHorizontalIcon: "controls",
  Smartphone: "smartphone",
  SmartphoneIcon: "smartphone",
  Smile: "sentiment-satisfied",
  SmileIcon: "sentiment-satisfied",
  Sparkles: "auto-awesome",
  SparklesIcon: "auto-awesome",
  Sprout: "co-2-leaf",
  SproutIcon: "co-2-leaf",
  Square: "checkbox-outline-blank",
  SquareCheck: "checkbox",
  SquareCheckIcon: "checkbox",
  SquareDashed: "select",
  SquareDashedIcon: "select",
  SquareIcon: "checkbox-outline-blank",
  SquareKanban: "kanban",
  SquareKanbanIcon: "kanban",
  SquareMinus: "indeterminate-checkbox",
  SquareMinusIcon: "indeterminate-checkbox",
  SquarePen: "edit-square",
  SquarePenIcon: "edit-square",
  SquareTerminal: "terminal",
  SquareTerminalIcon: "terminal",
  Star: "star",
  StarIcon: "star",
  Stars: "auto-awesome",
  StarsIcon: "auto-awesome",
  Sun: "light-mode",
  SunIcon: "light-mode",
  Table: "table",
  TableIcon: "table",
  Tablet: "tablet",
  TabletIcon: "tablet",
  Tag: "label",
  TagIcon: "label",
  Terminal: "terminal",
  TerminalIcon: "terminal",
  TerminalSquare: "terminal",
  TerminalSquareIcon: "terminal",
  ThumbsDown: "thumb-down",
  ThumbsDownIcon: "thumb-down",
  ThumbsUp: "thumb-up",
  ThumbsUpIcon: "thumb-up",
  Trash: "delete",
  Trash2: "delete",
  Trash2Icon: "delete",
  TrashIcon: "delete",
  TrendingDown: "trending-down",
  TrendingDownIcon: "trending-down",
  TrendingUp: "trending-up",
  TrendingUpIcon: "trending-up",
  TriangleAlert: "warning",
  TriangleAlertIcon: "warning",
  Type: "text",
  TypeIcon: "text",
  Underline: "format-underlined",
  UnderlineIcon: "format-underlined",
  Undo: "undo",
  UndoIcon: "undo",
  Unlink: "link-off",
  UnlinkIcon: "link-off",
  Unlock: "lock-open",
  UnlockIcon: "lock-open",
  Upload: "export-upload",
  UploadIcon: "export-upload",
  User: "person",
  User2: "person",
  User2Icon: "person",
  UserIcon: "person",
  UserPlus: "person-add",
  UserPlusIcon: "person-add",
  UserRound: "person",
  UserRoundIcon: "person",
  UserRoundX: "person-remove",
  UserRoundXIcon: "person-remove",
  UserX2: "person-remove",
  UserX2Icon: "person-remove",
  Verified: "verified",
  VerifiedIcon: "verified",
  VolumeOff: "volume-off",
  VolumeOffIcon: "volume-off",
  Wallet: "wallet",
  WalletIcon: "wallet",
  Waves: "frameworks",
  WavesHorizontal: "frameworks",
  WavesHorizontalIcon: "frameworks",
  WavesIcon: "frameworks",
  Waypoints: "node",
  WaypointsIcon: "node",
  Wrench: "build",
  WrenchIcon: "build",
  X: "close",
  XCircle: "cancel-circle",
  XCircleIcon: "cancel-circle",
  XIcon: "close",
  XOctagon: "dangerous",
  XOctagonIcon: "dangerous",
  Zap: "electricity",
  ZapIcon: "electricity",
  ZoomIn: "zoom-in",
  ZoomInIcon: "zoom-in",
  ZoomOut: "zoom-out",
  ZoomOutIcon: "zoom-out",
} as const

/** A Tecton icon: the `slug` of an entry in packages/tecton-react/icons/icons.json. */
export type TectonIconName = (typeof ICONS)[keyof typeof ICONS]

/** Upstream identifier → the Tecton icon that replaces it. */
export const UPSTREAM_ICONS: Record<string, TectonIconName> = ICONS

/** Every Tecton icon this table names, for a manifest cross-check. */
export const TECTON_ICON_NAMES: readonly TectonIconName[] = [
  ...new Set(Object.values(ICONS)),
].sort() as TectonIconName[]

/**
 * `close` → `CloseIcon`: the identifier `@tecton/react/icons` exports for a
 * slug. Every manifest entry's `label` is exactly this, which
 * `verifyAgainstManifest()` re-checks.
 */
export function tectonIconExport(name: TectonIconName): string {
  return (
    name
      .split(/[-_\s]+/)
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("") + "Icon"
  )
}

/** The Tecton icon for an upstream identifier, or a hard failure naming it. */
export function tectonIconFor(identifier: string, where: string): TectonIconName {
  const name = UPSTREAM_ICONS[identifier]
  if (!name) {
    throw new Error(
      `${where}: no Tecton icon for the upstream identifier "${identifier}" — ` +
        "add it to scripts/upstream-icons.mts (the catalogue is packages/tecton-react/icons/icons.json)",
    )
  }
  return name
}

/** The `@tecton/react/icons` export for an upstream identifier. */
export function tectonIconImportFor(identifier: string, where: string): string {
  return tectonIconExport(tectonIconFor(identifier, where))
}

/**
 * Check every value against `packages/tecton-react/icons/icons.json` (parsed by
 * the caller, which is the side that can reach the file): a slug that has been
 * renamed or removed shows up here rather than as a missing export at build
 * time.
 */
export function verifyAgainstManifest(
  manifest: { icons: Array<{ slug: string; label: string }> },
  where: string,
): void {
  const labels = new Map(manifest.icons.map((icon) => [icon.slug, icon.label]))
  const problems: string[] = []
  for (const name of TECTON_ICON_NAMES) {
    const label = labels.get(name)
    if (!label) problems.push(`"${name}" is not an icon in icons/icons.json`)
    else if (label !== tectonIconExport(name)) {
      problems.push(`"${name}" is exported as ${label}, not ${tectonIconExport(name)}`)
    }
  }
  if (problems.length) {
    throw new Error(`${where}: scripts/upstream-icons.mts is out of date:\n  ${problems.join("\n  ")}`)
  }
}
