/**
 * agent-build — the search index and the per-component docs behind `tecton search`
 * and `tecton docs` (bin/tecton.mjs).
 *
 *   bun run scripts/agent-build.mts            (pnpm agent:build)
 *   bun run scripts/agent-build.mts --check    (pnpm agent:check — CI)
 *
 * Written:
 *   agent/index.json        one entry per guideline file, per external from
 *                           families.json and per topic skill, plus the query
 *                           vocabulary from guidelines/synonyms.json
 *   agent/docs/<id>.md      what `tecton docs <id>` prints: the guideline body
 *                           with the import line and the resolved "Not for"
 *
 * The CLI ships to applications and runs on plain Node, so everything that
 * needs YAML or the guideline contract happens here and the CLI only reads
 * these files. A `notFor` entry is indexed under the component it points AT:
 * "a transient confirmation → toast" in badge.md is how an agent phrases a
 * search for toast, not for Badge.
 */
/// <reference types="node" />
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import {
  GUIDELINES_DIR,
  PKG_ROOT,
  loadGuidelines,
  modulePathOf,
  renderImportLine,
  resolveReference,
} from "./guidelines-lib.mts"
import type { Catalog, Guideline } from "./guidelines-lib.mts"

const OUT_DIR = path.join(PKG_ROOT, "agent")
const DOCS_DIR = path.join(OUT_DIR, "docs")
const SYNONYMS_FILE = path.join(GUIDELINES_DIR, "synonyms.json")
const ICONS_MANIFEST = path.join(PKG_ROOT, "icons", "icons.json")
const ICONS_SPECIFIER = "@tecton/react/icons"
const GENERATED = "<!-- Generated by `pnpm --filter @tecton/react agent:build` from guidelines/ — do not edit. -->"

/** The hand-written skills served as topics: id -> skill folder. */
const TOPICS: Record<string, { skill: string; title: string }> = {
  rules: { skill: "core", title: "Rules for every file: imports, setup, palette, className, variants, icons" },
  "react-aria": { skill: "react-aria", title: "React Aria props instead of Radix props" },
  theming: { skill: "theming", title: "Colour, tokens, dark and light mode, ThemeRoot, micro-frontends" },
}

/** The glyphs `@tecton/react/icons` exports (the manifest's `domain: true` entries). */
function domainGlyphs(): Array<{ label: string; description: string }> {
  const manifest = JSON.parse(readFileSync(ICONS_MANIFEST, "utf8")) as {
    icons: Array<{ label: string; description: string; domain?: boolean }>
  }
  return manifest.icons
    .filter((icon) => icon.domain)
    .map(({ label, description }) => ({ label, description }))
    .sort((a, b) => a.label.localeCompare(b.label))
}

/** Rough token count; the CLI shows it so an agent can budget what it reads. */
export function estimateTokens(text: string) {
  return Math.ceil(text.length / 4)
}

export type IndexEntry = {
  id: string
  kind: "component" | "external" | "topic"
  name: string
  /** The import line, when the entry is imported from somewhere. */
  import?: string
  family?: string
  summary: string
  /** Searchable text by field; the CLI weights the fields. */
  fields: {
    names: string
    useWhen: string
    routed: string
    do: string
  }
  notFor: Array<{ need: string; id: string }>
  related: string[]
  /** Export name -> id, for `tecton docs SelectItem`. */
  exports: string[]
  /** Other names `tecton docs` accepts: an external documented by this guideline (`toast`). */
  aliases: string[]
  tokens: number
}

function idOfModule(moduleKey: string) {
  return moduleKey.split("/")[1]
}

function slug(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

/** `AlertDialogAction` -> `alert dialog action` */
function splitCamel(name: string) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1 $2").toLowerCase()
}

function stripFrontmatter(text: string) {
  return text.replace(/^---\n[\s\S]*?\n---\n?/, "")
}

/** The id a `use:`/`related:` name points at: a guideline, an external or nothing. */
function targetId(name: string, catalog: Catalog, externalIds: Map<string, string>): string | null {
  const external = externalIds.get(name)
  if (external) return external
  const reference = resolveReference(name, catalog)
  if (reference?.kind === "module") return idOfModule(reference.module)
  return null
}

function renderDoc(
  guideline: Guideline,
  catalog: Catalog,
  externalIds: Map<string, string>
): string {
  const notFor = guideline.meta.notFor.map((entry) => {
    const id = targetId(entry.use, catalog, externalIds)
    return `- ${entry.need} → \`${entry.use}\`${id ? ` (tecton docs ${id})` : ""}`
  })
  const related = guideline.meta.related
    .map((name) => targetId(name, catalog, externalIds))
    .filter((id): id is string => Boolean(id))
  return [
    `# ${guideline.meta.component} — ${modulePathOf(guideline.module)}`,
    "",
    "```tsx",
    renderImportLine(guideline.meta),
    "```",
    "",
    "## Use it when",
    "",
    guideline.sections.useWhen,
    "",
    "## Not for",
    "",
    ...notFor,
    "",
    "## Do",
    "",
    guideline.sections.do,
    "",
    "## Don't",
    "",
    guideline.sections.dont,
    ...(related.length ? ["", `Related: ${[...new Set(related)].join(", ")}`] : []),
    "",
  ].join("\n")
}

function main() {
  const check = process.argv.includes("--check")
  const { catalog, valid, invalid } = loadGuidelines(GUIDELINES_DIR)
  if (invalid.size) {
    for (const file of invalid.keys()) console.error(`✗ ${path.basename(file)} fails guidelines:check`)
    process.exit(1)
  }

  // Externals: `toast` is documented by the sonner guideline, the others stand alone.
  const externalIds = new Map<string, string>()
  const externalDocTarget = new Map<string, string>()
  for (const [name, external] of Object.entries(catalog.families.externals)) {
    const id = slug(name)
    externalIds.set(name, id)
    const docsBase = external.docs.split("/").pop() ?? ""
    const guideline = [...valid.values()].find((g) => idOfModule(g.module) === docsBase)
    if (guideline) externalDocTarget.set(id, idOfModule(guideline.module))
  }

  // Needs routed to the entry they point at.
  const routed = new Map<string, string[]>()
  for (const guideline of valid.values()) {
    for (const entry of guideline.meta.notFor) {
      const id = targetId(entry.use, catalog, externalIds)
      if (!id) continue
      routed.set(id, [...(routed.get(id) ?? []), entry.need])
    }
  }

  const docs = new Map<string, string>()
  const entries: IndexEntry[] = []

  for (const guideline of [...valid.values()].sort((a, b) => a.name.localeCompare(b.name))) {
    const id = idOfModule(guideline.module)
    const doc = renderDoc(guideline, catalog, externalIds)
    docs.set(id, doc)
    entries.push({
      id,
      kind: "component",
      name: guideline.meta.component,
      import: renderImportLine(guideline.meta),
      family: guideline.meta.family,
      summary: guideline.sections.useWhenBullets[0] ?? guideline.meta.component,
      fields: {
        names: [id.replace(/-/g, " "), ...guideline.meta.exports.map(splitCamel)].join(" "),
        useWhen: guideline.sections.useWhenBullets.join(" "),
        routed: (routed.get(id) ?? []).join(" "),
        do: guideline.sections.doBullets.join(" "),
      },
      notFor: guideline.meta.notFor
        .map((entry) => ({ need: entry.need, id: targetId(entry.use, catalog, externalIds) ?? "" }))
        .filter((entry) => entry.id),
      related: guideline.meta.related
        .map((name) => targetId(name, catalog, externalIds))
        .filter((value): value is string => Boolean(value)),
      exports: guideline.meta.exports,
      aliases: [],
      tokens: estimateTokens(doc),
    })
  }

  // An external documented by a guideline (`toast` by sonner.md) folds into that
  // entry, so a search shows it once; the others are entries of their own.
  for (const [name, external] of Object.entries(catalog.families.externals)) {
    const id = externalIds.get(name) as string
    const target = externalDocTarget.get(id)
    const host = target ? entries.find((entry) => entry.id === target) : undefined
    if (host) {
      host.name = `${host.name} + ${name}`
      host.import = `${host.import}\n${external.import}`
      host.aliases.push(id)
      host.fields.names += ` ${name.toLowerCase()}`
      host.fields.routed += ` ${(routed.get(id) ?? []).join(" ")}`
      const doc = [
        (docs.get(target as string) as string).replace(
          /```tsx\n(.*)\n```/,
          (_, line) => `\`\`\`tsx\n${line}\n${external.import}\n\`\`\``
        ),
        ...(external.note ? [external.note, ""] : []),
      ].join("\n")
      docs.set(target as string, doc)
      host.tokens = estimateTokens(doc)
      continue
    }
    const specifier = /from\s+["']([^"']+)["']/.exec(external.import)?.[1] ?? ""
    // `@tecton/react/icons` lists its glyphs, so an agent never guesses a name.
    const glyphs = specifier === ICONS_SPECIFIER ? domainGlyphs() : []
    const doc = [
      `# ${name} — external`,
      "",
      "```tsx",
      external.import,
      "```",
      "",
      ...(external.note ? [external.note, ""] : []),
      ...(glyphs.length
        ? [
            'Every glyph takes the Lucide props plus `variant="outlined" | "filled"`; inside a control it carries `data-icon="inline-start"`.',
            "",
            ...glyphs.map((glyph) => `- \`${glyph.label}\` — ${glyph.description}`),
            "",
          ]
        : []),
      `Docs: ${external.docs}`,
      "",
    ].join("\n")
    docs.set(id, doc)
    // `tecton docs icons` / `tecton docs lucide-react`: the last segment of the specifier
    const alias = specifier.split("/").pop() ?? ""
    entries.push({
      id,
      kind: "external",
      name,
      import: external.import,
      summary: external.note ?? `${name} (${external.import})`,
      fields: {
        names: `${name.toLowerCase()} ${splitCamel(name)} ${glyphs.map((glyph) => splitCamel(glyph.label)).join(" ")}`,
        useWhen: [external.note ?? "", ...glyphs.map((glyph) => glyph.description)].join(" "),
        routed: (routed.get(id) ?? []).join(" "),
        do: "",
      },
      notFor: [],
      related: [],
      exports: glyphs.map((glyph) => glyph.label),
      aliases: alias && alias !== id ? [alias] : [],
      tokens: estimateTokens(doc),
    })
  }

  for (const [id, topic] of Object.entries(TOPICS)) {
    const raw = readFileSync(path.join(PKG_ROOT, "skills", topic.skill, "SKILL.md"), "utf8")
    const description = /^description: >\n((?:  .*\n)+)/m.exec(raw)?.[1].replace(/\s+/g, " ").trim() ?? ""
    const headings = [...stripFrontmatter(raw).matchAll(/^#{2,3} (.*)$/gm)].map((m) => m[1]).join(" ")
    const doc = stripFrontmatter(raw).trim() + "\n"
    docs.set(id, doc)
    entries.push({
      id,
      kind: "topic",
      name: topic.title,
      summary: topic.title,
      fields: { names: `${id.replace(/-/g, " ")} ${topic.skill}`, useWhen: description, routed: "", do: headings },
      notFor: [],
      related: [],
      exports: [],
      aliases: [],
      tokens: estimateTokens(doc),
    })
  }

  // The vocabulary: every expansion has to land somewhere, or the synonym is dead.
  const { synonyms } = JSON.parse(readFileSync(SYNONYMS_FILE, "utf8")) as {
    synonyms: Record<string, string[]>
  }
  const corpus = entries
    .map((entry) => Object.values(entry.fields).join(" "))
    .join(" ")
    .toLowerCase()
  const dead = Object.entries(synonyms).flatMap(([word, targets]) =>
    targets.filter((target) => !corpus.includes(target)).map((target) => `${word} → ${target}`)
  )
  if (dead.length) {
    console.error(`✗ synonyms.json: no entry mentions ${dead.join(", ")}`)
    process.exit(1)
  }

  // `→ toast` in a notFor list reads as `→ sonner` once toast is folded in.
  const folded = new Map([...externalDocTarget])
  for (const entry of entries) {
    for (const item of entry.notFor) item.id = folded.get(item.id) ?? item.id
    entry.related = [...new Set(entry.related.map((id) => folded.get(id) ?? id))]
  }

  const index = {
    $comment: GENERATED,
    package: "@tecton/react",
    version: catalog.version,
    synonyms,
    entries,
  }

  const files = new Map<string, string>([
    [path.join(OUT_DIR, "index.json"), `${JSON.stringify(index, null, 1)}\n`],
    ...[...docs].map(([id, doc]): [string, string] => [
      path.join(DOCS_DIR, `${id}.md`),
      `${GENERATED}\n\n${doc.trimEnd()}\n`,
    ]),
  ])

  const drift: string[] = []
  for (const [file, content] of files) {
    const current = existsSync(file) ? readFileSync(file, "utf8") : null
    if (current === content) continue
    drift.push(path.relative(PKG_ROOT, file))
    if (!check) {
      mkdirSync(path.dirname(file), { recursive: true })
      writeFileSync(file, content)
    }
  }
  if (existsSync(DOCS_DIR)) {
    for (const name of readdirSync(DOCS_DIR)) {
      const file = path.join(DOCS_DIR, name)
      if (files.has(file)) continue
      drift.push(`${path.relative(PKG_ROOT, file)} (no longer generated)`)
      if (!check) rmSync(file)
    }
  }

  const summary = `${entries.length} entries, ${docs.size} docs`
  if (check) {
    if (drift.length) {
      console.error(`agent:check failed — ${drift.length} file(s) differ:`)
      for (const item of drift) console.error(`  ${item}`)
      console.error("  run: pnpm --filter @tecton/react agent:build")
      process.exit(1)
    }
    console.log(`agent: up to date (${summary})`)
    return
  }
  console.log(drift.length ? `agent: wrote ${drift.length} file(s) (${summary})` : `agent: up to date (${summary})`)
}

main()
