/**
 * agent-build — the search index and the per-component docs behind `tecton search`
 * and `tecton docs` (bin/tecton-lib.mjs).
 *
 *   bun run scripts/agent-build.mts            (pnpm agent:build)
 *   bun run scripts/agent-build.mts --check    (pnpm agent:check — CI)
 *
 * Written:
 *   agent/index.json        one entry per guideline file, per external from
 *                           families.json and per page in guidelines/topics/,
 *                           plus the query vocabulary from guidelines/synonyms.json
 *   agent/docs/<id>.md      what `tecton docs <id>` prints: the guideline body
 *                           with the import line, the resolved "Not for" and the
 *                           family checklist items that concern the component
 *   skills/tecton/SKILL.md  only its `library_version` (the package version)
 *
 * Checked, failing the build: each topic's frontmatter (title, description),
 * synonyms.json against the search tokenizer and the index vocabulary, and the
 * skill's "Before you finish" against the rules topic's.
 *
 * The CLI ships to applications and runs on plain Node, so everything that
 * needs YAML or the guideline contract happens here and the CLI only reads
 * these files. A `notFor` entry is indexed under the component it points AT:
 * "a transient confirmation → toast" in badge.md is how an agent phrases a
 * search for toast, not for Badge.
 */
/// <reference types="node" />
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import { tokenize } from "../bin/tecton-lib.mjs"
import {
  GUIDELINES_DIR,
  PKG_ROOT,
  loadGuidelines,
  modulePathOf,
  parseYaml,
  renderImportLine,
  resolveReference,
} from "./guidelines-lib.mts"
import type { Catalog, Guideline } from "./guidelines-lib.mts"

const OUT_DIR = path.join(PKG_ROOT, "agent")
const DOCS_DIR = path.join(OUT_DIR, "docs")
const SYNONYMS_FILE = path.join(GUIDELINES_DIR, "synonyms.json")
const TOPICS_DIR = path.join(GUIDELINES_DIR, "topics")
const SKILL_FILE = path.join(PKG_ROOT, "skills", "tecton", "SKILL.md")
const ICONS_MANIFEST = path.join(PKG_ROOT, "icons", "icons.json")
const ICONS_SPECIFIER = "@tecton/react/icons"
const GENERATED = "<!-- Generated by `pnpm --filter @tecton/react agent:build` from guidelines/ — do not edit. -->"


/** The glyphs `@tecton/react/icons` exports (the manifest's `domain: true` entries). */
function domainGlyphs(): Array<{ label: string; description: string }> {
  const manifest = JSON.parse(readFileSync(ICONS_MANIFEST, "utf8")) as {
    icons: Array<{ label: string; description: string; domain?: boolean }>
  }
  return manifest.icons
    .filter((icon) => icon.domain)
    .map(({ label, description }) => ({ label, description }))
    .sort((a, b) => a.label.localeCompare(b.label))
}

/** Rough token count; the CLI shows it so an agent can budget what it reads. */
export function estimateTokens(text: string) {
  return Math.ceil(text.length / 4)
}

export type IndexEntry = {
  id: string
  kind: "component" | "external" | "topic"
  name: string
  /** The import line, when the entry is imported from somewhere. */
  import?: string
  family?: string
  summary: string
  /** Searchable text by field; the CLI weights the fields. */
  fields: {
    names: string
    useWhen: string
    routed: string
    do: string
  }
  notFor: Array<{ need: string; id: string }>
  related: string[]
  /** Export name -> id, for `tecton docs SelectItem`. */
  exports: string[]
  /** Other names `tecton docs` accepts: an external documented by this guideline (`toast`). */
  aliases: string[]
  tokens: number
}

function idOfModule(moduleKey: string) {
  return moduleKey.split("/")[1]
}

function slug(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

/** `AlertDialogAction` -> `alert dialog action` */
function splitCamel(name: string) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1 $2").toLowerCase()
}

/** A text file with LF line endings, whatever the checkout wrote. */
function readText(file: string) {
  return readFileSync(file, "utf8").replace(/^﻿/, "").replace(/\r\n/g, "\n")
}

const FRONTMATTER = /^---\n([\s\S]*?)\n---\n?/

function stripFrontmatter(text: string) {
  return text.replace(FRONTMATTER, "")
}

/** A topic's `title` and `description`, read with the YAML parser; both are required. */
function topicMeta(file: string, raw: string): { title: string; description: string; errors: string[] } {
  const match = FRONTMATTER.exec(raw)
  const errors: string[] = []
  let meta: Record<string, unknown> = {}
  if (!match) {
    errors.push("no `---` frontmatter block")
  } else {
    try {
      const parsed = parseYaml(match[1])
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) meta = parsed as Record<string, unknown>
      else errors.push("the frontmatter is not a mapping")
    } catch (error) {
      errors.push(`the frontmatter is not valid YAML: ${(error as Error).message}`)
    }
  }
  const field = (key: string) => {
    const value = meta[key]
    if (typeof value === "string" && value.trim()) return value.replace(/\s+/g, " ").trim()
    if (match) errors.push(`"${key}" must be a non-empty string`)
    return ""
  }
  const title = field("title")
  const description = field("description")
  return { title, description, errors: errors.map((error) => `${file}: ${error}`) }
}

/**
 * The query vocabulary, held to what the search does with it: every key and
 * value goes through the search tokenizer. A key keeps all its words (no
 * stopword, nothing the tokenizer drops), no two keys stem to the same words
 * (the later one would silently replace the earlier), a key does not expand
 * only to itself, and every value is one word that some entry uses.
 */
function checkSynonyms(synonyms: Record<string, string[]>, vocabulary: Set<string>): string[] {
  const errors: string[] = []
  const seen = new Map<string, string>()
  for (const [key, targets] of Object.entries(synonyms)) {
    const words = key.trim().split(/\s+/)
    const stems = tokenize(key)
    if (key !== key.toLowerCase() || stems.length !== words.length) {
      errors.push(`"${key}": a key is lowercase words the tokenizer keeps (${words.length} word(s), kept ${stems.length})`)
      continue
    }
    const joined = stems.join(" ")
    const other = seen.get(joined)
    if (other) errors.push(`"${key}" and "${other}" both stem to "${joined}"`)
    seen.set(joined, key)
    if (!Array.isArray(targets) || !targets.length) {
      errors.push(`"${key}": no values`)
      continue
    }
    const targetStems: string[] = []
    for (const target of targets) {
      const [only, ...rest] = tokenize(target)
      if (!only || rest.length) errors.push(`"${key}" → "${target}": a value is one word the tokenizer keeps`)
      else if (!vocabulary.has(only)) errors.push(`"${key}" → "${target}": no entry uses "${only}"`)
      else targetStems.push(only)
    }
    if (stems.length === 1 && targetStems.length && targetStems.every((target) => target === stems[0])) {
      errors.push(`"${key}" expands only to itself`)
    }
  }
  return errors
}

/** The bold leads of the bullets under `## Before you finish`, or null without that section. */
function checklistLeads(text: string): string[] | null {
  const at = text.indexOf("\n## Before you finish\n")
  if (at === -1) return null
  const next = text.indexOf("\n## ", at + 1)
  const section = text.slice(at, next === -1 ? text.length : next)
  return [...section.matchAll(/^- \*\*(.+?)\*\*/gm)].map((match) => match[1])
}

/**
 * The skill ships beside the index and is held to the same sources: its
 * `library_version` is the package version (rewritten here), and every rule in
 * the rules topic's "Before you finish" has its bold lead in the skill's, so a
 * rule added to rules.md cannot miss the skill.
 */
function skillFile(version: string, rulesRaw: string): { content: string; errors: string[] } {
  const current = readText(SKILL_FILE)
  const content = current.replace(/^(\s*library_version:\s*)"[^"]*"/m, `$1"${version}"`)
  const errors: string[] = []
  if (!/^\s*library_version:\s*"/m.test(current)) errors.push('SKILL.md: no `library_version: "…"` in the frontmatter')
  const rules = checklistLeads(stripFrontmatter(rulesRaw))
  const skill = checklistLeads(content)
  if (!rules) errors.push('topics/rules.md: no "## Before you finish" section')
  if (!skill) errors.push('SKILL.md: no "## Before you finish" section')
  for (const lead of rules && skill ? rules.filter((item) => !skill.includes(item)) : []) {
    errors.push(`SKILL.md: "Before you finish" has no "**${lead}**" item, which topics/rules.md has`)
  }
  return { content, errors }
}

/** The id a `use:`/`related:` name points at: a guideline, an external or nothing. */
function targetId(name: string, catalog: Catalog, externalIds: Map<string, string>): string | null {
  const external = externalIds.get(name)
  if (external) return external
  const reference = resolveReference(name, catalog)
  if (reference?.kind === "module") return idOfModule(reference.module)
  return null
}

/** Appends lines at the end of a `## <heading>` section (before the next `## `). */
function appendToSection(doc: string, heading: string, lines: string[]): string {
  const start = doc.indexOf(`\n## ${heading}\n`)
  if (start === -1) throw new Error(`agent-build: no "## ${heading}" section to extend`)
  const next = doc.indexOf("\n## ", start + 1)
  const end = next === -1 ? doc.length : next
  const section = doc.slice(0, end).replace(/\s+$/, "")
  return `${section}\n${lines.join("\n")}\n${doc.slice(end)}`
}

/** The component names an item mentions: every identifier inside its backticks. */
function namesIn(item: string): Set<string> {
  const names = new Set<string>()
  for (const [, code] of item.matchAll(/`([^`]+)`/g)) {
    for (const [name] of code.matchAll(/\b[A-Z][A-Za-z]+\b/g)) names.add(name)
  }
  return names
}

/**
 * The family checklist items that concern one member: those naming one of its
 * exports, plus those naming no member at all (the family-wide rules).
 */
function checklistFor(guideline: Guideline, catalog: Catalog): string[] {
  const family = catalog.families.families[guideline.meta.family]
  const members = new Set(
    family.modules.flatMap((moduleKey) => catalog.guidelines.get(moduleKey)?.meta.exports ?? [])
  )
  const own = new Set(guideline.meta.exports)
  return (family.checklist ?? []).filter((item) => {
    const named = [...namesIn(item)].filter((name) => members.has(name))
    return !named.length || named.some((name) => own.has(name))
  })
}

function renderDoc(
  guideline: Guideline,
  catalog: Catalog,
  externalIds: Map<string, string>
): string {
  // Adopted checklist items (guidelines/adopted/*.json) follow the family's own.
  const checklist = [...checklistFor(guideline, catalog), ...guideline.adopted.checklist]
  const notFor = guideline.meta.notFor.map((entry) => {
    const id = targetId(entry.use, catalog, externalIds)
    return `- ${entry.need} → \`${entry.use}\`${id ? ` (tecton docs ${id})` : ""}`
  })
  const related = guideline.meta.related
    .map((name) => targetId(name, catalog, externalIds))
    .filter((id): id is string => Boolean(id))
  return [
    `# ${guideline.meta.component} — ${modulePathOf(guideline.module)}`,
    "",
    "```tsx",
    renderImportLine(guideline.meta),
    "```",
    "",
    "## Use it when",
    "",
    guideline.sections.useWhen,
    "",
    "## Not for",
    "",
    ...notFor,
    "",
    "## Do",
    "",
    guideline.sections.do,
    "",
    "## Don't",
    "",
    guideline.sections.dont,
    ...(checklist.length
      ? ["", "## Before you finish", "", ...checklist.map((item) => `- ${item}`)]
      : []),
    ...(related.length ? ["", `Related: ${[...new Set(related)].join(", ")}`] : []),
    "",
  ].join("\n")
}

function main() {
  const check = process.argv.includes("--check")
  const { catalog, valid, invalid } = loadGuidelines(GUIDELINES_DIR)
  if (invalid.size) {
    for (const file of invalid.keys()) console.error(`✗ ${path.basename(file)} fails guidelines:check`)
    process.exit(1)
  }

  // Externals: `toast` is documented by the sonner guideline, the others stand alone.
  const externalIds = new Map<string, string>()
  const externalDocTarget = new Map<string, string>()
  for (const [name, external] of Object.entries(catalog.families.externals)) {
    const id = slug(name)
    externalIds.set(name, id)
    const docsBase = external.docs.split("/").pop() ?? ""
    const guideline = [...valid.values()].find((g) => idOfModule(g.module) === docsBase)
    if (guideline) externalDocTarget.set(id, idOfModule(guideline.module))
  }

  // Needs routed to the entry they point at.
  const routed = new Map<string, string[]>()
  for (const guideline of valid.values()) {
    for (const entry of guideline.meta.notFor) {
      const id = targetId(entry.use, catalog, externalIds)
      if (!id) continue
      routed.set(id, [...(routed.get(id) ?? []), entry.need])
    }
  }

  const docs = new Map<string, string>()
  const entries: IndexEntry[] = []

  for (const guideline of [...valid.values()].sort((a, b) => a.name.localeCompare(b.name))) {
    const id = idOfModule(guideline.module)
    const doc = renderDoc(guideline, catalog, externalIds)
    docs.set(id, doc)
    entries.push({
      id,
      kind: "component",
      name: guideline.meta.component,
      import: renderImportLine(guideline.meta),
      family: guideline.meta.family,
      summary: guideline.sections.useWhenBullets[0] ?? guideline.meta.component,
      fields: {
        names: [id.replace(/-/g, " "), ...guideline.meta.exports.map(splitCamel)].join(" "),
        useWhen: guideline.sections.useWhenBullets.join(" "),
        routed: (routed.get(id) ?? []).join(" "),
        // Adopted rules shape how a component is used, not what it is for: keep
        // them out of the ranking so adding or removing a source leaves search alone.
        do: guideline.sections.doBullets.filter((bullet) => !guideline.adopted.do.includes(bullet)).join(" "),
      },
      notFor: guideline.meta.notFor
        .map((entry) => ({ need: entry.need, id: targetId(entry.use, catalog, externalIds) ?? "" }))
        .filter((entry) => entry.id),
      related: guideline.meta.related
        .map((name) => targetId(name, catalog, externalIds))
        .filter((value): value is string => Boolean(value)),
      exports: guideline.meta.exports,
      aliases: [],
      tokens: estimateTokens(doc),
    })
  }

  // An external documented by a guideline (`toast` by sonner.md) folds into that
  // entry, so a search shows it once; the others are entries of their own.
  for (const [name, external] of Object.entries(catalog.families.externals)) {
    const id = externalIds.get(name) as string
    const target = externalDocTarget.get(id)
    const host = target ? entries.find((entry) => entry.id === target) : undefined
    if (host) {
      host.name = `${host.name} + ${name}`
      host.import = `${host.import}\n${external.import}`
      host.aliases.push(id)
      host.fields.names += ` ${name.toLowerCase()}`
      host.fields.routed += ` ${(routed.get(id) ?? []).join(" ")}`
      const doc = [
        (docs.get(target as string) as string).replace(
          /```tsx\n(.*)\n```/,
          (_, line) => `\`\`\`tsx\n${line}\n${external.import}\n\`\`\``
        ),
        ...(external.note ? [external.note, ""] : []),
      ].join("\n")
      docs.set(target as string, doc)
      host.tokens = estimateTokens(doc)
      continue
    }
    const specifier = /from\s+["']([^"']+)["']/.exec(external.import)?.[1] ?? ""
    // `@tecton/react/icons` lists its glyphs, so an agent never guesses a name.
    const glyphs = specifier === ICONS_SPECIFIER ? domainGlyphs() : []
    const doc = [
      `# ${name} — external`,
      "",
      "```tsx",
      external.import,
      "```",
      "",
      ...(external.note ? [external.note, ""] : []),
      ...(glyphs.length
        ? [
            'Every glyph takes the Lucide props plus `variant="outlined" | "filled"`; inside a control it carries `data-icon="inline-start"`.',
            "",
            ...glyphs.map((glyph) => `- \`${glyph.label}\` — ${glyph.description}`),
            "",
          ]
        : []),
      `Docs: ${external.docs}`,
      "",
    ].join("\n")
    docs.set(id, doc)
    // `tecton docs icons` / `tecton docs lucide-react`: the last segment of the specifier
    const alias = specifier.split("/").pop() ?? ""
    entries.push({
      id,
      kind: "external",
      name,
      import: external.import,
      summary: external.note ?? `${name} (${external.import})`,
      fields: {
        names: `${name.toLowerCase()} ${splitCamel(name)} ${glyphs.map((glyph) => splitCamel(glyph.label)).join(" ")}`,
        useWhen: [external.note ?? "", ...glyphs.map((glyph) => glyph.description)].join(" "),
        routed: (routed.get(id) ?? []).join(" "),
        do: "",
      },
      notFor: [],
      related: [],
      exports: glyphs.map((glyph) => glyph.label),
      aliases: alias && alias !== id ? [alias] : [],
      tokens: estimateTokens(doc),
    })
  }

  const topicErrors: string[] = []
  let rulesRaw = ""
  for (const file of readdirSync(TOPICS_DIR).filter((name) => name.endsWith(".md")).sort()) {
    const id = file.slice(0, -".md".length)
    const raw = readText(path.join(TOPICS_DIR, file))
    if (id === "rules") rulesRaw = raw
    const { title, description, errors } = topicMeta(file, raw)
    topicErrors.push(...errors)
    const headings = [...stripFrontmatter(raw).matchAll(/^#{2,3} (.*)$/gm)].map((m) => m[1]).join(" ")
    let doc = stripFrontmatter(raw).trim() + "\n"
    // Adopted rules for every file extend the rules page's own "Before you finish".
    if (id === "rules" && catalog.adoptedRules.length) {
      doc = appendToSection(doc, "Before you finish", catalog.adoptedRules.map((rule) => `- ${rule}`))
    }
    docs.set(id, doc)
    entries.push({
      id,
      kind: "topic",
      name: title,
      summary: title,
      fields: { names: id.replace(/-/g, " "), useWhen: description, routed: "", do: headings },
      notFor: [],
      related: [],
      exports: [],
      aliases: [],
      tokens: estimateTokens(doc),
    })
  }

  if (topicErrors.length) {
    for (const error of topicErrors) console.error(`✗ topics/${error}`)
    process.exit(1)
  }

  // The vocabulary: every expansion has to land on a word the index holds, read
  // the way the CLI reads it (`loadIndex` in bin/tecton-lib.mjs).
  const { synonyms } = JSON.parse(readText(SYNONYMS_FILE)) as {
    synonyms: Record<string, string[]>
  }
  const vocabulary = new Set(
    entries.flatMap((entry) => Object.values(entry.fields).flatMap((text) => tokenize(text, { camel: false })))
  )
  const synonymErrors = checkSynonyms(synonyms, vocabulary)
  if (synonymErrors.length) {
    for (const error of synonymErrors) console.error(`✗ synonyms.json: ${error}`)
    process.exit(1)
  }

  const skill = skillFile(catalog.version, rulesRaw)
  if (skill.errors.length) {
    for (const error of skill.errors) console.error(`✗ ${error}`)
    process.exit(1)
  }

  // `→ toast` in a notFor list reads as `→ sonner` once toast is folded in.
  const folded = new Map([...externalDocTarget])
  for (const entry of entries) {
    for (const item of entry.notFor) item.id = folded.get(item.id) ?? item.id
    entry.related = [...new Set(entry.related.map((id) => folded.get(id) ?? id))]
  }

  const index = {
    $comment: GENERATED,
    package: "@tecton/react",
    version: catalog.version,
    synonyms,
    entries,
  }

  const files = new Map<string, string>([
    [SKILL_FILE, skill.content],
    [path.join(OUT_DIR, "index.json"),`${JSON.stringify(index, null, 1)}\n`],
    ...[...docs].map(([id, doc]): [string, string] => [
      path.join(DOCS_DIR, `${id}.md`),
      `${GENERATED}\n\n${doc.trimEnd()}\n`,
    ]),
  ])

  const drift: string[] = []
  for (const [file, content] of files) {
    const current = existsSync(file) ? readText(file) : null
    if (current === content) continue
    drift.push(path.relative(PKG_ROOT, file))
    if (!check) {
      mkdirSync(path.dirname(file), { recursive: true })
      writeFileSync(file, content)
    }
  }
  if (existsSync(DOCS_DIR)) {
    for (const name of readdirSync(DOCS_DIR)) {
      const file = path.join(DOCS_DIR, name)
      if (files.has(file)) continue
      drift.push(`${path.relative(PKG_ROOT, file)} (no longer generated)`)
      if (!check) rmSync(file)
    }
  }

  const summary = `${entries.length} entries, ${docs.size} docs`
  if (check) {
    if (drift.length) {
      console.error(`agent:check failed — ${drift.length} file(s) differ:`)
      for (const item of drift) console.error(`  ${item}`)
      console.error("  run: pnpm --filter @tecton/react agent:build")
      process.exit(1)
    }
    console.log(`agent: up to date (${summary})`)
    return
  }
  console.log(drift.length ? `agent: wrote ${drift.length} file(s) (${summary})` : `agent: up to date (${summary})`)
}

main()
