/// <reference types="node" />
/**
 * barrel-build — generates src/index.ts, the single entry point of
 * `@tecton/react`.
 *
 *   bun run scripts/barrel-build.mts            writes src/index.ts
 *   bun run scripts/barrel-build.mts --check    fails (exit 1) when stale
 *
 * Why it exists: a micro-frontend host that shares Tecton through Module
 * Federation needs *one* share entry. Importing every component from its own
 * subpath (`@tecton/react/components/button`) means one `shared` key per
 * component; re-exporting the whole surface from `@tecton/react` collapses
 * that to a single key. The subpath exports stay — nothing has to move.
 *
 * Scope: src/components, src/hooks, src/lib and src/tecton. Deliberately out:
 *   - src/icons     already one generated barrel (`@tecton/react/icons`);
 *                   pulling it in here would drag the `tectonIcons` gallery
 *                   array — which references all 136 glyphs — into every
 *                   consumer and cost icon tree-shaking.
 *   - src/blocks    registry templates copied into an app by the shadcn CLI,
 *                   not imported from the package (see scripts/registry-build).
 *
 * Export names and their type-ness come from the TypeScript checker, not a
 * regex, so a type-only export is emitted under `export type { … }` and stays
 * safe to erase (isolatedModules / verbatimModuleSyntax). Two modules
 * exporting the same name fails the run: with a flat barrel one would
 * silently shadow the other.
 */
import { createRequire } from "node:module"
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const require = createRequire(import.meta.url)
const ts = require("typescript") as typeof import("typescript")
const prettier = require("prettier") as typeof import("prettier")

const HERE = path.dirname(fileURLToPath(import.meta.url))
const PKG = path.resolve(HERE, "..")
const SRC = path.join(PKG, "src")
const OUT = path.join(SRC, "index.ts")
const REPO = path.resolve(PKG, "../..")

const HEADER = "// GENERATED by scripts/barrel-build.mts — do not edit"
const check = process.argv.includes("--check")

/** The directories the barrel covers, in emit order, with their file extension. */
const GROUPS = [
  {
    dir: "components",
    ext: ".tsx",
    title:
      "shadcn components — generated by the CLI from the `aria-tecton` style",
  },
  { dir: "hooks", ext: ".ts", title: "hooks" },
  { dir: "lib", ext: ".ts", title: "utilities" },
  { dir: "tecton", ext: ".tsx", title: "Tecton components" },
] as const

type Export = { name: string; isType: boolean; pos: number }

const files = GROUPS.flatMap(({ dir, ext }) =>
  readdirSync(path.join(SRC, dir))
    .filter((f) => f.endsWith(ext))
    .sort()
    .map((f) => ({ dir, file: f, abs: path.join(SRC, dir, f) }))
)

// One program over the whole surface: the checker needs the real module graph
// to resolve a re-export such as `export { cn } from "cn"` back to a value.
const program = ts.createProgram(
  files.map((f) => f.abs),
  {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    jsx: ts.JsxEmit.ReactJSX,
    strict: true,
    skipLibCheck: true,
    noEmit: true,
    allowJs: false,
    baseUrl: PKG,
    paths: { "@tecton/react/*": ["./src/*"] },
  }
)
const checker = program.getTypeChecker()

/** The exports of one module, in source order, split into values and types. */
function exportsOf(abs: string): Export[] {
  const sourceFile = program.getSourceFile(abs)
  if (!sourceFile) throw new Error(`not in program: ${abs}`)
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile)
  if (!moduleSymbol) return []

  return checker
    .getExportsOfModule(moduleSymbol)
    .map((symbol) => {
      // `export { cn } from "cn"` is an alias; its value-ness lives on the
      // symbol it points at, not on the specifier.
      const target =
        symbol.flags & ts.SymbolFlags.Alias
          ? checker.getAliasedSymbol(symbol)
          : symbol
      const declaration = symbol.declarations?.[0]
      return {
        name: symbol.getName(),
        // A class or an enum is both; emit it as a value, which carries both.
        isType: !(target.flags & ts.SymbolFlags.Value),
        pos: declaration?.getStart() ?? 0,
      }
    })
    .sort((a, b) => a.pos - b.pos)
}

const collected = files.map((f) => ({ ...f, exports: exportsOf(f.abs) }))

// A flat barrel cannot carry the same name twice — ESM drops an ambiguous
// star-export silently and TypeScript errors on a duplicate named one. Fail
// here, where the message can name both modules.
const seen = new Map<string, string>()
const clashes: string[] = []
for (const { dir, file, exports } of collected) {
  for (const { name } of exports) {
    const from = `${dir}/${file}`
    const previous = seen.get(name)
    if (previous) clashes.push(`  ${name}: ${previous} and ${from}`)
    else seen.set(name, from)
  }
}
if (clashes.length) {
  console.error(
    `barrel-build: ${clashes.length} name(s) exported by more than one module:\n${clashes.join("\n")}\n\n` +
      "Rename one of them, or drop the module from GROUPS in scripts/barrel-build.mts."
  )
  process.exit(1)
}

const lines: string[] = [
  HEADER,
  "/**",
  " * The whole `@tecton/react` surface behind one import.",
  " *",
  " * Every component, hook and utility is also reachable at its own subpath",
  " * (`@tecton/react/components/button`), which is what the docs site and the",
  " * shadcn CLI use. This barrel exists for consumers that need a single",
  " * module — a Module Federation host, where one share entry per component",
  " * is unmanageable:",
  " *",
  ' *     import { Button, Panel, useIsMobile, cn } from "@tecton/react"',
  " *",
  " * Icons stay at `@tecton/react/icons` and blocks at `@tecton/react/blocks/*`;",
  " * see scripts/barrel-build.mts for why.",
  " */",
  "",
]

for (const { dir, ext, title } of GROUPS) {
  lines.push(`// ${"-".repeat(74)}`, `// ${title}`, `// ${"-".repeat(74)}`, "")
  for (const entry of collected.filter((c) => c.dir === dir)) {
    const module = `./${dir}/${entry.file.slice(0, -ext.length)}`
    const values = entry.exports.filter((e) => !e.isType).map((e) => e.name)
    const types = entry.exports.filter((e) => e.isType).map((e) => e.name)
    if (values.length)
      lines.push(`export { ${values.join(", ")} } from "${module}"`)
    if (types.length)
      lines.push(`export type { ${types.join(", ")} } from "${module}"`)
  }
  lines.push("")
}

const prettierConfig = await prettier.resolveConfig(OUT)
const output = await prettier.format(lines.join("\n"), {
  ...prettierConfig,
  filepath: OUT,
})

const current = (() => {
  try {
    return readFileSync(OUT, "utf8")
  } catch {
    return null
  }
})()

const total = collected.reduce((n, c) => n + c.exports.length, 0)
const relative = path.relative(REPO, OUT)

if (check) {
  if (current !== output) {
    console.error(
      `✗ ${relative} is out of date — run \`pnpm barrel:build\`.\n` +
        (current === null ? "  (the file does not exist)" : "")
    )
    process.exit(1)
  }
  console.log(
    `✓ ${relative} up to date (${total} exports from ${files.length} modules)`
  )
} else {
  if (current === output)
    console.log(`✓ ${relative} unchanged (${total} exports)`)
  else {
    writeFileSync(OUT, output)
    console.log(
      `✓ wrote ${relative} — ${total} exports from ${files.length} modules`
    )
  }
}
