/**
 * build-icons — generates `src/icons/` from the icon manifest.
 *
 *   bun run scripts/build-icons.mts          (pnpm icons:build)
 *
 * Inputs
 *   icons/icons.json               manifest: name / slug / label / description /
 *                                  symbol / lucide / domain
 *   icons/material-symbols.codepoints  Material Symbols Sharp's name → codepoint
 *                                  table; every manifest `symbol` resolves here
 *   icons/tecton-codepoints.json   the append-only allocation of Tecton's own
 *                                  glyphs (written by scripts/build-symbol-fonts.mts)
 *   icons-src/tecton/<slug>.ts     the Tecton icon export (defineTectonSvgIcon
 *                                  definitions with outline + filled markup)
 *   icons-src/<variant>/<slug>.svg loose SVG overrides (see scripts/extract-icons.mts)
 *   src/components/*.tsx           scanned for the identifiers imported from
 *                                  lucide-react or from the compat module
 *   src/tecton/*.tsx               (same — used to build the lucide compat map)
 *
 * Outputs (all GENERATED, all overwritten on every run)
 *   src/icons/<slug>.tsx           one component per manifest icon: a one-line
 *                                  `tectonIcon("<slug>")` wrapper, or an inline
 *                                  SVG component for a colour drawing
 *   src/icons/names.ts             `tectonIconNames` + the `tectonIconTable`
 *                                  that `<Icon>` resolves a name through
 *   src/icons/material-codepoints.ts  the Material name → codepoint table, for
 *                                  the `MaterialSymbol` escape hatch only
 *   src/icons/svg-icons.ts         the colour drawings `<Icon>` delegates to
 *   src/icons/types.ts             TectonIconProps & friends
 *   src/icons/_runtime.ts          tiny shared helper (size / stroke-width maths)
 *   src/icons/index.ts             named exports + `tectonIcons` gallery array
 *   src/icons/lucide-compat.map.ts lucide identifier → Tecton override / pass-through
 *
 * `src/icons/icon.tsx` (the `Icon` primitive and the font-readiness store),
 * `src/icons/material.tsx` and `src/icons/lucide-compat.ts` are hand-written.
 *
 * Every icon needs exactly one primary source, and the build fails when it has
 * none:
 *   1. "symbol"   the manifest names a Material Symbols glyph. It wins over a
 *                 Tecton drawing of the same icon, which stays in the domain
 *                 font as a reserve. Two icons may not claim the same symbol.
 *   2. "domain"   no symbol, but a drawing in icons-src/tecton (or a loose SVG):
 *                 it renders from the domain font, outlined and filled being two
 *                 codepoints.
 *   3. "svg"      a `colored` drawing (today: `strata` alone) keeps its inline
 *                 SVG component — a font glyph is monochrome.
 *
 * Every rendered icon carries `data-tecton-icon="<slug>"` and
 * `data-tecton-source="symbol" | "domain" | "svg"` so a docs gallery (or a
 * test) can tell what drew it.
 *
 * Flags
 *   --check   exit 1 if any output would change (CI drift guard); writes nothing
 */
/// <reference types="node" />
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  ICONS_OUT_DIR,
  MATERIAL_CODEPOINTS_PATH,
  ICONS_SRC_DIR,
  ICON_VARIANTS,
  type IconManifestEntry,
  type IconVariant,
  kebabToPascal,
  loadManifest,
  loadMaterialCodepoints,
  loadTectonDefinitions,
  normalizeSvg,
  parseAttributes,
  pkgRoot,
  scanIconSources,
} from "./icon-utils.mjs";
import type { TectonSvgIcon } from "../icons-src/icon-definition";

const HEADER = "// GENERATED by scripts/build-icons.mts — do not edit\n";
/** The wrappers put `"use client"` first, so the marker is looked for, not `startsWith`. */
const GENERATED_MARKER = HEADER.trim();
/** Every generated component is a client component (`Icon` subscribes to font loading). */
const USE_CLIENT = '"use client"\n';
const CHECK_MODE = process.argv.includes("--check");
const LUCIDE_DTS = path.join(pkgRoot, "node_modules/lucide-react/dist/lucide-react.d.ts");
/** The Tecton glyph allocation, written by scripts/build-symbol-fonts.mts. */
const ALLOCATION_PATH = path.join(pkgRoot, "icons/tecton-codepoints.json");
/** Folders scanned (recursively) for lucide-react imports when building the compat map. */
const COMPAT_SCAN_DIRS = ["src/components", "src/tecton"];
/**
 * Specifiers a scanned file can import the compat surface from. The generated
 * components no longer name `lucide-react`: the registry mirror rewrites their
 * import to the compat module before the CLI writes them
 * (scripts/registry-mirror/icon-imports.mts), so the scan has to recognise it
 * too or the component-usage entries silently empty out — and with them the
 * pass-through count that says which names still fall through to lucide.
 */
const COMPAT_MODULES = [
  "lucide-react",
  "@tecton/react/icons/lucide-compat",
  // The same module named from inside the package (a generated component that
  // was installed relative, or a src/tecton file that reaches for it).
  "../icons/lucide-compat",
  "./lucide-compat",
];
const COMPAT_IMPORT_RE = new RegExp(
  String.raw`import\s+(type\s+)?\{([^}]*)\}\s*from\s*["'](?:${COMPAT_MODULES.map((m) =>
    m.replace(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`)
  ).join("|")})["']`,
  "g"
);

type Source = "symbol" | "domain" | "svg";

// ---------------------------------------------------------------------------
// lucide-react export table (parsed from the bundled .d.ts)
// ---------------------------------------------------------------------------
interface LucideExports {
  /** Value exports that are icon components (e.g. `CirclePlus`, `CirclePlusIcon`). */
  values: Set<string>;
  /** Type-only exports (e.g. `LucideIcon`, `LucideProps`). */
  types: Set<string>;
  /** Exported alias → the declared const it points at (`MoreVerticalIcon` → `EllipsisVertical`). */
  canonical: Map<string, string>;
  /** Declared const → every export name that resolves to it (itself included). */
  aliases: Map<string, string[]>;
}

function loadLucideExports(): LucideExports | null {
  if (!existsSync(LUCIDE_DTS)) {
    console.warn(`warning: ${path.relative(pkgRoot, LUCIDE_DTS)} not found — skipping lucide name validation`);
    return null;
  }
  const dts = readFileSync(LUCIDE_DTS, "utf8");
  const values = new Set<string>();
  const types = new Set<string>();
  const canonical = new Map<string, string>();

  // `declare const CirclePlus: LucideIcon;`  and friends (createLucideIcon, Icon, …)
  for (const m of dts.matchAll(/^declare (?:const|function|class) (\w+)/gm)) values.add(m[1]);
  // `type LucideIcon = …` / `interface LucideProps …`
  for (const m of dts.matchAll(/^(?:declare )?(?:type|interface) (\w+)\b/gm)) types.add(m[1]);
  // The final `export { index_CirclePlus as CirclePlus, … }` block: aliases such as
  // `CirclePlusIcon` / `LucideCirclePlus` map to declared consts.
  for (const m of dts.matchAll(/\b(?:index_)?(\w+) as (\w+)/g)) {
    const [, target, alias] = m;
    if (values.has(target)) {
      values.add(alias);
      canonical.set(alias, canonical.get(target) ?? target);
    } else if (types.has(target)) types.add(alias);
  }
  const aliases = new Map<string, string[]>();
  for (const value of values) {
    const root = canonical.get(value) ?? value;
    aliases.set(root, [...(aliases.get(root) ?? []), value]);
  }
  return { values, types, canonical, aliases };
}

/** Closest lucide export names for an unknown one — makes manifest typos easy to fix. */
function suggestLucide(name: string, exports: LucideExports): string[] {
  const needle = name.toLowerCase().replace(/[^a-z0-9]/g, "");
  const out: string[] = [];
  for (const value of exports.values) {
    if (/^(Lucide|index_)/.test(value) || value.endsWith("Icon")) continue;
    const hay = value.toLowerCase();
    if (hay.includes(needle) || needle.includes(hay)) out.push(value);
    if (out.length >= 5) break;
  }
  return out;
}

// ---------------------------------------------------------------------------
// SVG → JSX
// ---------------------------------------------------------------------------

/** Attribute names React wants in a different spelling than SVG. */
const JSX_ATTR_RENAMES: Record<string, string> = {
  class: "className",
  for: "htmlFor",
  "xlink:href": "xlinkHref",
  "xlink:actuate": "xlinkActuate",
  "xlink:arcrole": "xlinkArcrole",
  "xlink:role": "xlinkRole",
  "xlink:show": "xlinkShow",
  "xlink:title": "xlinkTitle",
  "xlink:type": "xlinkType",
  "xml:base": "xmlBase",
  "xml:lang": "xmlLang",
  "xml:space": "xmlSpace",
  "xmlns:xlink": "xmlnsXlink",
  tabindex: "tabIndex",
  viewbox: "viewBox",
};

function toJsxAttrName(name: string): string {
  if (JSX_ATTR_RENAMES[name]) return JSX_ATTR_RENAMES[name];
  if (name.startsWith("data-") || name.startsWith("aria-")) return name;
  // stroke-width → strokeWidth, fill-rule → fillRule, …
  return name.replace(/-([a-z])/g, (_m, c: string) => c.toUpperCase());
}

/** `style="fill:none;stroke-width:2"` → `{{ fill: "none", strokeWidth: "2" }}` */
function styleToJsx(style: string): string {
  const pairs = style
    .split(";")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((decl) => {
      const idx = decl.indexOf(":");
      const prop = decl.slice(0, idx).trim();
      const value = decl.slice(idx + 1).trim();
      const key = prop.startsWith("--") ? JSON.stringify(prop) : prop.replace(/-([a-z])/g, (_m, c: string) => c.toUpperCase());
      return `${key}: ${JSON.stringify(value)}`;
    });
  return `{{ ${pairs.join(", ")} }}`;
}

/** Decode the handful of entities an SVG text node can carry; JSX `{"…"}` expressions are not entity-aware. */
function decodeEntities(text: string): string {
  return text
    .replace(/&#x([0-9a-f]+);/gi, (_m, hex: string) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_m, dec: string) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/&(amp|lt|gt|quot|apos|nbsp);/g, (_m, name: string) => ({ amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: "\u00a0" })[name] ?? _m);
}

function attrsToJsx(attrs: Map<string, string>): string {
  let out = "";
  for (const [name, value] of attrs) {
    const jsxName = toJsxAttrName(name);
    out += jsxName === "style" ? ` style=${styleToJsx(value)}` : ` ${jsxName}=${JSON.stringify(value)}`;
  }
  return out;
}

interface ParsedSvg {
  /** Root `<svg>` attributes minus xmlns/viewBox (already handled). */
  rootAttrs: Map<string, string>;
  viewBox: string;
  /** Children as JSX source, one element per line, no indentation. */
  childrenJsx: string[];
}

/**
 * Turn a canonical SVG (as written by normalizeSvg) into JSX lines.
 * The tokenizer understands opening / closing / self-closing tags and text
 * (needed for `<text>` glyphs); comments and prolog were already stripped.
 */
function parseSvgForJsx(svg: string, file: string): ParsedSvg {
  const rootMatch = svg.trim().match(/^<svg\b([^>]*)>([\s\S]*)<\/svg>\s*$/i);
  if (!rootMatch) throw new Error(`${file}: not a single <svg> element (run extract-icons to normalise it)`);
  const rootAttrs = parseAttributes(rootMatch[1]);
  const viewBox = rootAttrs.get("viewBox") ?? "0 0 24 24";
  rootAttrs.delete("viewBox");
  rootAttrs.delete("xmlns");

  const lines: string[] = [];
  const stack: string[] = [];
  const tokenRe = /<\/([\w:-]+)\s*>|<([\w:-]+)\b([^>]*?)(\/?)>|([^<]+)/g;
  for (const m of rootMatch[2].matchAll(tokenRe)) {
    const [, closeTag, openTag, attrText, selfClose, text] = m;
    const indent = "  ".repeat(stack.length);
    if (closeTag) {
      const expected = stack.pop();
      if (expected !== closeTag) throw new Error(`${file}: mismatched </${closeTag}> (expected </${expected}>)`);
      lines.push(`${indent.slice(2)}</${closeTag}>`);
    } else if (openTag) {
      const attrs = parseAttributes(attrText);
      // Namespace declarations on descendants (e.g. the XHTML <div> Figma puts
      // inside <foreignObject>) are not valid JSX props; React needs none.
      attrs.delete("xmlns");
      lines.push(`${indent}<${openTag}${attrsToJsx(attrs)}${selfClose ? " />" : ">"}`);
      if (!selfClose) stack.push(openTag);
    } else if (text && text.trim()) {
      // JSX text: escape braces and keep it on its own line
      lines.push(`${indent}{${JSON.stringify(decodeEntities(text.trim()))}}`);
    }
  }
  if (stack.length) throw new Error(`${file}: unclosed <${stack[stack.length - 1]}>`);
  return { rootAttrs, viewBox, childrenJsx: lines };
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------
interface IconBuild {
  entry: IconManifestEntry;
  /** Component identifier, e.g. `AddCircleIcon`. */
  ident: string;
  /** What draws the glyph — `tectonIconTable[slug].source`. */
  source: Source;
  /** Material codepoint, when source === "symbol". */
  codepoint: number | null;
  /** Tecton's two codepoints, when source === "domain". */
  domain: { outlined: number; filled: number } | null;
  /** lucide-react export this icon stands in for, when any. */
  lucideExport: string | null;
  code: string;
}

/** `icons/tecton-codepoints.json` — slug → the domain font's two codepoints. */
function loadAllocation(): Map<string, { outlined: number; filled: number }> {
  if (!existsSync(ALLOCATION_PATH)) {
    throw new Error(
      `${path.relative(pkgRoot, ALLOCATION_PATH)} is missing — run \`pnpm --filter @tecton/react icons:fonts\` first`,
    );
  }
  const file = JSON.parse(readFileSync(ALLOCATION_PATH, "utf8")) as {
    icons: Array<{ slug: string; outlined: string; filled: string }>;
  };
  const parse = (value: string, where: string) => {
    const match = /^U\+([0-9A-F]{4,6})$/.exec(value);
    if (!match) throw new Error(`icons/tecton-codepoints.json (${where}): "${value}" is not a U+XXXXX codepoint`);
    return Number.parseInt(match[1], 16);
  };
  return new Map(
    file.icons.map((entry) => [
      entry.slug,
      { outlined: parse(entry.outlined, entry.slug), filled: parse(entry.filled, entry.slug) },
    ]),
  );
}

function indentBlock(lines: string[], depth: number): string {
  const pad = "  ".repeat(depth);
  return lines.map((l) => (l ? pad + l : l)).join("\n");
}

function rootAttrsLiteral(attrs: Map<string, string>): string {
  if (!attrs.size) return "{}";
  const pairs: string[] = [];
  for (const [name, value] of attrs) {
    const key = toJsxAttrName(name);
    const safeKey = /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
    pairs.push(`${safeKey}: ${key === "style" ? styleToJsx(value).slice(1, -1) : JSON.stringify(value)}`);
  }
  return `{ ${pairs.join(", ")} }`;
}

/** One variant's normalised SVG plus where it came from (for the header comment). */
interface SvgSource {
  svg: string;
  origin: string;
}

/**
 * Turn a Tecton export definition into normalised `<svg>` strings per variant.
 * Figma's conic-gradient hack (`<foreignObject>` + `data-figma-*` attributes)
 * is dropped: the clipPath-referenced `<path>` keeps the shape, and the
 * gradient is re-expressed as an SVG `<linearGradient>` fill on that path.
 */
function definitionToSources(def: TectonSvgIcon, origin: string): Record<IconVariant, SvgSource | undefined> {
  const clean = (markup: string) => {
    // Figma exports conic gradients as a <foreignObject> with a CSS gradient
    // inside a clip-path group. Browsers render it, so multi-colour glyphs keep
    // it; monochrome glyphs drop it (the clipped <path> already draws the shape).
    const withoutGradientHack = def.colored
      ? markup
      : markup.replace(/<g[^>]*data-figma-skip-parse="true"[^>]*>[\s\S]*?<\/g>\s*<\/g>/g, "");
    return withoutGradientHack.replace(/\s+data-figma-[\w-]+="(?:[^"\\]|\\.)*"/g, "");
  };
  // The export's paths carry no fill: they inherit from the root, so the root
  // fills with currentColor (the same contract as lucide's stroke="currentColor").
  const wrap = (inner: string) =>
    normalizeSvg(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${def.viewBox}" fill="currentColor">${clean(inner)}</svg>`, {
      keepColors: def.colored,
    });
  return {
    outlined: def.outline ? { svg: wrap(def.outline), origin: `${origin} (outline)` } : undefined,
    filled: def.filled ? { svg: wrap(def.filled), origin: `${origin} (filled)` } : undefined,
  };
}

function genSvgComponent(entry: IconManifestEntry, ident: string, sources: Record<IconVariant, SvgSource | undefined>): string {
  // Resolve each variant to a parsed SVG, falling back to the other variant.
  const parsed: Partial<Record<IconVariant, ParsedSvg>> = {};
  for (const variant of ICON_VARIANTS) {
    const src = sources[variant];
    if (src) parsed[variant] = parseSvgForJsx(src.svg, src.origin);
  }
  const outlined = parsed.outlined ?? parsed.filled!;
  const filled = parsed.filled ?? parsed.outlined!;
  const sameGlyph =
    parsed.outlined === undefined ||
    parsed.filled === undefined ||
    parsed.outlined.childrenJsx.join("\n") === parsed.filled.childrenJsx.join("\n");

  // The source's own stroke-width is the default for the `strokeWidth` prop;
  // it is applied through tectonSvgAttrs(), so keep it out of ROOT.
  const strokeWidths: Record<IconVariant, string | undefined> = {
    outlined: outlined.rootAttrs.get("stroke-width"),
    filled: filled.rootAttrs.get("stroke-width"),
  };
  outlined.rootAttrs.delete("stroke-width");
  filled.rootAttrs.delete("stroke-width");

  const sourceComment = ICON_VARIANTS.filter((v) => sources[v])
    .map((v) => `//   ${v}: ${sources[v]!.origin}`)
    .join("\n");

  const body = sameGlyph
    ? indentBlock(outlined.childrenJsx, 3)
    : [
        "      {variant === \"filled\" ? (",
        "        <>",
        indentBlock(filled.childrenJsx, 5),
        "        </>",
        "      ) : (",
        "        <>",
        indentBlock(outlined.childrenJsx, 5),
        "        </>",
        "      )}",
      ].join("\n");

  return `${USE_CLIENT}${HEADER}// Drawn in colour, so it stays an inline SVG: a font glyph is monochrome.
// Source SVGs:
${sourceComment}
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: ${rootAttrsLiteral(outlined.rootAttrs)},
  filled: ${rootAttrsLiteral(filled.rootAttrs)},
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: ${JSON.stringify(outlined.viewBox)},
  filled: ${JSON.stringify(filled.viewBox)},
}

/** The source's own stroke-width — default for the \`strokeWidth\` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: ${JSON.stringify(strokeWidths.outlined)},
  filled: ${JSON.stringify(strokeWidths.filled)},
}

/** ${entry.label} — ${entry.description} */
export function ${ident}({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon=${JSON.stringify(entry.slug)}
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
${body}
    </svg>
  )
}
${ident}.displayName = ${JSON.stringify(ident)}
`;
}

/**
 * The wrapper every icon but a colour drawing gets: one line that binds the
 * name, so `./icons/<slug>` stays a module of its own and the component keeps
 * its displayName. `Icon` does the rest.
 */
function genWrapperComponent(entry: IconManifestEntry, ident: string, build: Omit<IconBuild, "code" | "entry" | "ident" | "lucideExport">): string {
  const drawn =
    build.source === "symbol"
      ? `Material Symbols Sharp \`${entry.symbol}\` (${hex(build.codepoint!)}), FILL ${"`"}variant${"`"}`
      : `Tecton's own drawing (${hex(build.domain!.outlined)} outlined, ${hex(build.domain!.filled)} filled)`;
  return `${USE_CLIENT}${HEADER}// ${drawn}, rendered from the symbol fonts by <Icon>.
import { tectonIcon } from "./icon"

/** ${entry.label} — ${entry.description} */
export const ${ident} = tectonIcon(${JSON.stringify(entry.slug)})
`;
}

/** `0xe147` → `U+E147`, for the generated comments. */
function hex(codepoint: number): string {
  return `U+${codepoint.toString(16).toUpperCase().padStart(4, "0")}`;
}

const TYPES_TS = `${HEADER}import type { ReactElement, SVGProps } from "react"

export type TectonIconVariant = "outlined" | "filled"

/**
 * What draws a glyph:
 *   - \`symbol\`  a Material Symbols Sharp codepoint, from "Tecton Symbols"
 *               (\`variant\` moves the font's FILL axis)
 *   - \`domain\`  one of Tecton's own drawings, from "Tecton Symbols Domain",
 *               where outlined and filled are two codepoints
 *   - \`svg\`     an inline SVG component, for a colour drawing a monochrome
 *               font glyph cannot carry
 */
export type TectonIconSource = "symbol" | "domain" | "svg"

/**
 * lucide-compatible icon props. Every Tecton icon is a plain function
 * component (React 19 forwards \`ref\` as a prop, so no forwardRef needed).
 */
export interface TectonIconProps extends SVGProps<SVGSVGElement> {
  /** Width and height (default 24). */
  size?: number | string
  /** Accepted for lucide compatibility — a font glyph has no stroke to widen. */
  strokeWidth?: number | string
  /** Accepted for lucide compatibility — no effect on a font glyph. */
  absoluteStrokeWidth?: boolean
  /** Glyph style (default \`outlined\`). */
  variant?: TectonIconVariant
}

export type TectonIconComponent = ((props: TectonIconProps) => ReactElement) & { displayName?: string }

/** What every icon carries, whatever draws it. */
export interface TectonIconMeta {
  /** PascalCase name without suffix, e.g. \`AddCircle\`. */
  name: string
  /** Exported identifier / gallery label, e.g. \`AddCircleIcon\`. */
  label: string
  description: string
  /** Oil & gas / subsurface domain glyph. */
  domain: boolean
  /** Closest lucide-react icon (kebab-case lucide name) or null. */
  lucide: string | null
  /** Material Symbols name, when a Material glyph draws it. */
  symbol: string | null
}

/** One row of \`tectonIconTable\` — the glyph, resolved. */
export type TectonIconRecord =
  | (TectonIconMeta & { source: "symbol"; symbol: string; codepoint: number })
  | (TectonIconMeta & { source: "domain"; symbol: null; outlined: number; filled: number })
  | (TectonIconMeta & { source: "svg"; symbol: null })

/** One row of the \`tectonIcons\` gallery array. */
export type TectonIconEntry = TectonIconRecord & {
  /** kebab-case id; also the \`data-tecton-icon\` value and the file name. */
  slug: string
  Icon: TectonIconComponent
}
`;

function recordLiteral(build: IconBuild): string {
  const e = build.entry;
  const meta =
    `name: ${JSON.stringify(e.name)}, label: ${JSON.stringify(e.label)}, description: ${JSON.stringify(e.description)}, ` +
    `domain: ${e.domain}, lucide: ${JSON.stringify(e.lucide)}, symbol: ${JSON.stringify(e.symbol)}`;
  if (build.source === "symbol") return `{ ${meta}, source: "symbol", codepoint: 0x${build.codepoint!.toString(16)} }`;
  if (build.source === "domain") {
    return `{ ${meta}, source: "domain", outlined: 0x${build.domain!.outlined.toString(16)}, filled: 0x${build.domain!.filled.toString(16)} }`;
  }
  return `{ ${meta}, source: "svg" }`;
}

function genNames(builds: Array<IconBuild>): string {
  const names = builds.map((b) => `  ${JSON.stringify(b.entry.slug)},`).join("\n");
  const rows = builds.map((b) => `  ${JSON.stringify(b.entry.slug)}: ${recordLiteral(b)},`).join("\n");
  const counts = (source: Source) => builds.filter((b) => b.source === source).length;
  return `${HEADER}//
// The ${builds.length} Tecton icon names and what draws each one:
// ${counts("symbol")} Material symbol(s), ${counts("domain")} Tecton drawing(s) in the domain font,
// ${counts("svg")} colour drawing(s) that stay an inline SVG component.
import type { TectonIconRecord } from "./types"

/** Every Tecton icon name, in manifest (alphabetical) order. */
export const tectonIconNames = [
${names}
] as const

/** A name \`Icon\`, \`tectonIcon\` and \`tectonIconTable\` accept. */
export type TectonIconName = (typeof tectonIconNames)[number]

/** The glyph behind each name, plus the metadata the docs gallery shows. */
export const tectonIconTable: Record<TectonIconName, TectonIconRecord> = {
${rows}
}
`;
}

function genMaterialCodepoints(names: Map<string, number>): string {
  const union = [...names.keys()].map((name) => `  | ${JSON.stringify(name)}`).join("\n");
  const rows = [...names].map(([name, code]) => `  ${JSON.stringify(name)}: 0x${code.toString(16)},`).join("\n");
  return `${HEADER}//
// icons/material-symbols.codepoints — Google's own name → codepoint table for
// Material Symbols Sharp (${names.size} glyph names), as a module.
//
// Only \`./material\` imports this: the table is dead weight for an application
// that stays on Tecton names, and keeping it on its own subpath is what lets a
// bundler drop it.

/** Every Material Symbols Sharp glyph name. */
export type MaterialSymbolName =
${union}

export const materialSymbolCodepoints: Record<MaterialSymbolName, number> = {
${rows}
}
`;
}

function genSvgIcons(builds: Array<IconBuild>): string {
  const svg = builds.filter((b) => b.source === "svg");
  const imports = svg.map((b) => `import { ${b.ident} } from "./${b.entry.slug}"`).join("\n");
  const rows = svg.map((b) => `  ${JSON.stringify(b.entry.slug)}: ${b.ident},`).join("\n");
  return `${HEADER}//
// The colour drawings that stay inline SVG components — a font glyph is
// monochrome, so the gradient would be lost. \`Icon\` renders these instead of
// a \`<text>\` glyph.
${imports}
import type { TectonIconName } from "./names"
import type { TectonIconComponent } from "./types"

export const tectonSvgIcons: Partial<Record<TectonIconName, TectonIconComponent>> = {
${rows}
}
`;
}

const RUNTIME_TS = `${HEADER}/**
 * Size / stroke-width maths shared by generated SVG-backed icons.
 * Mirrors lucide: with \`absoluteStrokeWidth\` the stroke stays visually
 * constant across sizes (strokeWidth * viewBoxSize / size).
 */
export function tectonSvgAttrs(
  size: number | string,
  strokeWidth: number | string | undefined,
  absoluteStrokeWidth: boolean | undefined,
  viewBox = "0 0 24 24",
): { width: number | string; height: number | string; strokeWidth?: number | string } {
  const attrs: { width: number | string; height: number | string; strokeWidth?: number | string } = {
    width: size,
    height: size,
  }
  if (strokeWidth === undefined) return attrs
  const numericSize = typeof size === "number" ? size : Number.parseFloat(size)
  const viewBoxSize = Number.parseFloat(viewBox.split(/\\s+/)[2] ?? "24") || 24
  attrs.strokeWidth =
    absoluteStrokeWidth && Number.isFinite(numericSize) && numericSize > 0
      ? (Number(strokeWidth) * viewBoxSize) / numericSize
      : strokeWidth
  return attrs
}
`;

function genIndex(builds: Array<IconBuild>): string {
  const exports = builds.map((b) => `export { ${b.ident} } from "./${b.entry.slug}"`).join("\n");
  const imports = builds.map((b) => `import { ${b.ident} } from "./${b.entry.slug}"`).join("\n");
  const components = builds.map((b) => `  ${JSON.stringify(b.entry.slug)}: ${b.ident},`).join("\n");
  return `${HEADER}import { tectonIconNames, tectonIconTable } from "./names"
${imports}
import type { TectonIconName } from "./names"
import type { TectonIconComponent, TectonIconEntry } from "./types"

export { Icon, tectonIcon, useTectonSymbolFontState } from "./icon"
export type { IconName, IconProps, TectonSymbolFontState } from "./icon"
export { tectonIconNames, tectonIconTable } from "./names"
export type { TectonIconName } from "./names"
export type {
  TectonIconComponent,
  TectonIconEntry,
  TectonIconMeta,
  TectonIconProps,
  TectonIconRecord,
  TectonIconSource,
  TectonIconVariant,
} from "./types"

${exports}

/** The component behind each name — what \`tectonIcons[].Icon\` renders. */
const components: Record<TectonIconName, TectonIconComponent> = {
${components}
}

/** Every Tecton icon, in manifest (alphabetical) order — drives the docs gallery. */
export const tectonIcons: ReadonlyArray<TectonIconEntry> = tectonIconNames.map((slug) => ({
  ...tectonIconTable[slug],
  slug,
  Icon: components[slug],
}))

/** Lookup by slug, e.g. \`tectonIconsBySlug["add-circle"]\`. */
export const tectonIconsBySlug: Readonly<Record<string, TectonIconEntry>> = Object.fromEntries(
  tectonIcons.map((entry) => [entry.slug, entry]),
)
`;
}

// ---------------------------------------------------------------------------
// lucide compat map
// ---------------------------------------------------------------------------

/** Collect `{ A, B as C }` identifiers imported from a COMPAT_MODULES specifier. */
function collectLucideIdentifiers(): Map<string, string[]> {
  const uses = new Map<string, string[]>(); // identifier → files
  const visit = (dir: string, rel: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        visit(path.join(dir, entry.name), `${rel}/${entry.name}`);
        continue;
      }
      if (!/\.tsx?$/.test(entry.name)) continue;
      const src = readFileSync(path.join(dir, entry.name), "utf8");
      for (const m of src.matchAll(COMPAT_IMPORT_RE)) {
        for (const spec of m[2].split(",")) {
          const cleaned = spec.replace(/\btype\s+/, "").trim();
          if (!cleaned) continue;
          const original = cleaned.split(/\s+as\s+/)[0].trim();
          const files = uses.get(original) ?? [];
          files.push(`${rel}/${entry.name}`);
          uses.set(original, files);
        }
      }
    }
  };
  for (const rel of COMPAT_SCAN_DIRS) {
    const dir = path.join(pkgRoot, rel);
    if (existsSync(dir)) visit(dir, rel);
  }
  return new Map([...uses.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

interface CompatRow {
  ident: string;
  kind: "type" | "lucide" | "tecton";
  /** Tecton build providing the override, when kind === "tecton". */
  build?: IconBuild;
  files: string[];
}

function resolveCompat(uses: Map<string, string[]>, builds: IconBuild[], lucide: LucideExports | null): CompatRow[] {
  // Tecton icons keyed by the PascalCase lucide name they stand in for. Every
  // icon has a glyph now (a Material symbol or a Tecton drawing), so every one
  // of them can shadow its lucide peer.
  const byLucide = new Map<string, Array<IconBuild>>();
  for (const b of builds) {
    if (!b.entry.lucide) continue;
    const key = kebabToPascal(b.entry.lucide);
    byLucide.set(key, [...(byLucide.get(key) ?? []), b]);
  }

  // ChevronDownIcon / LucideChevronDown / MoreVerticalIcon → ChevronDown / EllipsisVertical
  const baseOf = (ident: string) => {
    const bare = ident.replace(/^Lucide/, "").replace(/Icon$/, "");
    return lucide?.canonical.get(ident) ?? lucide?.canonical.get(bare) ?? bare;
  };
  const overrideFor = (ident: string): IconBuild | undefined => {
    const candidates = byLucide.get(baseOf(ident)) ?? [];
    // Prefer the icon whose own name equals the lucide name (chevron-down over chevron-down-small).
    return candidates.find((b) => b.entry.slug === b.entry.lucide) ?? candidates[0];
  };

  const rows: CompatRow[] = [];
  const seen = new Set<string>();
  for (const [ident, files] of uses) {
    seen.add(ident);
    if (lucide?.types.has(ident)) {
      rows.push({ ident, kind: "type", files });
      continue;
    }
    if (lucide && !lucide.values.has(ident)) {
      throw new Error(`"${ident}" is imported from lucide-react in ${files.join(", ")} but lucide-react does not export it`);
    }
    const pick = overrideFor(ident);
    rows.push(pick ? { ident, kind: "tecton", build: pick, files } : { ident, kind: "lucide", files });
  }

  // The rest of the catalogue: every lucide export name (and alias) that a
  // Tecton icon stands in for, so application code importing other lucide
  // icons also gets the Tecton glyph through the bundler alias.
  if (lucide) {
    for (const [base, candidates] of byLucide) {
      const pick = candidates.find((b) => b.entry.slug === b.entry.lucide) ?? candidates[0];
      for (const ident of lucide.aliases.get(base) ?? []) {
        if (seen.has(ident) || lucide.types.has(ident)) continue;
        seen.add(ident);
        rows.push({ ident, kind: "tecton", build: pick, files: ["catalogue"] });
      }
    }
  }
  return rows.sort((a, b) => a.ident.localeCompare(b.ident));
}

function genCompatMap(rows: CompatRow[]): string {
  const overrides = rows.filter((r) => r.kind === "tecton");
  const passthrough = rows.filter((r) => r.kind === "lucide");
  const types = rows.filter((r) => r.kind === "type");

  const lines: string[] = [
    HEADER.trimEnd(),
    "//",
    "// lucide-react identifiers used by src/components and src/tecton,",
    "// plus every lucide name (and alias) a Tecton icon stands in for. Consumed by",
    "// ./lucide-compat.ts.",
    "// Everything else lucide exports passes straight through (star re-export;",
    "// the explicit exports below shadow it).",
    "",
    'export * from "lucide-react"',
    "",
  ];

  lines.push(`// ${overrides.length} Tecton override(s)`);
  for (const r of overrides) {
    const b = r.build!;
    lines.push(`export { ${b.ident}${b.ident === r.ident ? "" : ` as ${r.ident}`} } from "./${b.entry.slug}" // ${r.files.join(", ")}`);
  }
  lines.push("", `// ${passthrough.length} lucide pass-through(s) (no Tecton icon for this name)`);
  for (const r of passthrough) lines.push(`export { ${r.ident} } from "lucide-react" // ${r.files.join(", ")}`);
  if (types.length) {
    lines.push("", "// type-only re-exports");
    for (const r of types) lines.push(`export type { ${r.ident} } from "lucide-react"`);
  }

  lines.push(
    "",
    "/** Which identifiers are served by Tecton vs lucide — handy for docs / tests. */",
    "export const tectonLucideCompat = {",
    ...rows.filter((r) => r.kind !== "type").map((r) => `  ${r.ident}: ${JSON.stringify(r.kind === "tecton" ? r.build!.entry.slug : "lucide")},`),
    "} as const",
    "",
  );
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main(): Promise<void> {
  const manifest = loadManifest();
  const lucide = loadLucideExports();
  const sources = scanIconSources(ICONS_SRC_DIR);
  const definitions = await loadTectonDefinitions();
  const materialCodepoints = loadMaterialCodepoints();
  const allocation = loadAllocation();
  const manifestSlugs = new Set(manifest.icons.map((i) => i.slug));
  for (const slug of definitions.keys()) {
    if (!manifestSlugs.has(slug)) console.warn(`warning: icons-src/tecton/${slug}.ts has no entry in icons/icons.json (ignored)`);
  }

  // Warn about SVGs that no manifest entry claims.
  for (const variant of ICON_VARIANTS) {
    for (const slug of sources[variant].keys()) {
      if (!manifestSlugs.has(slug)) console.warn(`warning: icons-src/${variant}/${slug}.svg has no entry in icons/icons.json (ignored)`);
    }
  }

  // Per-icon builds.
  const builds: Array<IconBuild> = [];
  const idents = new Set<string>();
  const badLucide: Array<string> = [];
  const badSymbol: Array<string> = [];
  const noSource: Array<string> = [];
  const symbolOwner = new Map<string, string>();
  for (const entry of manifest.icons) {
    const ident = entry.label;
    if (!/^[A-Z][A-Za-z0-9]*Icon$/.test(ident)) throw new Error(`manifest label "${ident}" is not a valid PascalCase identifier ending in "Icon"`);
    if (idents.has(ident)) throw new Error(`duplicate manifest label "${ident}"`);
    idents.add(ident);

    // Loose SVG files override the export; the export is the default source.
    const definition = definitions.get(entry.slug);
    const fromDefinition = definition
      ? definitionToSources(definition.def, path.relative(pkgRoot, definition.file).split(path.sep).join("/"))
      : { outlined: undefined, filled: undefined };
    const svgSources: Record<IconVariant, SvgSource | undefined> = { outlined: undefined, filled: undefined };
    for (const variant of ICON_VARIANTS) {
      const file = sources[variant].get(entry.slug);
      svgSources[variant] = file
        ? { svg: normalizeSvg(readFileSync(file, "utf8")), origin: path.relative(pkgRoot, file).split(path.sep).join("/") }
        : fromDefinition[variant];
    }
    const hasSvg = Boolean(svgSources.outlined || svgSources.filled);
    const colored = Boolean(definition?.def.colored);

    let lucideExport: string | null = null;
    if (entry.lucide) {
      lucideExport = kebabToPascal(entry.lucide);
      if (lucide && !lucide.values.has(lucideExport)) {
        badLucide.push(`${entry.slug}: lucide "${entry.lucide}" (${lucideExport}) — try: ${suggestLucide(lucideExport, lucide).join(", ") || "?"}`);
        lucideExport = null;
      }
    }

    let codepoint: number | null = null;
    if (entry.symbol !== null) {
      const owner = symbolOwner.get(entry.symbol);
      if (owner) badSymbol.push(`${entry.slug}: symbol "${entry.symbol}" is already claimed by ${owner}`);
      else symbolOwner.set(entry.symbol, entry.slug);
      const code = materialCodepoints.get(entry.symbol);
      if (code === undefined) badSymbol.push(`${entry.slug}: symbol "${entry.symbol}" is not in icons/material-symbols.codepoints`);
      else codepoint = code;
    }

    // One primary source per icon. A colour drawing is the exception: a font
    // glyph is monochrome, so it keeps its inline SVG whatever else it has.
    let source: Source;
    let domain: IconBuild["domain"] = null;
    let code: string;
    if (colored && hasSvg) {
      source = "svg";
      code = genSvgComponent(entry, ident, svgSources);
    } else if (codepoint !== null) {
      source = "symbol";
      code = genWrapperComponent(entry, ident, { source, codepoint, domain });
    } else if (hasSvg) {
      const allocated = allocation.get(entry.slug);
      if (!allocated) {
        throw new Error(
          `${entry.slug} is drawn by icons-src/tecton but icons/tecton-codepoints.json has no codepoint for it — ` +
            "run `pnpm --filter @tecton/react icons:fonts` first",
        );
      }
      source = "domain";
      domain = allocated;
      code = genWrapperComponent(entry, ident, { source, codepoint, domain });
    } else {
      // Nothing to draw: neither a Material symbol nor a Tecton drawing.
      noSource.push(`${entry.slug} (${entry.label})`);
      continue;
    }
    builds.push({ entry, ident, source, codepoint, domain, lucideExport, code });
  }
  if (noSource.length) {
    throw new Error(
      `icons/icons.json entries with no glyph at all — give each one a "symbol" from ` +
        `icons/material-symbols.codepoints, or a drawing in icons-src/tecton/:\n  ${noSource.join("\n  ")}`,
    );
  }
  if (badSymbol.length) {
    throw new Error(`icons/icons.json has unusable "symbol" values:\n  ${badSymbol.join("\n  ")}`);
  }
  if (badLucide.length) {
    throw new Error(`icons/icons.json references lucide icons that lucide-react does not export:\n  ${badLucide.join("\n  ")}`);
  }

  // Files to write.
  const outputs = new Map<string, string>();
  for (const b of builds) outputs.set(path.join(ICONS_OUT_DIR, `${b.entry.slug}.tsx`), b.code);
  outputs.set(path.join(ICONS_OUT_DIR, "types.ts"), TYPES_TS);
  outputs.set(path.join(ICONS_OUT_DIR, "_runtime.ts"), RUNTIME_TS);
  outputs.set(path.join(ICONS_OUT_DIR, "names.ts"), genNames(builds));
  outputs.set(path.join(ICONS_OUT_DIR, "material-codepoints.ts"), genMaterialCodepoints(materialCodepoints));
  outputs.set(path.join(ICONS_OUT_DIR, "svg-icons.ts"), genSvgIcons(builds));
  outputs.set(path.join(ICONS_OUT_DIR, "index.ts"), genIndex(builds));
  const compatRows = resolveCompat(collectLucideIdentifiers(), builds, lucide);
  outputs.set(path.join(ICONS_OUT_DIR, "lucide-compat.map.ts"), genCompatMap(compatRows));

  // Stale generated files (icons removed from the manifest). The hand-written
  // modules (icon.tsx, material.tsx, lucide-compat.ts) carry no marker.
  const stale: Array<string> = [];
  if (existsSync(ICONS_OUT_DIR)) {
    for (const name of readdirSync(ICONS_OUT_DIR)) {
      const file = path.join(ICONS_OUT_DIR, name);
      if (outputs.has(file) || !/\.tsx?$/.test(name)) continue;
      if (readFileSync(file, "utf8").slice(0, 200).includes(GENERATED_MARKER)) stale.push(file);
    }
  }

  // Write (or check).
  let changed = 0;
  for (const [file, content] of outputs) {
    // Windows checkouts may carry CRLF; compare on normalised line endings.
    const current = existsSync(file) ? readFileSync(file, "utf8").replace(/\r\n/g, "\n") : null;
    if (current === content) continue;
    changed++;
    if (CHECK_MODE) console.log(`would ${current === null ? "create" : "update"} ${path.relative(pkgRoot, file)}`);
    else {
      mkdirSync(path.dirname(file), { recursive: true });
      writeFileSync(file, content, "utf8");
    }
  }
  for (const file of stale) {
    changed++;
    if (CHECK_MODE) console.log(`would delete ${path.relative(pkgRoot, file)}`);
    else rmSync(file);
  }

  // Summary.
  const count = (source: Source) => builds.filter((b) => b.source === source).length;
  const passthrough = compatRows.filter((r) => r.kind === "lucide");
  console.log(
    [
      `icons: ${builds.length} component(s) → ${path.relative(pkgRoot, ICONS_OUT_DIR)}/`,
      `  symbol: ${count("symbol")}   domain: ${count("domain")}   svg: ${count("svg")}` +
        `   (${materialCodepoints.size} Material names in material-codepoints.ts)`,
      `  lucide compat: ${compatRows.filter((r) => r.kind === "tecton").length} Tecton override(s), ${passthrough.length} pass-through(s)` +
        (passthrough.length ? `: ${passthrough.map((r) => r.ident).join(", ")}` : ""),
      `  ${CHECK_MODE ? "changes pending" : "files changed"}: ${changed}${stale.length ? ` (stale removed: ${stale.length})` : ""}`,
    ].join("\n"),
  );
  if (CHECK_MODE && changed) {
    console.error("build-icons --check: outputs are out of date — run `pnpm icons:build`");
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(`build-icons: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
