/**
 * build-icons — generates `src/icons/` from the icon manifest + SVG sources.
 *
 *   bun run scripts/build-icons.mts          (pnpm icons:build)
 *
 * Inputs
 *   icons/icons.json               manifest: name / slug / label / lucide / domain
 *   icons-src/tecton/<slug>.ts     the Tecton icon export (defineTectonSvgIcon
 *                                  definitions with outline + filled markup) — primary source
 *   icons-src/<variant>/<slug>.svg loose SVG overrides (see scripts/extract-icons.mts)
 *
 * Only the SHIPPED icons are generated — the `domain: true` entries, per
 * `isShippedIcon()` in scripts/icon-utils.mts. The manifest and the vendored
 * export are already trimmed to those (the Tecton set's general-purpose glyphs
 * duplicate lucide-react and are neither vendored nor published), so the filter
 * matters when a fresh full export is dropped in. Components left behind by an
 * entry that no longer ships are swept away.
 *
 * Outputs (all GENERATED, all overwritten on every run)
 *   src/icons/<slug>.tsx           one component per shipped manifest icon
 *   src/icons/types.ts             TectonIconProps & friends
 *   src/icons/_runtime.ts          tiny shared helper (size / stroke-width maths)
 *   src/icons/index.ts             named exports + `tectonIcons` gallery array
 *
 * Per icon, the rendered source is chosen in this order:
 *   1. "svg"              icons-src/tecton/<slug>.ts defines it, or
 *                         icons-src/<variant>/<slug>.svg exists (the other
 *                         variant falls back to whichever variant exists)
 *   2. "lucide-fallback"  manifest `lucide` names a lucide-react export
 *   3. "placeholder"      dashed rounded square (domain glyphs with no peer)
 *
 * Every generated svg carries `data-tecton-icon="<slug>"` and
 * `data-tecton-source="svg" | "lucide-fallback" | "placeholder"` so a docs
 * gallery (or a test) can tell real glyphs from stand-ins.
 *
 * SVG-backed icons are also optically cropped: the source grid carries the
 * glyph's own margin, so the generated viewBox is trimmed by up to
 * ICON_VIEWBOX_INSET user units per side (clamped per icon by the glyph's real
 * bounding box, measured with scripts/svg-bbox.mts) and the crop is recorded in
 * each generated file's header. Path data is never touched, and the
 * lucide-fallback and placeholder components are not cropped.
 *
 * Flags
 *   --check   exit 1 if any output would change (CI drift guard); writes nothing
 */
/// <reference types="node" />
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import {
  ICONS_OUT_DIR,
  ICONS_SRC_DIR,
  ICON_VARIANTS,
  type IconManifestEntry,
  type IconVariant,
  isShippedIcon,
  kebabToPascal,
  loadManifest,
  normalizeSvg,
  parseAttributes,
  pkgRoot,
  scanIconSources,
} from "./icon-utils.mjs";
import { opticalCrop } from "./svg-bbox.mjs";
import type { TectonSvgIcon } from "../icons-src/icon-definition";

const TECTON_DEFINITIONS_DIR = path.join(pkgRoot, "icons-src/tecton");

/**
 * Optical crop: how much of the source grid the generated viewBox trims from
 * each side, in the source's own user units, so a Tecton glyph renders as
 * large as a lucide glyph at the same pixel size.
 *
 * Why 1 (on the 16-unit Tecton grid → `viewBox="1 1 14 14"`, 16/14 ≈ 1.143x):
 *
 *   - Measured gap. Comparing the painted extent of seven Tecton glyphs with
 *     their lucide counterparts (normalised to the same box, lucide's 2-unit
 *     stroke counted as a 1-unit halo on each side) the Tecton glyph is
 *     0.85–0.98 of the lucide one, median 0.89 — lucide renders ~1.12x larger.
 *     1.143x closes that: the median lands at ~1.02.
 *
 *   - Not 2, even though the modal Tecton glyph sits in a 12x12 live area
 *     (inset exactly 2.0 is the single most common margin in the export and
 *     `checkbox` is exactly `2 2 14 14`): 58 of the 131 glyphs in the full
 *     Tecton export reach past it, by up to a full 2 units, so
 *     `viewBox="2 2 12 12"` would clip them.
 *     Only 19 glyphs have less than 1 unit to spare, and each of those is
 *     clamped individually rather than clipped.
 *
 *   - It is an upper bound, not a promise: the per-icon padding is
 *     `min(ICON_VIEWBOX_INSET, the glyph's own margin)`, so a full-bleed glyph
 *     such as `add-pin` (its badge touches y=0) keeps its original viewBox.
 */
const ICON_VIEWBOX_INSET = 1;

const HEADER = "// GENERATED by scripts/build-icons.mts — do not edit\n";
const CHECK_MODE = process.argv.includes("--check");
const LUCIDE_DTS = path.join(pkgRoot, "node_modules/lucide-react/dist/lucide-react.d.ts");

type Source = "svg" | "lucide-fallback" | "placeholder";

// ---------------------------------------------------------------------------
// lucide-react export table (parsed from the bundled .d.ts)
// ---------------------------------------------------------------------------
interface LucideExports {
  /** Value exports that are icon components (e.g. `CirclePlus`, `CirclePlusIcon`). */
  values: Set<string>;
  /** Type-only exports (e.g. `LucideIcon`, `LucideProps`). */
  types: Set<string>;
  /** Exported alias → the declared const it points at (`MoreVerticalIcon` → `EllipsisVertical`). */
  canonical: Map<string, string>;
  /** Declared const → every export name that resolves to it (itself included). */
  aliases: Map<string, string[]>;
}

function loadLucideExports(): LucideExports | null {
  if (!existsSync(LUCIDE_DTS)) {
    console.warn(`warning: ${path.relative(pkgRoot, LUCIDE_DTS)} not found — skipping lucide name validation`);
    return null;
  }
  const dts = readFileSync(LUCIDE_DTS, "utf8");
  const values = new Set<string>();
  const types = new Set<string>();
  const canonical = new Map<string, string>();

  // `declare const CirclePlus: LucideIcon;`  and friends (createLucideIcon, Icon, …)
  for (const m of dts.matchAll(/^declare (?:const|function|class) (\w+)/gm)) values.add(m[1]);
  // `type LucideIcon = …` / `interface LucideProps …`
  for (const m of dts.matchAll(/^(?:declare )?(?:type|interface) (\w+)\b/gm)) types.add(m[1]);
  // The final `export { index_CirclePlus as CirclePlus, … }` block: aliases such as
  // `CirclePlusIcon` / `LucideCirclePlus` map to declared consts.
  for (const m of dts.matchAll(/\b(?:index_)?(\w+) as (\w+)/g)) {
    const [, target, alias] = m;
    if (values.has(target)) {
      values.add(alias);
      canonical.set(alias, canonical.get(target) ?? target);
    } else if (types.has(target)) types.add(alias);
  }
  const aliases = new Map<string, string[]>();
  for (const value of values) {
    const root = canonical.get(value) ?? value;
    aliases.set(root, [...(aliases.get(root) ?? []), value]);
  }
  return { values, types, canonical, aliases };
}

/** Closest lucide export names for an unknown one — makes manifest typos easy to fix. */
function suggestLucide(name: string, exports: LucideExports): string[] {
  const needle = name.toLowerCase().replace(/[^a-z0-9]/g, "");
  const out: string[] = [];
  for (const value of exports.values) {
    if (/^(Lucide|index_)/.test(value) || value.endsWith("Icon")) continue;
    const hay = value.toLowerCase();
    if (hay.includes(needle) || needle.includes(hay)) out.push(value);
    if (out.length >= 5) break;
  }
  return out;
}

// ---------------------------------------------------------------------------
// SVG → JSX
// ---------------------------------------------------------------------------

/** Attribute names React wants in a different spelling than SVG. */
const JSX_ATTR_RENAMES: Record<string, string> = {
  class: "className",
  for: "htmlFor",
  "xlink:href": "xlinkHref",
  "xlink:actuate": "xlinkActuate",
  "xlink:arcrole": "xlinkArcrole",
  "xlink:role": "xlinkRole",
  "xlink:show": "xlinkShow",
  "xlink:title": "xlinkTitle",
  "xlink:type": "xlinkType",
  "xml:base": "xmlBase",
  "xml:lang": "xmlLang",
  "xml:space": "xmlSpace",
  "xmlns:xlink": "xmlnsXlink",
  tabindex: "tabIndex",
  viewbox: "viewBox",
};

function toJsxAttrName(name: string): string {
  if (JSX_ATTR_RENAMES[name]) return JSX_ATTR_RENAMES[name];
  if (name.startsWith("data-") || name.startsWith("aria-")) return name;
  // stroke-width → strokeWidth, fill-rule → fillRule, …
  return name.replace(/-([a-z])/g, (_m, c: string) => c.toUpperCase());
}

/** `style="fill:none;stroke-width:2"` → `{{ fill: "none", strokeWidth: "2" }}` */
function styleToJsx(style: string): string {
  const pairs = style
    .split(";")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((decl) => {
      const idx = decl.indexOf(":");
      const prop = decl.slice(0, idx).trim();
      const value = decl.slice(idx + 1).trim();
      const key = prop.startsWith("--") ? JSON.stringify(prop) : prop.replace(/-([a-z])/g, (_m, c: string) => c.toUpperCase());
      return `${key}: ${JSON.stringify(value)}`;
    });
  return `{{ ${pairs.join(", ")} }}`;
}

/** Decode the handful of entities an SVG text node can carry; JSX `{"…"}` expressions are not entity-aware. */
function decodeEntities(text: string): string {
  return text
    .replace(/&#x([0-9a-f]+);/gi, (_m, hex: string) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_m, dec: string) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/&(amp|lt|gt|quot|apos|nbsp);/g, (_m, name: string) => ({ amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: "\u00a0" })[name] ?? _m);
}

function attrsToJsx(attrs: Map<string, string>): string {
  let out = "";
  for (const [name, value] of attrs) {
    const jsxName = toJsxAttrName(name);
    out += jsxName === "style" ? ` style=${styleToJsx(value)}` : ` ${jsxName}=${JSON.stringify(value)}`;
  }
  return out;
}

interface ParsedSvg {
  /** Root `<svg>` attributes minus xmlns/viewBox (already handled). */
  rootAttrs: Map<string, string>;
  viewBox: string;
  /** Children as JSX source, one element per line, no indentation. */
  childrenJsx: string[];
}

/**
 * Turn a canonical SVG (as written by normalizeSvg) into JSX lines.
 * The tokenizer understands opening / closing / self-closing tags and text
 * (needed for `<text>` glyphs); comments and prolog were already stripped.
 */
function parseSvgForJsx(svg: string, file: string): ParsedSvg {
  const rootMatch = svg.trim().match(/^<svg\b([^>]*)>([\s\S]*)<\/svg>\s*$/i);
  if (!rootMatch) throw new Error(`${file}: not a single <svg> element (run extract-icons to normalise it)`);
  const rootAttrs = parseAttributes(rootMatch[1]);
  const viewBox = rootAttrs.get("viewBox") ?? "0 0 24 24";
  rootAttrs.delete("viewBox");
  rootAttrs.delete("xmlns");

  const lines: string[] = [];
  const stack: string[] = [];
  const tokenRe = /<\/([\w:-]+)\s*>|<([\w:-]+)\b([^>]*?)(\/?)>|([^<]+)/g;
  for (const m of rootMatch[2].matchAll(tokenRe)) {
    const [, closeTag, openTag, attrText, selfClose, text] = m;
    const indent = "  ".repeat(stack.length);
    if (closeTag) {
      const expected = stack.pop();
      if (expected !== closeTag) throw new Error(`${file}: mismatched </${closeTag}> (expected </${expected}>)`);
      lines.push(`${indent.slice(2)}</${closeTag}>`);
    } else if (openTag) {
      const attrs = parseAttributes(attrText);
      // Namespace declarations on descendants (e.g. the XHTML <div> Figma puts
      // inside <foreignObject>) are not valid JSX props; React needs none.
      attrs.delete("xmlns");
      lines.push(`${indent}<${openTag}${attrsToJsx(attrs)}${selfClose ? " />" : ">"}`);
      if (!selfClose) stack.push(openTag);
    } else if (text && text.trim()) {
      // JSX text: escape braces and keep it on its own line
      lines.push(`${indent}{${JSON.stringify(decodeEntities(text.trim()))}}`);
    }
  }
  if (stack.length) throw new Error(`${file}: unclosed <${stack[stack.length - 1]}>`);
  return { rootAttrs, viewBox, childrenJsx: lines };
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------
interface IconBuild {
  entry: IconManifestEntry;
  /** Component identifier, e.g. `AddCircleIcon`. */
  ident: string;
  /** What each variant renders. */
  sources: Record<IconVariant, Source>;
  /** Primary source (outlined) — what `tectonIcons[].source` reports. */
  source: Source;
  /** lucide-react export used for the fallback, when any. */
  lucideExport: string | null;
  code: string;
}

function indentBlock(lines: string[], depth: number): string {
  const pad = "  ".repeat(depth);
  return lines.map((l) => (l ? pad + l : l)).join("\n");
}

function rootAttrsLiteral(attrs: Map<string, string>): string {
  if (!attrs.size) return "{}";
  const pairs: string[] = [];
  for (const [name, value] of attrs) {
    const key = toJsxAttrName(name);
    const safeKey = /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
    pairs.push(`${safeKey}: ${key === "style" ? styleToJsx(value).slice(1, -1) : JSON.stringify(value)}`);
  }
  return `{ ${pairs.join(", ")} }`;
}

/** One variant's normalised SVG plus where it came from (for the header comment). */
interface SvgSource {
  svg: string;
  origin: string;
}

/**
 * Turn a Tecton export definition into normalised `<svg>` strings per variant.
 * Figma's conic-gradient hack (`<foreignObject>` + `data-figma-*` attributes)
 * is dropped: the clipPath-referenced `<path>` keeps the shape, and the
 * gradient is re-expressed as an SVG `<linearGradient>` fill on that path.
 */
function definitionToSources(def: TectonSvgIcon, origin: string): Record<IconVariant, SvgSource | undefined> {
  const clean = (markup: string) => {
    // Figma exports conic gradients as a <foreignObject> with a CSS gradient
    // inside a clip-path group. Browsers render it, so multi-colour glyphs keep
    // it; monochrome glyphs drop it (the clipped <path> already draws the shape).
    const withoutGradientHack = def.colored
      ? markup
      : markup.replace(/<g[^>]*data-figma-skip-parse="true"[^>]*>[\s\S]*?<\/g>\s*<\/g>/g, "");
    return withoutGradientHack.replace(/\s+data-figma-[\w-]+="(?:[^"\\]|\\.)*"/g, "");
  };
  // The export's paths carry no fill: they inherit from the root, so the root
  // fills with currentColor (the same contract as lucide's stroke="currentColor").
  const wrap = (inner: string) =>
    normalizeSvg(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${def.viewBox}" fill="currentColor">${clean(inner)}</svg>`, {
      keepColors: def.colored,
    });
  return {
    outlined: def.outline ? { svg: wrap(def.outline), origin: `${origin} (outline)` } : undefined,
    filled: def.filled ? { svg: wrap(def.filled), origin: `${origin} (filled)` } : undefined,
  };
}

/** Load every `icons-src/tecton/<slug>.ts` definition (bun/tsx can import TS directly). */
async function loadTectonDefinitions(): Promise<Map<string, { def: TectonSvgIcon; file: string }>> {
  const out = new Map<string, { def: TectonSvgIcon; file: string }>();
  if (!existsSync(TECTON_DEFINITIONS_DIR)) return out;
  for (const name of readdirSync(TECTON_DEFINITIONS_DIR).sort()) {
    if (!/\.ts$/.test(name) || name === "index.ts") continue;
    const file = path.join(TECTON_DEFINITIONS_DIR, name);
    // a file URL, not a path: `import("C:\\…")` would read the drive letter as a URL scheme
    const mod = (await import(pathToFileURL(file).href)) as Record<string, unknown>;
    const def = Object.values(mod).find(
      (v): v is TectonSvgIcon => typeof v === "object" && v !== null && "slug" in v && "viewBox" in v,
    );
    if (!def) throw new Error(`${path.relative(pkgRoot, file)}: no defineTectonSvgIcon() export found`);
    if (out.has(def.slug)) throw new Error(`duplicate Tecton icon definition for "${def.slug}"`);
    out.set(def.slug, { def, file });
  }
  return out;
}

/** The `viewBox` of the root `<svg>`, or null when it carries none. */
function rootViewBox(svg: string): string | null {
  const root = svg.trim().match(/^<svg\b([^>]*)>/i);
  return root ? (parseAttributes(root[1]).get("viewBox") ?? null) : null;
}

/** Rewrite the root `<svg>`'s `viewBox`, leaving every other attribute and all path data alone. */
function withRootViewBox(svg: string, viewBox: string): string {
  return svg.replace(/^(\s*<svg\b[^>]*?)viewBox="[^"]*"/i, `$1viewBox="${viewBox}"`);
}

/**
 * Crop each variant's viewBox by ICON_VIEWBOX_INSET so the glyph renders
 * larger, clamped per icon so nothing is ever clipped (see the constant).
 *
 * Variants that were authored on the same viewBox are measured together and
 * get one shared crop, so toggling `variant` never shifts or rescales the
 * glyph. Only the root `viewBox` attribute changes; the path data is untouched.
 *
 * Mutates `sources` in place and returns the header-comment lines describing
 * what happened, so a reader of the generated file can see the crop.
 */
function applyOpticalCrop(sources: Record<IconVariant, SvgSource | undefined>): string[] {
  const groups = new Map<string, IconVariant[]>();
  for (const variant of ICON_VARIANTS) {
    const viewBox = sources[variant] && rootViewBox(sources[variant]!.svg);
    if (viewBox) groups.set(viewBox, [...(groups.get(viewBox) ?? []), variant]);
  }

  const notes: string[] = [];
  for (const [viewBox, variants] of groups) {
    const crop = opticalCrop(
      viewBox,
      variants.map((variant) => sources[variant]!.svg),
      ICON_VIEWBOX_INSET,
    );
    // Only labelled per variant in the (currently hypothetical) case of an icon
    // whose two variants were authored on different grids.
    const who = groups.size > 1 ? `${variants.join("+")} ` : "";
    if (crop.cropped) {
      for (const variant of variants) sources[variant]!.svg = withRootViewBox(sources[variant]!.svg, crop.viewBox);
      notes.push(`// ${who}viewBox: "${viewBox}" cropped to "${crop.viewBox}" (inset ${crop.padding}, ${crop.scale}x)`);
    } else if (crop.unmeasured?.length) {
      const tags = crop.unmeasured.map((tag) => `<${tag}>`).join(", ");
      notes.push(`// ${who}viewBox: "${viewBox}" kept (${tags} cannot be measured)`);
    } else {
      notes.push(`// ${who}viewBox: "${viewBox}" kept (glyph reaches the edge)`);
    }
  }
  return notes;
}

function genSvgComponent(entry: IconManifestEntry, ident: string, sources: Record<IconVariant, SvgSource | undefined>): string {
  const cropNotes = applyOpticalCrop(sources);
  // Resolve each variant to a parsed SVG, falling back to the other variant.
  const parsed: Partial<Record<IconVariant, ParsedSvg>> = {};
  for (const variant of ICON_VARIANTS) {
    const src = sources[variant];
    if (src) parsed[variant] = parseSvgForJsx(src.svg, src.origin);
  }
  const outlined = parsed.outlined ?? parsed.filled!;
  const filled = parsed.filled ?? parsed.outlined!;
  const sameGlyph =
    parsed.outlined === undefined ||
    parsed.filled === undefined ||
    parsed.outlined.childrenJsx.join("\n") === parsed.filled.childrenJsx.join("\n");

  // The source's own stroke-width is the default for the `strokeWidth` prop;
  // it is applied through tectonSvgAttrs(), so keep it out of ROOT.
  const strokeWidths: Record<IconVariant, string | undefined> = {
    outlined: outlined.rootAttrs.get("stroke-width"),
    filled: filled.rootAttrs.get("stroke-width"),
  };
  outlined.rootAttrs.delete("stroke-width");
  filled.rootAttrs.delete("stroke-width");

  const sourceComment = ICON_VARIANTS.filter((v) => sources[v])
    .map((v) => `//   ${v}: ${sources[v]!.origin}`)
    .join("\n");

  const body = sameGlyph
    ? indentBlock(outlined.childrenJsx, 3)
    : [
        "      {variant === \"filled\" ? (",
        "        <>",
        indentBlock(filled.childrenJsx, 5),
        "        </>",
        "      ) : (",
        "        <>",
        indentBlock(outlined.childrenJsx, 5),
        "        </>",
        "      )}",
      ].join("\n");

  return `${HEADER}// Source SVGs:
${sourceComment}
${cropNotes.join("\n")}
import type { SVGProps } from "react"
import type { TectonIconProps, TectonIconVariant } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** Root <svg> presentation attributes from the source files, per variant. */
const ROOT: Record<TectonIconVariant, SVGProps<SVGSVGElement>> = {
  outlined: ${rootAttrsLiteral(outlined.rootAttrs)},
  filled: ${rootAttrsLiteral(filled.rootAttrs)},
}

const VIEW_BOX: Record<TectonIconVariant, string> = {
  outlined: ${JSON.stringify(outlined.viewBox)},
  filled: ${JSON.stringify(filled.viewBox)},
}

/** The source's own stroke-width — default for the \`strokeWidth\` prop. */
const STROKE_WIDTH: Record<TectonIconVariant, string | undefined> = {
  outlined: ${JSON.stringify(strokeWidths.outlined)},
  filled: ${JSON.stringify(strokeWidths.filled)},
}

/** ${entry.label} — ${entry.description} */
export function ${ident}({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={VIEW_BOX[variant]}
      {...ROOT[variant]}
      {...tectonSvgAttrs(size, strokeWidth ?? STROKE_WIDTH[variant], absoluteStrokeWidth, VIEW_BOX[variant])}
      className={className}
      data-tecton-icon=${JSON.stringify(entry.slug)}
      data-tecton-source="svg"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
${body}
    </svg>
  )
}
${ident}.displayName = ${JSON.stringify(ident)}
`;
}

function genLucideFallbackComponent(entry: IconManifestEntry, ident: string, lucideExport: string): string {
  return `${HEADER}// No SVG source yet — renders lucide-react's \`${lucideExport}\` (manifest: lucide: "${entry.lucide}").
// Drop icons-src/outlined/${entry.slug}.svg in place and re-run \`pnpm icons:build\`.
import { ${lucideExport} as Fallback } from "lucide-react"
import type { TectonIconProps } from "./types"

/** ${entry.label} — ${entry.description} */
export function ${ident}({
  size = 24,
  strokeWidth,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <Fallback
      size={size}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      className={className}
      data-tecton-icon=${JSON.stringify(entry.slug)}
      data-tecton-source="lucide-fallback"
      data-tecton-variant={variant}
      {...props}
    />
  )
}
${ident}.displayName = ${JSON.stringify(ident)}
`;
}

function genPlaceholderComponent(entry: IconManifestEntry, ident: string): string {
  return `${HEADER}// No SVG source and no lucide equivalent — renders a dashed placeholder.
// Drop icons-src/outlined/${entry.slug}.svg in place and re-run \`pnpm icons:build\`.
import type { TectonIconProps } from "./types"
import { tectonSvgAttrs } from "./_runtime"

/** ${entry.label} — ${entry.description} (placeholder) */
export function ${ident}({
  size = 24,
  strokeWidth = 2,
  absoluteStrokeWidth,
  variant = "outlined",
  className,
  ...props
}: TectonIconProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...tectonSvgAttrs(size, strokeWidth, absoluteStrokeWidth)}
      className={className}
      data-tecton-icon=${JSON.stringify(entry.slug)}
      data-tecton-source="placeholder"
      data-tecton-variant={variant}
      aria-hidden={props["aria-label"] || props["aria-labelledby"] ? undefined : true}
      {...props}
    >
      <rect x="3" y="3" width="18" height="18" rx="3" strokeDasharray="3 2" />
    </svg>
  )
}
${ident}.displayName = ${JSON.stringify(ident)}
`;
}

const TYPES_TS = `${HEADER}import type { ReactElement, SVGProps } from "react"

export type TectonIconVariant = "outlined" | "filled"

/**
 * Where a rendered icon's glyph comes from:
 *   - \`svg\`              the real Tecton glyph from icons-src/
 *   - \`lucide-fallback\`  the closest lucide-react icon (no Tecton SVG yet)
 *   - \`placeholder\`      dashed square (no Tecton SVG, no lucide peer)
 */
export type TectonIconSource = "svg" | "lucide-fallback" | "placeholder"

/**
 * lucide-compatible icon props. Every Tecton icon is a plain function
 * component (React 19 forwards \`ref\` as a prop, so no forwardRef needed).
 */
export interface TectonIconProps extends SVGProps<SVGSVGElement> {
  /** Width and height (default 24). */
  size?: number | string
  /** Stroke width for stroke-based glyphs; defaults to the glyph's own. */
  strokeWidth?: number | string
  /** Keep the stroke visually constant when \`size\` changes (lucide semantics). */
  absoluteStrokeWidth?: boolean
  /** Glyph style (default \`outlined\`). */
  variant?: TectonIconVariant
}

export type TectonIconComponent = ((props: TectonIconProps) => ReactElement) & { displayName?: string }

/** One row of the \`tectonIcons\` gallery array. */
export interface TectonIconEntry {
  /** PascalCase name without suffix, e.g. \`AddCircle\`. */
  name: string
  /** Exported identifier / gallery label, e.g. \`AddCircleIcon\`. */
  label: string
  /** kebab-case id; also the \`data-tecton-icon\` value and the file name. */
  slug: string
  description: string
  Icon: TectonIconComponent
  /** Source of the default (outlined) variant. */
  source: TectonIconSource
  /** Source per variant (a missing variant falls back to the other one). */
  sources: Record<TectonIconVariant, TectonIconSource>
  /** Oil & gas / subsurface domain glyph. */
  domain: boolean
  /** Closest lucide-react icon (kebab-case lucide name) or null. */
  lucide: string | null
}
`;

const RUNTIME_TS = `${HEADER}/**
 * Size / stroke-width maths shared by generated SVG-backed icons.
 * Mirrors lucide: with \`absoluteStrokeWidth\` the stroke stays visually
 * constant across sizes (strokeWidth * viewBoxSize / size).
 */
export function tectonSvgAttrs(
  size: number | string,
  strokeWidth: number | string | undefined,
  absoluteStrokeWidth: boolean | undefined,
  viewBox = "0 0 24 24",
): { width: number | string; height: number | string; strokeWidth?: number | string } {
  const attrs: { width: number | string; height: number | string; strokeWidth?: number | string } = {
    width: size,
    height: size,
  }
  if (strokeWidth === undefined) return attrs
  const numericSize = typeof size === "number" ? size : Number.parseFloat(size)
  const viewBoxSize = Number.parseFloat(viewBox.split(/\\s+/)[2] ?? "24") || 24
  attrs.strokeWidth =
    absoluteStrokeWidth && Number.isFinite(numericSize) && numericSize > 0
      ? (Number(strokeWidth) * viewBoxSize) / numericSize
      : strokeWidth
  return attrs
}
`;

function genIndex(builds: IconBuild[]): string {
  const exports = builds.map((b) => `export { ${b.ident} } from "./${b.entry.slug}"`).join("\n");
  const imports = builds.map((b) => `import { ${b.ident} } from "./${b.entry.slug}"`).join("\n");
  const rows = builds
    .map((b) => {
      const e = b.entry;
      return `  { name: ${JSON.stringify(e.name)}, label: ${JSON.stringify(e.label)}, slug: ${JSON.stringify(e.slug)}, description: ${JSON.stringify(e.description)}, Icon: ${b.ident}, source: ${JSON.stringify(b.source)}, sources: ${JSON.stringify(b.sources)}, domain: ${e.domain}, lucide: ${JSON.stringify(e.lucide)} },`;
    })
    .join("\n");
  return `${HEADER}import type { TectonIconEntry } from "./types"
${imports}

export type { TectonIconComponent, TectonIconEntry, TectonIconProps, TectonIconSource, TectonIconVariant } from "./types"

${exports}

/** Every Tecton icon, in manifest (alphabetical) order — drives the docs gallery. */
export const tectonIcons: readonly TectonIconEntry[] = [
${rows}
]

/** Lookup by slug, e.g. \`tectonIconsBySlug["add-circle"]\`. */
export const tectonIconsBySlug: Readonly<Record<string, TectonIconEntry>> = Object.fromEntries(
  tectonIcons.map((entry) => [entry.slug, entry]),
)
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main(): Promise<void> {
  const manifest = loadManifest();
  const lucide = loadLucideExports();
  const sources = scanIconSources(ICONS_SRC_DIR);
  const definitions = await loadTectonDefinitions();
  const manifestSlugs = new Set(manifest.icons.map((i) => i.slug));
  for (const slug of definitions.keys()) {
    if (!manifestSlugs.has(slug)) console.warn(`warning: icons-src/tecton/${slug}.ts has no entry in icons/icons.json (ignored)`);
  }

  // Warn about SVGs that no manifest entry claims.
  const slugs = new Set(manifest.icons.map((i) => i.slug));
  for (const variant of ICON_VARIANTS) {
    for (const slug of sources[variant].keys()) {
      if (!slugs.has(slug)) console.warn(`warning: icons-src/${variant}/${slug}.svg has no entry in icons/icons.json (ignored)`);
    }
  }

  // Per-icon builds.
  const builds: IconBuild[] = [];
  const idents = new Set<string>();
  const badLucide: string[] = [];
  for (const entry of manifest.icons.filter(isShippedIcon)) {
    const ident = entry.label;
    if (!/^[A-Z][A-Za-z0-9]*Icon$/.test(ident)) throw new Error(`manifest label "${ident}" is not a valid PascalCase identifier ending in "Icon"`);
    if (idents.has(ident)) throw new Error(`duplicate manifest label "${ident}"`);
    idents.add(ident);

    // Loose SVG files override the export; the export is the default source.
    const definition = definitions.get(entry.slug);
    const fromDefinition = definition
      ? definitionToSources(definition.def, path.relative(pkgRoot, definition.file).split(path.sep).join("/"))
      : { outlined: undefined, filled: undefined };
    const svgSources: Record<IconVariant, SvgSource | undefined> = { outlined: undefined, filled: undefined };
    for (const variant of ICON_VARIANTS) {
      const file = sources[variant].get(entry.slug);
      svgSources[variant] = file
        ? { svg: normalizeSvg(readFileSync(file, "utf8")), origin: path.relative(pkgRoot, file).split(path.sep).join("/") }
        : fromDefinition[variant];
    }
    const hasSvg = Boolean(svgSources.outlined || svgSources.filled);

    let lucideExport: string | null = null;
    if (entry.lucide) {
      lucideExport = kebabToPascal(entry.lucide);
      if (lucide && !lucide.values.has(lucideExport)) {
        badLucide.push(`${entry.slug}: lucide "${entry.lucide}" (${lucideExport}) — try: ${suggestLucide(lucideExport, lucide).join(", ") || "?"}`);
        lucideExport = null;
      }
    }

    let code: string;
    let source: Source;
    if (hasSvg) {
      source = "svg";
      code = genSvgComponent(entry, ident, svgSources);
    } else if (lucideExport) {
      source = "lucide-fallback";
      code = genLucideFallbackComponent(entry, ident, lucideExport);
    } else {
      source = "placeholder";
      code = genPlaceholderComponent(entry, ident);
    }
    builds.push({ entry, ident, source, sources: { outlined: source, filled: source }, lucideExport, code });
  }
  if (badLucide.length) {
    throw new Error(`icons/icons.json references lucide icons that lucide-react does not export:\n  ${badLucide.join("\n  ")}`);
  }

  // Files to write.
  const outputs = new Map<string, string>();
  for (const b of builds) outputs.set(path.join(ICONS_OUT_DIR, `${b.entry.slug}.tsx`), b.code);
  outputs.set(path.join(ICONS_OUT_DIR, "types.ts"), TYPES_TS);
  outputs.set(path.join(ICONS_OUT_DIR, "_runtime.ts"), RUNTIME_TS);
  outputs.set(path.join(ICONS_OUT_DIR, "index.ts"), genIndex(builds));

  // Stale generated files (icons removed from the manifest).
  const stale: string[] = [];
  if (existsSync(ICONS_OUT_DIR)) {
    for (const name of readdirSync(ICONS_OUT_DIR).sort()) {
      const file = path.join(ICONS_OUT_DIR, name);
      if (outputs.has(file) || !/\.tsx?$/.test(name)) continue;
      // a CRLF checkout still carries the header, with a \r before its \n
      if (readFileSync(file, "utf8").replace(/\r\n/g, "\n").startsWith(HEADER)) stale.push(file);
    }
  }

  // Write (or check).
  let changed = 0;
  for (const [file, content] of outputs) {
    // Windows checkouts may carry CRLF; compare on normalised line endings.
    const current = existsSync(file) ? readFileSync(file, "utf8").replace(/\r\n/g, "\n") : null;
    if (current === content) continue;
    changed++;
    if (CHECK_MODE) console.log(`would ${current === null ? "create" : "update"} ${path.relative(pkgRoot, file)}`);
    else {
      mkdirSync(path.dirname(file), { recursive: true });
      writeFileSync(file, content, "utf8");
    }
  }
  for (const file of stale) {
    changed++;
    if (CHECK_MODE) console.log(`would delete ${path.relative(pkgRoot, file)}`);
    else rmSync(file);
  }

  // Summary.
  const count = (s: Source) => builds.filter((b) => b.source === s).length;
  console.log(
    [
      `icons: ${builds.length} component(s) → ${path.relative(pkgRoot, ICONS_OUT_DIR)}/`,
      `  svg: ${count("svg")}   lucide-fallback: ${count("lucide-fallback")}   placeholder: ${count("placeholder")}`,
      `  ${CHECK_MODE ? "changes pending" : "files changed"}: ${changed}${stale.length ? ` (stale removed: ${stale.length})` : ""}`,
    ].join("\n"),
  );
  if (CHECK_MODE && changed) {
    console.error("build-icons --check: outputs are out of date — run `pnpm icons:build`");
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(`build-icons: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
