/// <reference types="node" />
/**
 * Builds the `@tecton` shadcn registry.
 *
 * 1. Stages the Tecton sources (src/tecton, src/blocks, src/hooks, src/lib,
 *    src/styles) into registry/src with package imports rewritten to the
 *    `@/…` aliases the shadcn CLI understands
 *    (`@tecton/react/components/x` -> `@/components/ui/x`,
 *     `@tecton/react/tecton/x`     -> `@/components/tecton/x`, …).
 * 2. Writes registry.json (theme, tokens stylesheet, fonts, components, blocks).
 * 3. Runs `shadcn build registry.json --output <out>` (the CLI ships with the
 *    `shadcn` runtime dependency) so apps/www/public/r/<name>.json exist.
 *
 * Usage: bun run scripts/registry-build.mts [--output ../../apps/www/public/r]
 */
import { spawnSync } from "node:child_process"
import { promises as fs } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const PKG = path.resolve(HERE, "..")
const SRC = path.join(PKG, "src")
const STAGE = path.join(PKG, "registry/src")
const outputFlag = process.argv.indexOf("--output")
const OUTPUT = path.resolve(
  PKG,
  outputFlag > -1 ? process.argv[outputFlag + 1] : "../../apps/www/public/r"
)

type RegistryFile = {
  path: string
  type: string
  target?: string
}

type RegistryItem = {
  name: string
  type: string
  title?: string
  description?: string
  dependencies?: string[]
  registryDependencies?: string[]
  categories?: string[]
  files?: RegistryFile[]
  cssVars?: Record<string, Record<string, string>>
  css?: Record<string, unknown>
}

const IMPORT_REWRITES: [RegExp, string][] = [
  [/^@tecton\/react\/components\/(.+)$/, "@/components/ui/$1"],
  [/^@tecton\/react\/tecton\/(.+)$/, "@/components/tecton/$1"],
  [/^@tecton\/react\/hooks\/(.+)$/, "@/hooks/$1"],
  [/^@tecton\/react\/lib\/(.+)$/, "@/lib/$1"],
  [/^@tecton\/react\/blocks\/([^/]+)\/(.+)$/, "@/components/$1/$2"],
]

/** External packages the Tecton sources may import, mapped to registry deps. */
const KNOWN_DEPENDENCIES = new Set([
  "react-aria-components",
  "class-variance-authority",
  "cn",
  "lucide-react",
  "@tanstack/react-table",
  "recharts",
  "sonner",
  "@internationalized/date",
])

function rewrite(source: string) {
  const deps = new Set<string>()
  const registryDeps = new Set<string>()
  const code = source.replace(
    /(from\s+|import\s+|import\()\s*(["'])([^"']+)\2/g,
    (match, prefix: string, quote: string, spec: string) => {
      const ui = spec.match(/^@tecton\/react\/components\/(.+)$/)
      if (ui) registryDeps.add(ui[1])
      const tecton = spec.match(/^@tecton\/react\/tecton\/(.+)$/)
      if (tecton) registryDeps.add(`@tecton/${tecton[1]}`)
      const hook = spec.match(/^@tecton\/react\/hooks\/(.+)$/)
      if (hook) registryDeps.add(hook[1])
      for (const [pattern, replacement] of IMPORT_REWRITES) {
        if (pattern.test(spec)) {
          return `${prefix}${quote}${spec.replace(pattern, replacement)}${quote}`
        }
      }
      const bare = spec.startsWith("@") ? spec.split("/").slice(0, 2).join("/") : spec.split("/")[0]
      if (KNOWN_DEPENDENCIES.has(bare)) deps.add(bare)
      return match
    }
  )
  return { code, deps, registryDeps }
}

async function stage(relative: string) {
  const source = await fs.readFile(path.join(SRC, relative), "utf8")
  const { code, deps, registryDeps } = rewrite(source)
  const out = path.join(STAGE, relative)
  await fs.mkdir(path.dirname(out), { recursive: true })
  await fs.writeFile(out, code)
  return { path: path.relative(PKG, out), deps, registryDeps }
}

function titleCase(slug: string) {
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
}

async function main() {
  await fs.rm(STAGE, { recursive: true, force: true })
  const items: RegistryItem[] = []

  // Theme (generated by tokens-build) ----------------------------------------
  const theme = JSON.parse(await fs.readFile(path.join(PKG, "registry/theme.json"), "utf8"))
  items.push({
    name: "theme",
    type: "registry:theme",
    title: theme.title ?? "Tecton theme",
    description: theme.description,
    dependencies: ["@fontsource-variable/figtree", "@fontsource/ibm-plex-mono"],
    cssVars: theme.cssVars,
    css: {
      '@import "@fontsource-variable/figtree"': {},
      '@import "@fontsource/ibm-plex-mono"': {},
    },
  })

  // Raw tokens stylesheet -----------------------------------------------------
  const tokens = await stage("styles/tecton-tokens.css")
  items.push({
    name: "tokens",
    type: "registry:style",
    title: "Tecton tokens",
    description: "Raw --tecton-* design tokens as CSS custom properties.",
    files: [{ path: tokens.path, type: "registry:file", target: "styles/tecton-tokens.css" }],
  })

  // Hooks (only the CLI-generated use-mobile is referenced by Tecton code) ----
  for (const file of await fs.readdir(path.join(SRC, "hooks"))) {
    if (!file.endsWith(".ts")) continue
    const name = file.replace(/\.ts$/, "")
    const staged = await stage(`hooks/${file}`)
    items.push({
      name,
      type: "registry:hook",
      files: [{ path: staged.path, type: "registry:hook" }],
    })
  }

  // Tecton components ----------------------------------------------------------
  for (const file of (await fs.readdir(path.join(SRC, "tecton"))).sort()) {
    if (!file.endsWith(".tsx")) continue
    const name = file.replace(/\.tsx$/, "")
    const staged = await stage(`tecton/${file}`)
    items.push({
      name,
      type: "registry:component",
      title: titleCase(name),
      description: `Tecton ${titleCase(name)} component.`,
      dependencies: [...staged.deps].sort(),
      registryDependencies: [...staged.registryDeps].sort(),
      files: [
        {
          path: staged.path,
          type: "registry:component",
          target: `components/tecton/${file}`,
        },
      ],
    })
  }

  // Blocks --------------------------------------------------------------------
  const blocksDir = path.join(SRC, "blocks")
  for (const block of (await fs.readdir(blocksDir, { withFileTypes: true })).sort((a, b) =>
    a.name.localeCompare(b.name)
  )) {
    if (!block.isDirectory()) continue
    const files: RegistryFile[] = []
    const deps = new Set<string>()
    const registryDeps = new Set<string>()
    const walk = async (dir: string) => {
      for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name)
        if (entry.isDirectory()) {
          await walk(full)
          continue
        }
        if (!/\.(tsx?|css)$/.test(entry.name)) continue
        const relative = path.relative(SRC, full)
        const staged = await stage(relative)
        staged.deps.forEach((d) => deps.add(d))
        staged.registryDeps.forEach((d) => registryDeps.add(d))
        const inBlock = path.relative(path.join(blocksDir, block.name), full)
        if (inBlock === "page.tsx") {
          files.push({ path: staged.path, type: "registry:page", target: `app/${block.name}/page.tsx` })
        } else {
          files.push({
            path: staged.path,
            type: /\.tsx?$/.test(entry.name) ? "registry:component" : "registry:file",
            target: `components/${block.name}/${inBlock}`,
          })
        }
      }
    }
    await walk(path.join(blocksDir, block.name))
    const registryMeta = await fs.readFile(path.join(blocksDir, "index.ts"), "utf8")
    const meta = registryMeta.match(
      new RegExp(`name: "${block.name}",\\s*title: "([^"]+)",\\s*description:\\s*"([^"]+)",\\s*category: "([^"]+)"`)
    )
    items.push({
      name: block.name,
      type: "registry:block",
      title: meta?.[1] ?? titleCase(block.name),
      description: meta?.[2] ?? "",
      categories: meta ? [meta[3]] : undefined,
      dependencies: [...deps].sort(),
      registryDependencies: [...registryDeps].sort(),
      files,
    })
  }

  const registry = {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: "tecton",
    homepage: "https://github.com/rpkapps/tecton-ui-1",
    items,
  }
  await fs.writeFile(path.join(PKG, "registry.json"), JSON.stringify(registry, null, 2) + "\n")
  console.log(`[registry:build] registry.json — ${items.length} items`)

  const cli = process.env.SHADCN_CLI ?? path.join(PKG, "node_modules/.bin/shadcn")
  const result = spawnSync(cli, ["build", "registry.json", "--output", OUTPUT], {
    cwd: PKG,
    stdio: "inherit",
    env: { ...process.env, npm_config_user_agent: "pnpm/10.33.0 npm/? node/v22 linux x64" },
  })
  if (result.status !== 0) {
    throw new Error(`shadcn build failed (exit ${result.status})`)
  }
  console.log(`[registry:build] wrote ${OUTPUT}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
