/**
 * skills-build — assembles the generated Agent Skills from the guideline files.
 *
 *   bun run scripts/skills-build.mts            (pnpm skills:build)
 *   bun run scripts/skills-build.mts --check    (pnpm skills:check — CI)
 *
 * Test flags: --guidelines <dir> reads guideline files from somewhere else,
 * --out <dir> writes the skills somewhere else (used with fixture folders).
 *
 * Written:
 *   skills/<family>/SKILL.md      one per family with a `skill` entry in
 *                                 families.json, assembled from that family's
 *                                 guideline files
 *   skills/choose-component/      the cross-family decision table
 *
 * The hand-written skills (core, react-aria, theming) are left alone: only
 * files carrying the generated marker below are written, compared or removed.
 *
 * A family whose guideline files are not all there yet is skipped and the
 * missing modules are printed, so the build keeps working while the guidelines
 * land one at a time. TanStack Intent caps a skill at 500 lines; the build
 * fails rather than emitting a file Intent would reject.
 *
 * A family skill is checklist first: the family's `skill.checklist` from
 * families.json, then the decision table, then one section per component whose
 * "Don't" keeps the code of the CRITICAL mistakes and reduces the rest to one
 * bullet naming the mechanism and the guideline file that carries the code.
 */
/// <reference types="node" />
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"
import {
  GUIDELINES_DIR,
  PKG_ROOT,
  loadGuidelines,
  modulePathOf,
  renderDontEntry,
  renderImportLine,
  renderNotFor,
  resolveReference,
} from "./guidelines-lib.mts"
import type { Catalog, DontEntry, Guideline } from "./guidelines-lib.mts"

const MARKER = "<!-- Generated by `pnpm --filter @tecton/react skills:build`"
const GENERATED_COMMENT = `${MARKER} from guidelines/*.md and guidelines/families.json — do not edit. -->`
const MAX_SKILL_LINES = 500
const MAX_DESCRIPTION = 1024
const ARTIFACTS_DIR = "_artifacts"

function argValue(flag: string): string | undefined {
  const at = process.argv.indexOf(flag)
  return at === -1 ? undefined : process.argv[at + 1]
}

// ---------------------------------------------------------------------------
// frontmatter
// ---------------------------------------------------------------------------

function yamlString(value: string) {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
}

function frontmatter(fields: {
  name: string
  description: string
  version: string
  sources: string[]
}) {
  return [
    "---",
    `name: ${fields.name}`,
    `description: ${yamlString(fields.description)}`,
    "metadata:",
    "  type: sub-skill",
    '  library: "@tecton/react"',
    `  library_version: ${yamlString(fields.version)}`,
    "requires:",
    "  - core",
    "sources:",
    ...fields.sources.map((source) => `  - ${source}`),
    "---",
  ].join("\n")
}

// ---------------------------------------------------------------------------
// the decision table
// ---------------------------------------------------------------------------

type Row = { need: string; use: string; from: string }

function cell(text: string) {
  return text
    .replace(/\|/g, "\\|")
    .replace(/\s*\n\s*/g, " ")
    .trim()
    .replace(/\.$/, "")
    .replace(/^[a-z]/, (letter) => letter.toUpperCase())
}

/**
 * One row per member component, built from its first "Use it when" bullet, plus
 * one row per `notFor` entry — the boundaries are what makes the table a
 * decision table rather than a list of components.
 */
function decisionRows(
  members: Guideline[],
  catalog: Catalog,
  options: {
    /**
     * When set, `notFor` rows whose replacement lives in one of these modules
     * are left out: the family skill carries the boundaries between its own
     * members, so the cross-family table only needs the ones that leave it.
     */
    omitTargetsIn?: Set<string>
  } = {}
): Row[] {
  const rows: Row[] = []
  const seen = new Set<string>()
  const push = (row: Row) => {
    const key = `${row.need.toLowerCase()}|${row.use}`
    if (seen.has(key)) return
    seen.add(key)
    rows.push(row)
  }
  for (const guideline of members) {
    const first = guideline.sections.useWhenBullets[0] ?? guideline.meta.component
    push({
      need: first,
      use: guideline.meta.component,
      from: modulePathOf(guideline.module),
    })
    for (const entry of guideline.meta.notFor) {
      const reference = resolveReference(entry.use, catalog)
      if (!reference) continue
      if (reference.kind === "module" && options.omitTargetsIn?.has(reference.module)) continue
      push({
        need: entry.need,
        use: reference.name,
        from: reference.kind === "module" ? reference.modulePath : reference.importFrom,
      })
    }
  }
  return rows
}

function renderTable(rows: Row[]) {
  return [
    "| You need … | Use … | Import |",
    "| --- | --- | --- |",
    ...rows.map((row) => `| ${cell(row.need)} | \`${row.use}\` | \`${row.from}\` |`),
  ].join("\n")
}

// ---------------------------------------------------------------------------
// a family skill
// ---------------------------------------------------------------------------

function lowerFirst(text: string) {
  return text.charAt(0).toLowerCase() + text.slice(1)
}

/**
 * The sentence that names the mechanism, on one line: the closing sentence the
 * parser split off, falling back to the last paragraph of the entry when there
 * is none (only reachable for a file the validator would reject).
 */
function mechanismOf(entry: DontEntry): string {
  const text = entry.closing || (entry.body.split(/\n[ \t]*\n/).pop() ?? "")
  return text.replace(/\s*\n\s*/g, " ").trim()
}

/**
 * A family can hold nine components and a skill is capped at 500 lines, so only
 * the CRITICAL mistakes keep their Wrong/Correct code. HIGH and MEDIUM become
 * one bullet each — the severity, the title, the mechanism and the guideline
 * file in `sources` that carries the code.
 */
function memberSection(guideline: Guideline, catalog: Catalog) {
  const entries = guideline.sections.dontEntries
  const compact = entries.filter((entry) => entry.severity !== "CRITICAL")
  const dont = [
    ...entries
      .filter((entry) => entry.severity === "CRITICAL")
      .map((entry) => renderDontEntry(entry, 4)),
    ...(compact.length
      ? [
          compact
            .map(
              (entry) =>
                `- **${entry.severity}** ${entry.title} — ${mechanismOf(entry)} (guidelines/${guideline.name}.md)`
            )
            .join("\n"),
        ]
      : []),
  ]
  const parts = [
    `## ${guideline.meta.component}`,
    "",
    "```tsx",
    renderImportLine(guideline.meta),
    "```",
    "",
    "### Use it when",
    "",
    guideline.sections.useWhen,
    "",
    "### Not for",
    "",
    renderNotFor(guideline.meta, catalog, "skill").join("\n"),
    "",
    "### Do",
    "",
    guideline.sections.do,
    "",
    "### Don't",
    "",
    dont.join("\n\n"),
  ]
  return parts.join("\n")
}

function familySkill(
  family: string,
  members: Guideline[],
  catalog: Catalog
): { file: string; content: string } {
  const entry = catalog.families.families[family]
  const names = members.map((member) => member.meta.component)
  const header =
    `${entry.title} — ${lowerFirst(entry.choice)}. Start from the table, then read the section of ` +
    `the component it sends you to: ${names.join(", ")}. Each one is imported from its own module; ` +
    `\`@tecton/react\` has no root export.`
  // The checklist lands with the family's `skill` entry; until it does, the
  // skill is the table and the sections, with nothing to re-read at the end.
  const checklist = (entry.skill?.checklist ?? []).map((item) => item.trim()).filter(Boolean)
  const body = [
    GENERATED_COMMENT,
    "",
    `# ${entry.title}`,
    "",
    header,
    ...(checklist.length ? ["", "## Checklist", "", ...checklist.map((item) => `- ${item}`)] : []),
    "",
    renderTable(decisionRows(members, catalog)),
    "",
    members.map((member) => memberSection(member, catalog)).join("\n\n"),
    ...(checklist.length
      ? ["", "Re-read the checklist above against the file you wrote before you report it done."]
      : []),
  ].join("\n")
  const content = [
    frontmatter({
      name: family,
      description: entry.skill?.description ?? "",
      version: catalog.version,
      sources: members.map((member) => `guidelines/${member.name}.md`),
    }),
    "",
    body,
    "",
  ].join("\n")
  return { file: path.join(family, "SKILL.md"), content }
}

// ---------------------------------------------------------------------------
// choose-component
// ---------------------------------------------------------------------------

function chooseComponentSkill(
  ready: Array<{ family: string; members: Guideline[] }>,
  catalog: Catalog
): { file: string; content: string } {
  const allFamilies = Object.keys(catalog.families.families)
  const description =
    `The decision table for @tecton/react: which component to reach for across ` +
    `${allFamilies.join(", ")}. Load it when the UI behaviour is clear but the component is not — ` +
    `it maps a need to one component, its import path and the family skill that carries the patterns.`
  const readyFamilies = new Set(ready.map((item) => item.family))
  const sections: string[] = []
  for (const { family, members } of ready) {
    const entry = catalog.families.families[family]
    sections.push(
      [
        `## ${entry.title}`,
        "",
        `${lowerFirst(entry.choice)}.`,
        "",
        renderTable(
          decisionRows(members, catalog, { omitTargetsIn: new Set(entry.modules) })
        ),
        "",
        `Load @tecton/react#${family} for the boundaries between these and the patterns.`,
      ].join("\n")
    )
  }
  const rest = allFamilies.filter((family) => !readyFamilies.has(family))
  if (rest.length) {
    sections.push(
      [
        "## Families without a skill yet",
        "",
        ...rest.map((family) => {
          const entry = catalog.families.families[family]
          const modules = entry.modules.map((moduleKey) => `\`${modulePathOf(moduleKey)}\``)
          return `- **${entry.title}**: ${modules.join(", ")}`
        }),
      ].join("\n")
    )
  }
  const body = [
    GENERATED_COMMENT,
    "",
    "# Choosing a Tecton component",
    "",
    "Every row is a need, the component that covers it and the module it is imported from. " +
      "Read the row, then load the family skill named under the table for the props, the " +
      "boundaries and the mistakes.",
    "",
    sections.join("\n\n"),
  ].join("\n")
  const content = [
    frontmatter({
      name: "choose-component",
      description,
      version: catalog.version,
      sources: [
        "guidelines/families.json",
        ...ready.flatMap(({ members }) => members.map((member) => `guidelines/${member.name}.md`)),
      ],
    }),
    "",
    body,
    "",
  ].join("\n")
  return { file: path.join("choose-component", "SKILL.md"), content }
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

function lineCount(content: string) {
  return content.replace(/\n$/, "").split("\n").length
}

/** Generated skill files already on disk, by `<dir>/SKILL.md`. */
function generatedOnDisk(outDir: string): string[] {
  if (!existsSync(outDir)) return []
  const found: string[] = []
  for (const entry of readdirSync(outDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === ARTIFACTS_DIR) continue
    const file = path.join(entry.name, "SKILL.md")
    const full = path.join(outDir, file)
    if (!existsSync(full)) continue
    if (readFileSync(full, "utf8").includes(MARKER)) found.push(file)
  }
  return found.sort()
}

function main() {
  const check = process.argv.includes("--check")
  const guidelinesDir = path.resolve(argValue("--guidelines") ?? GUIDELINES_DIR)
  const outDir = path.resolve(argValue("--out") ?? path.join(PKG_ROOT, "skills"))
  const { catalog, valid, invalid } = loadGuidelines(guidelinesDir)

  for (const [file, errors] of invalid) {
    console.warn(
      `skills: skipping ${path.basename(file)} — ${errors.length} problem(s); run guidelines:check`
    )
  }

  const ready: Array<{ family: string; members: Guideline[] }> = []
  for (const [family, entry] of Object.entries(catalog.families.families)) {
    if (!entry.skill) continue
    const missing = entry.modules.filter((moduleKey) => !valid.has(moduleKey))
    if (missing.length) {
      console.log(`skills: ${family} skipped — no guideline file yet for ${missing.join(", ")}`)
      continue
    }
    ready.push({
      family,
      members: entry.modules.map((moduleKey) => valid.get(moduleKey) as Guideline),
    })
  }

  const files = [
    ...ready.map(({ family, members }) => familySkill(family, members, catalog)),
    chooseComponentSkill(ready, catalog),
  ]

  const problems: string[] = []
  for (const { file, content } of files) {
    const lines = lineCount(content)
    if (lines > MAX_SKILL_LINES) {
      problems.push(`${file} is ${lines} lines; TanStack Intent allows ${MAX_SKILL_LINES}`)
    }
    const description = /^description: "((?:[^"\\]|\\.)*)"$/m.exec(content)?.[1] ?? ""
    if (description.length > MAX_DESCRIPTION) {
      problems.push(`${file}: description is ${description.length} characters (max ${MAX_DESCRIPTION})`)
    }
  }
  if (problems.length) {
    for (const problem of problems) console.error(`✗ ${problem}`)
    console.error("skills:build failed — shorten the guideline files or split the family.")
    process.exit(1)
  }

  const expected = new Set(files.map(({ file }) => file))
  const stale = generatedOnDisk(outDir).filter((file) => !expected.has(file))
  const drift: string[] = []

  for (const { file, content } of files) {
    const full = path.join(outDir, file)
    const current = existsSync(full) ? readFileSync(full, "utf8") : null
    if (current === content) continue
    const shown = file.split(path.sep).join("/")
    drift.push(current === null ? `${shown} (missing)` : `${shown} (stale)`)
    if (!check) {
      mkdirSync(path.dirname(full), { recursive: true })
      writeFileSync(full, content)
    }
  }
  for (const file of stale) {
    drift.push(`${file.split(path.sep).join("/")} (no longer generated)`)
    if (!check) {
      rmSync(path.join(outDir, file))
      const dir = path.dirname(path.join(outDir, file))
      if (!readdirSync(dir).length) rmSync(dir, { recursive: true })
    }
  }

  const summary = `${files.length} generated skill(s) from ${valid.size} guideline file(s)`
  if (check) {
    if (drift.length) {
      console.error(`skills:check failed — ${drift.length} file(s) differ:`)
      for (const item of drift) console.error(`  ${item}`)
      console.error("  run: pnpm --filter @tecton/react skills:build")
      process.exit(1)
    }
    console.log(`skills: up to date (${summary})`)
    return
  }
  console.log(
    drift.length ? `skills: wrote ${drift.length} file(s) (${summary})` : `skills: up to date (${summary})`
  )
}

main()
